### ISSUE TITLE
You can't rename folders

### ISSUE THREAD

**Issue by mcbalaam** [zen-browser/desktop#10052]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

Attempting to rename a folder seems to provide no feedback at all - nothing happens when you click the context menu button

### Expected behavior

A modal window/popup or at least a notification that this is not yet implemented was supposed to appear

### Actual behavior

Nothing happens when you click the button

### Steps to reproduce

1. Create a new folder
2. Open the context menu and select the "Rename folder" option
3. O B S E R V E

### Screenshots and videos

https://github.com/user-attachments/assets/9ad62b87-2dd2-4178-b28a-a66b3b1db47b

### Version

1.15t (Firefox 142.0.1) (2025-08-27) (64-bit)

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Tab Folders

### Relevant log output if applicable

```shell

```

**Comment by mr-cheffy** [comment]
Hi, do you have any mods, css, etc installed? Could you please send logs (ctrl+shift+J)

**Comment by mcbalaam** [comment]
> Hi, do you have any mods, css, etc installed? Could you please send logs (ctrl+shift+J)

<img width="960" height="340" alt="Image" src="https://github.com/user-attachments/assets/9ffd3209-1ea8-4029-8d40-003a8ce5ffaf" />

can this be caused by any of my extensions? I can try running a fresh installation of Zen on a virtual machine if so. Zen Mods are disabled. it spits all this out when I create a folder

**Comment by mcbalaam** [comment]
it just says "moz-extension". I'll send a paste if this is useful

**Comment by mr-cheffy** [comment]
Are those all the logs? Could you please try opening it on twilight?

**Comment by mcbalaam** [comment]
> Are those all the logs? Could you please try opening it on twilight?

I am using Twilight, as the version number says. yes, those are all the logs

https://github.com/user-attachments/assets/9795e85d-8583-4c41-86ea-2820d6139a8e

**Comment by mr-cheffy** [comment]
Could you please run it in "single process"

**Comment by mcbalaam** [comment]
no log output whatsoever in "single process" mode. no filters are applied

**Comment by mr-cheffy** [comment]
Are you using superpins or something similar?

**Comment by mcbalaam** [comment]
is that a Zen Mod? no, I don't. 

<img width="267" height="349" alt="Image" src="https://github.com/user-attachments/assets/39656951-87b1-4405-a334-254030eeace1" />

also a list of my extensions just in case

**Comment by taco-neko** [comment]
Adding onto this, it's not just renaming. Deleting also does not do anything. I have two folders that I created just permanently stuck there. They do not disappear even after a restart. It's really annoying

**Comment by mcbalaam** [comment]
> Adding onto this, it's not just renaming. Deleting also does not do anything.

deleting works for me though...

**Comment by tockudex** [comment]
I can't rename them either, nor can I change heir icon.
However, I use some mods, so the issue might lie there.

**Comment by taco-neko** [comment]
> > Adding onto this, it's not just renaming. Deleting also does not do anything.
> 
> deleting works for me though...

Oh, okay. I think I have a different issue then. My bad.

**Comment by rsramkis** [comment]
I did some testing this morning. So the following problems occur when Zen Browser uses the Settings > Look and Feel > Collapsed experience:

- Can create folders.
- Cannot rename because collapsed does not show folder name.
- Cannot Delete a folder.
- Dragging browser tabs to a folder visually is not clearly represented what folder it is assigned to.

Then if you switch the experience to Settings > Look and Feel > Multiple Tool bars, all functions work.

**Comment by Nanito111** [comment]
> I did some testing this morning. So the following problems occur when Zen Browser uses the Settings > Look and Feel > Collapsed experience:
> 
>     * Can create folders.
> 
>     * Cannot rename because collapsed does not show folder name.
> 
>     * Cannot Delete a folder.
> 
>     * Dragging browser tabs to a folder visually is not clearly represented what folder it is assigned to.
> 
> 
> Then if you switch the experience to Settings > Look and Feel > Multiple Tool bars, all functions work.

same here, when i change from collapse toolbar to multiple toolbar, all features works

**Comment by resting** [comment]
Renaming doesn't work for me too.
I can delete and change icon.
On Multiple toolbars Look and feel.

**Comment by Bxnie** [comment]
reproducible on 1.15.1b

No CSS, no mods, no extensions.

> Then if you switch the experience to Settings > Look and Feel > Multiple Tool bars, all functions work.

This solution has no effect for me, already using multiple toolbars :)

**Comment by Bxnie** [comment]
After some digging in about:config

If `zen.view.use-single-toolbar` is set to `false` -- Folders cannot be renamed
If `zen.view.use-single-toolbar` is set to `true` -- Folders can now be renamed

Hope this helps, can someone confirm this is reproducible?

**Comment by Hiori555** [comment]
I already use Multiple toolbar and renaming does not work. It works when I use Single toolbar.

**Comment by Lee-W** [comment]
> After some digging in about:config
> 
> If `zen.view.use-single-toolbar` is set to `false` -- Folders cannot be renamed If `zen.view.use-single-toolbar` is set to `true` -- Folders can now be renamed
> 
> Hope this helps, can someone confirm this is reproducible?

It kinda works for me. ~~My original setting was true and could not be renamed, but after changing it to false and then back to true, it can now be renamed.~~ After changing it to single toolbar, it can be renamed. but if I change it back to multiple, it cannot

**Comment by con-ner** [comment]
> After some digging in about:config
> 
> If `zen.view.use-single-toolbar` is set to `false` -- Folders cannot be renamed If `zen.view.use-single-toolbar` is set to `true` -- Folders can now be renamed
> 
> Hope this helps, can someone confirm this is reproducible?

This is reproducible and fixed my issue completely. 

Seems like the folders are still a bit buggy. I was able to rename but it didn't stick the first time. After another try, it worked perfectly.

**Comment by mr-cheffy** [comment]
Should be fixed next release 👍🏽

**Comment by Oculux314** [comment]
Heads up, this still occurs on 1.18.5b. `zen.view.use-single-toolbar` is set to `true` for me.

**Comment by lloyd-pinrun** [comment]
> Heads up, this still occurs on 1.18.5b. `zen.view.use-single-toolbar` is set to `true` for me.

@Oculux314 I noticed that I was still having this issue, as well. I toggled `zen.view.use-single-toolbar` to `false`, restarted Zen, and was then able to rename folders (regardless of the value for `zen.view.use-single-toolbar`).

I can't replicate the original issue again, however 🤔

Current version: `1.21.3b (Firefox 152.0.1) (aarch64)`
