### ISSUE TITLE
Enabling "Always use private browsing mode" results in totally black UI

### ISSUE THREAD

**Issue by nrusch** [zen-browser/desktop#10231]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

After enabling "Always use private browsing mode" and restarting Zen, the UI controls are completely black with the exception of tab favicons and the current tab highlight. The controls are all still there and fully functional, but it's "Zen Browser: Hard Mode".

I've reproduced this on two different Windows 10 machines with fresh installs of Zen, with no extensions or customizations installed.

### Expected behavior

I would expect the UI to still be visible

### Actual behavior

The UI turns completely black

### Steps to reproduce

1. Install Zen and click through the "first launch" flow (no bookmarks import, no extensions, etc.)
2. In `Settings` -> `Privacy and Security`, enable `Always use private browsing mode` (see screenshot).
3. Click `Restart Zen now` in the prompt that pops up.

### Screenshots and videos

Relevant settings (prior to change):
<img width="812" height="324" alt="Image" src="https://github.com/user-attachments/assets/94323378-78cd-45a5-bcb1-234120212096" />

Before enabling "Always use private browsing mode":
<img width="1458" height="875" alt="Image" src="https://github.com/user-attachments/assets/cb7ff6cc-b554-4b1c-961f-f5bd04acb592" />

After enabling and restarting:
<img width="1458" height="875" alt="Image" src="https://github.com/user-attachments/assets/6f539bb6-a3cd-4615-8d64-8aed9fc0ae01" />

### Version

1.15.3b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Settings

### Relevant log output if applicable

```shell

```

**Comment by nrusch** [comment]
Confirmed that this is still an issue as of 1.17.12b.

**Comment by HalibutGitWiz** [comment]
I experience the same issue on Garuda Linux, with version 1.17.15b.

It's a fresh install with no add-on. UI is fine when private browsing is not forced, and completely black as shown above when it is.

@nrusch When private browsing is not forced, it's still possible top open a private window from the menu. In that case, Zen also forces a black theme, but with white characters, so it's readable and usable. Using `zen-browser --private-window` in the terminal also results in white characters on a black background.

My guess is that the switch to white characters does not happen when Zen starts in private mode because it's forced to, so what we see must be black characters on a black background.

<img width="412" height="515" alt="Image" src="https://github.com/user-attachments/assets/f165ea8e-bbe5-49ac-b41e-e3fcdb8393e8" />

**Comment by tiimonn** [comment]
i beg you reverently to fix this issue. Can confirm on version 1.17.15b (Firefox 146.0.1) (aarch64)

**Comment by mr-cheffy** [comment]
I believe this should now be fixed. Please give me a ping to reopen if thats not the case

**Comment by LeonardoGandini** [comment]
This is still an issue, if I select 'Never Remember History" the whole ui turns black impossible to navigate!
Version 1.22b (64-bit) on Win11

**Comment by tiimonn** [comment]
> I believe this should now be fixed. Please give me a ping to reopen if thats not the case

ping. same here. Still present

**Comment by LeonardoGandini** [comment]
updated to 1.22.2b, same behavior
