### ISSUE TITLE
Video controls going under the screen when in fullscreen using Zen in fullscreen mode

### ISSUE THREAD

**Issue by alexdima03** [zen-browser/desktop#10594]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

When i use Zen in fullscreen mode on my Macbook on its internal monitor, the video controls go under the screen like there is a portion of screen that it tries to fill, but it obviously doesn't exist, and makes the video controls unusable (tried on YouTube and X); this doesn't happen on an external monitor though.

### Expected behavior

The video controls should be visible on fullscreen, ready to use

### Actual behavior

The video controls go under the screen, making them unusable

### Steps to reproduce

1) Use Zen on fullscreen mode on the Macbook's internal monitor
2) Open a video
3) Put it on fullscreen)

### Screenshots and videos

<img width="1512" height="982" alt="Image" src="https://github.com/user-attachments/assets/10a3285b-bdd3-4c2b-83ee-b1aae4db76f7" /> actual behavior

<img width="1512" height="982" alt="Image" src="https://github.com/user-attachments/assets/f8bec1db-cbcd-4959-8e7b-3687dc6eb5ff" /> expected behavior

### Version

1.16.2b

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Other

### Relevant log output if applicable

```shell

```

**Comment by xibrox** [comment]
Same issue

**Comment by Perchycs** [comment]
Same here, also on Mac, I don't think it happens on my Windows installation. 

I tried launching Zen with no extensions enabled and still had the issue. Tested on Youtube and Vimeo.

**Comment by AymenAbb** [comment]
Same issue, here's my experience:

M1 Pro, MacOS. After updating around 10/3/25, when I try to full screen **any** video on any platform, it'll maximize so much that I cannot see the bottom bar. Turned off all my zen mods and extensions, no change. Tried incognito mode too.

This only happens on compact mode and with Zen in exclusive full screen. It will not happen if one of those conditions isn't met.

**Comment by AymenAbb** [comment]
Tested on a fresh install of MacOS 26 on a M1 Air (no notch), no problems. I'll keep trying to triage the devices this happens on as I can.

**Comment by xibrox** [comment]
Oh looks like that is the issue. Looks like the notch isn't taken into consideration because I have M3 Air (with notch) on MacOS 26 and the problem is there.

**Comment by AymenAbb** [comment]
Dropped my M1 Pro resolution from 1512 x 982 (default) to 1512 x 945 (gets rid of notch), and the problem is gone. This is resolution related, probably to the notch yes.

**Comment by xibrox** [comment]
Okay to get this issue:

1. U need macbook with a notch
2. Compact mode

**Comment by AymenAbb** [comment]
1. Mac with notch (default resolution)
2. Compact mode
3. Zen is in exclusive full screen

ALL must be true to get the bug. Since the bug doesn't exist on exclusive full screen with compact mode disabled, it's probably something with how Zen changes the resolution when compact mode is turned on.

**Comment by alexdima03** [comment]
problem still present in 1.17b (even tho the new youtube ui makes it less worse than before)

**Comment by LalitSinghRana** [comment]
**This issue still present.** 

I can see it on YT, Twitch, Pexels, and X(twitter). Safe to assume it's there for every video site, as it's browser issue.

---

System:
- MacBookPro (14 inch)
- Apple M4 Pro
- macOS - 26.0.1
- Zen - 1.16.4b

**Comment by LalitSinghRana** [comment]
Is anyone currently looking into this?
If not, I can pick it up, as long as there’s reviewer bandwidth.

**Comment by timonkuiters** [comment]
I made a small test page to check this bug, and it seems to occur on any full screen element (not necessarily video).

https://timonkuiters.nl/zen-fullscreen-bug.html

In compact mode on a MacBookPro (16 inch) with notch (Zen 1.17.1b), entering full screen hides the bottom right marker. Playing around with the height of the markers, it seems about 33px is hidden on the bottom, which seems to match the height of the notch.

Weirdly, the bug is not present in the same test on Codepen, but I would guess the difference is that the test there is inside an iframe. https://codepen.io/TimonK/pen/YPwLpdR

Also when the Web Developer Tools are open on the page (not in a separate window) the bug does not occur.

**Comment by AymenAbb** [comment]
> I made a small test page to check this bug, and it seems to occur on any full screen element (not necessarily video).
> 
> https://timonkuiters.nl/zen-fullscreen-bug.html
> 
> In compact mode on a MacBookPro (16 inch) with notch (Zen 1.17.1b), entering full screen hides the bottom right marker. Playing around with the height of the markers, it seems about 33px is hidden on the bottom, which seems to match the height of the notch.
> 
> Weirdly, the bug is not present in the same test on Codepen, but I would guess the difference is that the test there is inside an iframe. https://codepen.io/TimonK/pen/YPwLpdR
> 
> Also when the Web Developer Tools are open on the page (not in a separate window) the bug does not occur.

I replicated everything you mentioned on my 14" m1 pro

**Comment by Samamyo** [comment]
M3 air, I've found that when the initial browser window is not in fullscreen and moving into fullscreen via the video control the screen is mapped correctly, so that may be a temporary fix for some people

**Comment by DzmitryTarashkevich** [comment]
>     2. Compact mode

Thanks, @AymenAbb. So easy workaround may be showing top panel - choose "Sidebar and Top Toolbar" option instead of "Only sidebar". 

<img height="80" alt="Image" src="https://github.com/user-attachments/assets/23955524-3663-489c-a82d-1c20aff9cbb3" />

You may leave compact mode on but do not hide toolbar:

<img height="80" alt="Image" src="https://github.com/user-attachments/assets/c2728675-9490-4026-966a-388e5c61496a" />

**Comment by shumailow** [comment]
Is there any way to fix this without waiting for the official release?
For example, I managed to shift it upward, but then the title doesn’t fit:

`:root[inDOMFullscreen="true"] #tabbrowser-tabpanels {
  margin-top: -38px !important;
}`

**Comment by NOX2912** [comment]
Here's a possible small fix for this. I couldn't build the project, so I wasn't able to test whether it works. Could someone please try it?

Cause: updateElementSeparation() sets --zen-element-separation to 0 whenever [inFullscreen] is present. DOM fullscreen also sets this, so compact borderless offsets stay active during video fullscreen.

Idea: only zero padding for window fullscreen, not DOM fullscreen.

Patch:
```code
diff --git a/src/zen/common/zenThemeModifier.js b/src/zen/common/zenThemeModifier.js
@@
   updateElementSeparation() {
     const kMinElementSeparation = 0.1; // in px
     let separation = this.elementSeparation;
+    const inWindowFullscreen = document.documentElement.hasAttribute('inFullscreen');
+    const inDOMFullscreen =
+      document.documentElement.getAttribute('inDOMFullscreen') === 'true';
     if (
-      document.documentElement.hasAttribute('inFullscreen') &&
+      inWindowFullscreen &&
+      !inDOMFullscreen &&
       window.gZenCompactModeManager?.preference &&
       !document.getElementById('tabbrowser-tabbox')?.hasAttribute('zen-split-view') &&
       Services.prefs.getBoolPref('zen.view.borderless-fullscreen', true)
     ) {
       separation = 0;
```

**Comment by Propheticus** [comment]
@mr-cheffy It appears that the way the 8px window padding is currently removed when having compact mode enabled and going full screen messes up the offsets and causes content to run off screen for users of a macbook with a notch.

This (also) causes videos to render their controls half out of view when they are viewed full screen.

To repro:
- Have Mac with notch
- Compact mode enabled
- (exclusive) Full screen the browser window  (windowed browser and then using the fullscreen button on the video itself does not trigger the issue)

Good test to show the issue https://github.com/zen-browser/desktop/issues/10594#issuecomment-3439690006 
Fix suggestion: https://github.com/zen-browser/desktop/issues/10594#issuecomment-3609168236

Thanks to all the contributors above for doing all the work. You're awesome.

p.s. pinging you because I think this issue has now formed a complete picture of the issue, it's cause and a possible solution. Can't repro myself since I don't own a macbook.

**Comment by AymenAbb** [comment]
> Here's a possible small fix for this. I couldn't build the project, so I wasn't able to test whether it works. Could someone please try it?
> 
> Cause: updateElementSeparation() sets --zen-element-separation to 0 whenever [inFullscreen] is present. DOM fullscreen also sets this, so compact borderless offsets stay active during video fullscreen.
> 
> Idea: only zero padding for window fullscreen, not DOM fullscreen.
> 
> Patch:
> 
> ```
> diff --git a/src/zen/common/zenThemeModifier.js b/src/zen/common/zenThemeModifier.js
> @@
>    updateElementSeparation() {
>      const kMinElementSeparation = 0.1; // in px
>      let separation = this.elementSeparation;
> +    const inWindowFullscreen = document.documentElement.hasAttribute('inFullscreen');
> +    const inDOMFullscreen =
> +      document.documentElement.getAttribute('inDOMFullscreen') === 'true';
>      if (
> -      document.documentElement.hasAttribute('inFullscreen') &&
> +      inWindowFullscreen &&
> +      !inDOMFullscreen &&
>        window.gZenCompactModeManager?.preference &&
>        !document.getElementById('tabbrowser-tabbox')?.hasAttribute('zen-split-view') &&
>        Services.prefs.getBoolPref('zen.view.borderless-fullscreen', true)
>      ) {
>        separation = 0;
> ```

Built this, no luck as it still behaves the same. Someone else should try it though too.

**Comment by mr-cheffy** [comment]
> Here's a possible small fix for this. I couldn't build the project, so I wasn't able to test whether it works. Could someone please try it?
> 
> Cause: updateElementSeparation() sets --zen-element-separation to 0 whenever [inFullscreen] is present. DOM fullscreen also sets this, so compact borderless offsets stay active during video fullscreen.
> 
> Idea: only zero padding for window fullscreen, not DOM fullscreen.
> 
> Patch:
> 
> ```
> diff --git a/src/zen/common/zenThemeModifier.js b/src/zen/common/zenThemeModifier.js
> @@
>    updateElementSeparation() {
>      const kMinElementSeparation = 0.1; // in px
>      let separation = this.elementSeparation;
> +    const inWindowFullscreen = document.documentElement.hasAttribute('inFullscreen');
> +    const inDOMFullscreen =
> +      document.documentElement.getAttribute('inDOMFullscreen') === 'true';
>      if (
> -      document.documentElement.hasAttribute('inFullscreen') &&
> +      inWindowFullscreen &&
> +      !inDOMFullscreen &&
>        window.gZenCompactModeManager?.preference &&
>        !document.getElementById('tabbrowser-tabbox')?.hasAttribute('zen-split-view') &&
>        Services.prefs.getBoolPref('zen.view.borderless-fullscreen', true)
>      ) {
>        separation = 0;
> ```

Shuoldn't make a difference since all toolbars are hidden anyways on DOM fullscreen

**Comment by fujingzhai** [comment]
Haven't solved it yet？ Amazing

**Comment by shumailow** [comment]
> Haven't solved it yet？ Amazing

No 😭

**Comment by mr-cheffy** [comment]
@Propheticus is there no way to consistently reproduce this? Might it be due to mods or css?

**Comment by Propheticus** [comment]
> [@Propheticus](https://github.com/Propheticus) is there no way to consistently reproduce this? Might it be due to mods or css?

Like in the previous comment the prereqs:

- Have Mac with notch
- Compact mode enabled
- (exclusive) Full screen the browser window (windowed browser and then using the fullscreen button on the video itself does not trigger the issue)

Or to quote from one of the several dupes: "The issue kicks in only when youtube video is played in full screen **on a full screen zen application.**"

**Comment by mr-cheffy** [comment]
Ok, I can reproduce now

**Comment by mr-cheffy** [comment]
Seems like we need to do one more re-paint when entering DOM fullscreen as compact mode seems to disable while entering fullscreen

**Comment by fujingzhai** [comment]
It's not just YouTube, the same situation applies to Bilibili in China.

**Comment by mr-cheffy** [comment]
Its applied to all sites, as I said before, its an issue when repainting while performing the native fullscreen animation

**Comment by eugenius03** [comment]
Found a temporary fix for this issue that works for me and my friend. In `config:about` Set `zen.view.borderless-fullscreen` to `false`. Hopefully this will help

<img width="1494" height="411" alt="Image" src="https://github.com/user-attachments/assets/646ea910-9c9f-445d-b0a5-eafce793d65b" />

**Comment by faizan-mohiuddin** [comment]
@eugenius03 Thanks for your suggestion, it _does work_ as the buttons are in the expected position but it seems to introduce a permanent border around the window, even when in compact mode. This border also persists also when viewing, for example, a YouTube video in full screen mode.

Are there other temporary fixes while we wait for an official fix?

**Comment by serge-the-hedge** [comment]
Same here. Frustrating stuff

**Comment by xibrox** [comment]
still happens to me in latest version

**Comment by Propheticus** [comment]
@xibrox Can you be more specific what version you have? Sometimes when people say 'latest' it turns out they were actually not running the most recent version (due to updater issues or whatever)

A fix for this was released in v1.19.10b  and we're now at 1.19.11b

**Comment by xibrox** [comment]
> @xibrox Can you be more specific what version you have? Sometimes when people say 'latest' it turns out they were actually not running the most recent version (due to updater issues or whatever)
> 
> A fix for this was released in v1.19.10b  and we're now at 1.19.11b

I am on v1.19.11b

**Comment by xibrox** [comment]
I can share everything you need (idk what I can provide) just ask

**Comment by mr-cheffy** [comment]
What OS are you in? @xibrox could you please show a video on how you are going fullscreen and could you please try in troubleshooting mode? about:support

**Comment by NHClaessens** [comment]
Hey All, I am also still experiencing this issue, `about:support` reports the following
Zen Version: 1.19.11b
OS Version: Darwin 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:29 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6000 (a.k.a. macOS Sequoia 15.6)
Device: 2021 14 inch Macbook Pro

When running Zen in windowed mode (but maximised) it all works as expected
However, when I run Zen itself in fullscreen mode and _then_ open something else (i.e. YT) in fullscreen mode, the video controls go under the screen

See the video demo (taken in troubleshooting mode): [Google Drive link](https://drive.google.com/file/d/1UyzzFviSfqOG2YLAHgC2B_3KFpTMZ77l/view?usp=sharing)

If there's any other information you need, I'd be glad to help

**Comment by mr-cheffy** [comment]
https://github.com/user-attachments/assets/927d8312-dc36-4f0a-9f6e-34251d09e826

Weird, seems to be fixed on twilight for me. There's a chance this fix simply didn't land on stable yet.

**Comment by NHClaessens** [comment]
That's peculiar, I did see this bug noted as being fixed in the patch notes

Nevertheless, let's hope that it simply hasn't landed yet and a future update will fix this

Thank you for your work :)

**Comment by mr-cheffy** [comment]
Might have been a mistake from my side, https://github.com/zen-browser/desktop/compare/dev...stable it does not show here at the time of writing this

**Comment by jamjam2103** [comment]
seem to be still having the issue on twilight
26.4.1 Tahoe
Build ID 20260504101522

**Comment by mr-cheffy** [comment]
@jamjam2103 could you please show a video?

**Comment by jamjam2103** [comment]
> [@jamjam2103](https://github.com/jamjam2103) could you please show a video?

[GDrive Link](https://drive.google.com/file/d/1Flg-hw65zKrK-TfcPDZgZBZBCy2kJvJ_/view?usp=sharing)

**Comment by nikeshsitaula** [comment]
Started occurring again in v1.19.13b on macOS Tahoe 26.5. It was fine on the previous version.

**Comment by mr-cheffy** [comment]
> It was fine on the previous version

May I ask what your previous version was?

**Comment by Azazel-h** [comment]
Using 1.19.13b with MacOS Tahoe 26.3 (25D125) - still having the same issue with fullscreen

**Comment by mr-cheffy** [comment]
Please try in troubleshooting mode if it still happens. I can't reproduce it anymore

**Comment by alexdima03** [comment]
yep, can confirm that it still happens even in troubleshooting mode in the latest update (it was fine before tho)

**Comment by andreastande** [comment]
@mr-cheffy I found that if you set `zen.theme.content-element-separation` to `0` in `v1.19.13b`, the issue occurs. However, the default value `8` works fine!

So perhaps it is likely that those who are still experiencing this issue are using that config trick to remove the borders?

https://github.com/user-attachments/assets/9df45da4-9774-4f87-bd7c-39cbef36e3b8

**Comment by NHClaessens** [comment]
For what it's worth, I am using that same config trick to remove borders as well

**Comment by mr-cheffy** [comment]
Certainly a hacky fix, but what i've tried was to add 0.1 pixels to the right of the browser and removing it on the next paint so that we trigger a resize. Since its a very small pixel size, you shouldn't notice any flickering.

https://github.com/zen-browser/desktop/pull/13769

**Comment by MeleMannen** [comment]
I still have this issue after updating to the latest version: 1.20b. 

Edit:
If I reset zen.theme.content-element-separation in about:config, the issue is gone. But I don’t really want to do that.

**Comment by AymenAbb** [comment]
I can confirm this issue has been re-introduced. Setting my zen.theme.content-element-separation to 8 makes no difference.

**Comment by mr-cheffy** [comment]
Maybe we shouldn't use env(hairline) then as it might be an amount too small to trigger a resize on some devices, lets fall back to 0.5px.

**Comment by NHClaessens** [comment]
I'd be more than happy to test it on my Macbook if you could point me to the appropriate build instructions and the location to change said amount

**Comment by andreastande** [comment]
I'm sorry, but the issue still persists in v1.20.1b 😞

Let me know if you need a person to help verify if a build fixed the issue or not.

**Comment by NHClaessens** [comment]
As mentioned in the PR, the changes seem to resolve the issue (on my machine at least, famous last words)
Tested with both fullscreen and non-fullscreen and with and without border removed through `zen.theme.content-element-separation`

**Comment by mr-cheffy** [comment]
https://github.com/zen-browser/desktop/pull/13959 should fix it, with element-separation = 0

**Comment by LeventCelik** [comment]
1.20.1b, the issue persists here with element-separation = 0. However, it is fixed with element-separation > 1.
