### ISSUE TITLE
Cannot set hotkey for "Stop Loading" (Browser:Stop).

### ISSUE THREAD

**Issue by TheFaux** [zen-browser/desktop#10677]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

I noticed the Escape key doesn't make a page stop loading. In the shortcuts menu, the Browser:Stop (I don't see a "Stop Loading" item) is blank.
It cannot be set to the Escape key because that key is used to save a shortcut, trying to set a different shortcut works but gets wiped when the browser restarts (other shortcuts don't behave that way).

zen-browser-bin 1.16.2b-1 from AUR

### Expected behavior

Hotkey assigned to the Stop Loading shortcut

### Actual behavior

Hotkey unable to be assigned or forgotten after browser restart.

### Steps to reproduce

1. Open Zen
2. Go to about:preferences
3. Got to Keyboard Shortcuts
4. Scroll to Others
5. Locate Browser:Stop
6. Try to set shortcut
7. Restart Browser

### Version

1.16.2b

### What platform are you seeing the problem on?

Linux (Tarball)

### What component is this issue related to?

Keyboard Shortcuts

### Relevant log output if applicable

```shell

```

**Comment by mr-cheffy** [comment]
Should be fixed next update 👍🏽

**Comment by rodrigost23** [comment]
I'm on 1.17.5b and still have this issue. I only see "Browser:Stop" and even after resetting the shortcuts, it gets unset. I cannot set it as simply the Escape key, because Escape is the "confirm shortcut" action. I can set to <kbd>Ctrl</kbd> + <kbd>Esc</kbd>, but that's inconvenient.

Edit: Workaround: Edit `zen-keyboard-shortcuts.json` and set all modifiers to `false` to be able to get only <kbd>Esc</kbd>.

**Comment by TheFaux** [comment]
Same as @rodrigost23 , except in the `about:preferences` UI it still shows up as "Not Set"

**Comment by TheFaux** [comment]
Should this issue be reopened, or a new issue?
