### ISSUE TITLE
Extensions that take over/replace passkeys does not work

### ISSUE THREAD

**Issue by LEveLiQ** [zen-browser/desktop#11161]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

I've tried multiple extensions, such as 1Password and Bitwarden, but I cannot use either of them to either create or use any passkeys saved in the password managers themselves. When I try using them on Firefox, it works as intended, which saves the passkeys to/uses from the password manager (I had to install Firefox for this.). When I try it on Zen, it defaults to the Windows Hello passkey feature. 

### Expected behavior

Passkeys from the password manager extensions work

### Actual behavior

The extension does not take over the Windows built-in passkey feature (I do not know how better to word this out)

### Steps to reproduce

Prerequisite: get a password manager that supports passkey save (I tried 1Password and Bitwarden as mentioned above, but I expect others like LastPass to behave the same)
1. Go to a website that supports passkeys, try adding one (or use an existing one if you already have some in your password manager)
2. Windows Hello will pop up instead of actually using the extension

### Screenshots and videos

I was too lazy to change the language, my bad

<img width="2530" height="1401" alt="Image" src="https://github.com/user-attachments/assets/adf5cc80-ab4c-49da-b427-3eaaf8e07abe" />
Screenshot from Zen where the Windows Hello popup shows and asks for a security key because there is no matching passkey for the website

<img width="1916" height="1211" alt="Image" src="https://github.com/user-attachments/assets/7d8358f0-0358-4e7b-aa28-9c5e94f9e252" />
Screenshot from Firefox where the Bitwarden password manager works just fine

### Version

1.17.4b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Extensions

### Relevant log output if applicable

```shell

```

**Comment by JackDunnCodes** [comment]
Just as FYI, not seeing this in Zen 1.17.5b with KeePassXC extension with most sites - in particular Google works fine. I have had this happen with Toggl but just put it down to an issue with Toggl.

**Comment by LEveLiQ** [comment]
> Just as FYI, not seeing this in Zen 1.17.5b with KeePassXC extension with most sites - in particular Google works fine. I have had this happen with Toggl but just put it down to an issue with Toggl.

I just verified KeePassXC works totally fine with Zen, but the "majority" of the password managers, from what I assume, does not properly work with passkeys. I think we can agree on this since you also did mention that Toggl did not work either.

**Comment by dynpatch** [comment]
Can reproduce using `Bitwarden Version: 2025.10.0` and `Zen Twilight 1.16t (Firefox 143.0.3) (2025-10-01) (64-bit)`

**Comment by sh3rlock14** [comment]
It looks like Zen Browser has some issues dealing with Pass Keys whatsoever: in my case - no extensions installed - I couldn't access with my tablet using the Authenticator QR code, as I did with Edge, since it default to USB.
<img width="1080" height="720" alt="Image" src="https://github.com/user-attachments/assets/3f44c32e-0389-42cd-9a9a-c4f5400572e3" />

Also, to login to Github I encountered a similar issue: I was asked to use MFA, I asked for the passkey and I could'nt get any further from the pop-up you see: I had to insert the passcode from the Auth. App.



<img width="720" height="540" alt="Image" src="https://github.com/user-attachments/assets/60d0efba-6c65-4123-b39f-0382f49cd27c" />

**Comment by Lonsofore** [comment]
Can reproduce, passkey doesn't work (tested on Github, Google):
Zen: 1.17.8b (Firefox 145.0.1) (aarch64)
Bitwarden extension: 2025.11.0

**Comment by mateusztylec** [comment]
<img width="1113" height="713" alt="Image" src="https://github.com/user-attachments/assets/b59f32a9-2068-41b3-b0d2-a4c2f479b8d8" />

I have same issue.
Couple of days ago it was working fine.

Now it prompts me to use physical key and completely skips passkeys stored in password manager. In my case bitwarden.
Platform: MacOS
Zen: 1.17.10b
Bitwarden: 2025.11.1

**Comment by a15355447898a** [comment]
Same question. Any progress?

<img width="2551" height="872" alt="Image" src="https://github.com/user-attachments/assets/337a04ec-9b64-472d-a191-6843d8107048" />

I can't respond to passkey requests using the Bitwarden extension


Platform: MacOS and ArchLinux
Zen: 1.17.10b
Bitwarden: 2025.11.1

**Comment by giopera** [comment]
I can confirm:
Platform: Arch Linux + KDE
Zen: 1.17.7b (Firefox 145.0) (64-bit)
Bitwarden: 2025.11.1

**Comment by braccae** [comment]
Affects Fedora 42 & 43, and EL 9 & 10 as well. This is the final straw for us for zen, its too unstable. Trying to roll back the flatpak past 1.17.8b results in a 404

**Comment by vk2r** [comment]
The same thing happened to me. I can't log in with my biometric data using PocketID with Bitwarden.

I checked the latest version of Firefox and it works fine.

**Comment by paralin** [comment]
Happening to me too. Passkeys used to go to Bitwarden but now it's going to the MacOS passkey.

**Comment by SentientMuffin** [comment]
Same issue, was working fine couple days ago.
platform: macOS Sequoia 15.6.1
Zen: 1.17.10b (Firefox 145.0.2) (aarch64)
Password manager: Bitwarden (firefox extension) 2025.11.1

Prompt to use passkey shows MacOS passkey instead of a small window popup showing available Bitwarden passkeys.

Current behavior with Zen and Bitwarden extension
<img width="621" height="588" alt="Image" src="https://github.com/user-attachments/assets/a3330f77-e31f-480d-8e86-51bc752585d3" />

Expected behavior (demonstrated with Vivaldi and Bitwarden extension)

<img width="620" height="488" alt="Image" src="https://github.com/user-attachments/assets/703c1387-e0b7-4452-9751-76fa14472ad3" />

**Comment by Lumisilk** [comment]
Same here — I have exactly the same environment as ↑SentientMuffin.

Off topic, I’ve encountered two other issues:
1. Every time I log in to a website using Bitwarden, it pops up a prompt asking me to update the login info. This usually only happens when I actually change the login details on the website. This issue also occurs on Chrome so it's irrelevant to Firefox or Zen
2. I just found out that somehow I lost a passkey for one of my sites — possibly because I clicked “Update” by mistake when issue 1 occurred.

**Comment by mymmrac** [comment]
The same using Zen 1.17.10b and Bitwarden 2025.11.1 on Arch Linux, works perfectly in Firefox and Chromium

**Comment by attanix** [comment]
Confirmed, have the same issue on Fedora 43, Zen 1.17.10b, and BitWaeden 2025.11.1. Chromium doesn't have this issue with Bitwarden.

**Comment by EmKaCe** [comment]
Passkeys didn't work for me with 1.17.10b and Bitwarden 2025.11.1
However downgrading the Bitwarden extension to 2025.11.0 did work for me.

System running on Fedora 43, KDE Plasma 6.5.3, Wayland.

Might make sense to also look into https://github.com/bitwarden/clients/issues/17598

**Comment by DDiegoLopez** [comment]
Same issue with v1.17.11b and bitwarden 2025.11.1.
I’m on Fedora 43 KDE

**Comment by orknist** [comment]
### Temporary Workaround (Confirmed Working)

Passkeys stopped working for me on Zen Browser after the Bitwarden extension updated to **2025.11.1**.  
Rolling back to **Bitwarden 2025.11.0** immediately restored passkey functionality.

Since Firefox/Zen does not allow permanently installing unsigned extensions, here is the temporary workaround:

1. Download the **Bitwarden 2025.11.0** browser extension ZIP from the GitHub Releases page.
2. Extract the ZIP.
3. Open: `about:debugging#/runtime/this-firefox`
4. Click **“Load Temporary Add-on”**.
5. Select the `manifest.json` file inside the extracted 2025.11.0 folder.

After doing this, **passkey authentication works again**.

Note:  
This is only a temporary fix (it disappears after restarting the browser), but it confirms that the regression is introduced in **2025.11.1**.

Related issue: `bitwarden/clients#17598`

**Comment by freudFlintstone** [comment]
> ### Temporary Workaround (Confirmed Working)
> 
> Passkeys stopped working for me on Zen Browser after the Bitwarden extension updated to **2025.11.1**. Rolling back to **Bitwarden 2025.11.0** immediately restored passkey functionality.
> 
> Since Firefox/Zen does not allow permanently installing unsigned extensions, here is the temporary workaround:
> 
>     1. Download the **Bitwarden 2025.11.0** browser extension ZIP from the GitHub Releases page.
> 
>     2. Extract the ZIP.
> 
>     3. Open: `about:debugging#/runtime/this-firefox`
> 
>     4. Click **“Load Temporary Add-on”**.
> 
>     5. Select the `manifest.json` file inside the extracted 2025.11.0 folder.
> 
> 
> After doing this, **passkey authentication works again**.
> 
> Note: This is only a temporary fix (it disappears after restarting the browser), but it confirms that the regression is introduced in **2025.11.1**.
> 
> Related issue: `bitwarden/clients#17598`

bitwarden 2025.11.0 confirmed to work simply by removing current version and downloading previous from [firefox extensions page](https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/). You can go to the extensions manager in settings and disable automatic updates for this extension, so the fix persists across restarts.

**Comment by ghost** [comment]
I've encounter this issue on Windows 10 with both Bitwarden version: 2025.11.1 and Proton Pass version: 1.33.0.

EDIT: I did further testing I encounter this same issue with Firefox (version 145.0.2).

**Comment by davidbelius** [comment]
I'm also facing this issue.

**Comment by schembriaiden** [comment]
https://community.bitwarden.com/t/firefox-bw-extension-2025-11-1-not-prompting-for-passkeys-on-any-site/91252/51

**Comment by schembriaiden** [comment]
This has been fixed with Bitwarden Extension Version 2025.11.2

**Comment by julienvincent** [comment]
This issue is still relevant in the latest version of Zen. I use 1Password, not Bitwarden, and it is still unable to handle the passkey flow.

**Comment by mr-cheffy** [comment]
Does this happen in Firefox as well?

**Comment by paralin** [comment]
It did but the issue is fixed now, at least for Firefox/chrome and bitwarden. Not sure about other password managers. I know bitwarden deployed a fix for this.

**Comment by l4kr** [comment]
1password here. I can get it to work on most sites it seems but discord doesn't work

**Comment by leticiv** [comment]
Still unable to handle the passkey flow.

<img width="1264" height="608" alt="Image" src="https://github.com/user-attachments/assets/b1cc426b-9fdc-46d4-b191-59a913374b31" />

Im using the Bitwarden extension.

Platform: LinuxMint
Zen: 1.19.8b (Firefox 149.0.2) via Flatpak
Bitwarden: 2026.3.0

**Comment by btorresgil** [comment]
@mr-cheffy I see this was moved to `More info needed`. Happy to provide any info, just let us know what you need. Would love to help out in any way I can. Thanks for the attention to this!

**Comment by Telandriq** [comment]
Still experiencing this issue, with 1password, as I saw mention of the microsoft admin center unable to login to any as I have passkeys setup, and it just loops till it fails.

**Comment by kevingangi** [comment]
This is still an issue.
OS: Mac 26.5.1
Zen: 1.21.3b
Firefox: 152.0.1
Bitwarden: 2026.5.1

**Comment by fred-drake** [comment]
I was having this exact issue, but it turns out that for some reason my domain was showing up as an excluded domain.  After I removed it, the bitwarden passkey popped up as expected.  For anybody who sees this, you may want to check this first.  I am using the latest Bitwarden plugin and Zen browser at the time of this writing.

<img width="484" height="353" alt="Image" src="https://github.com/user-attachments/assets/44da34d9-5cb5-4522-8352-30b72f557ccc" />

**Comment by levitabris** [comment]
<img width="1415" height="951" alt="Image" src="https://github.com/user-attachments/assets/f6236bb2-adcb-40aa-9866-7898fa877183" />

My passkey login hangs here. I'm running `1.21.15b (Firefox 154.0) (aarch64)` on macOS 26.2.

I tried with vanilla Firefox and the login is very successful. I tried disabling all Zen extensions and the problem persists. 

I use Enpass Deskop with the official extension.

I suppose it is not a Windows only issue. And it is still relevant on Aug. 2026.

**Comment by Sadzeih** [comment]
Still happening with Bitwarden as well, in all platforms. Windows, macOS and Linux.

What can we do to help y'all fix this issue?

**Comment by whitererr** [comment]
1.21.15b still gives the issue.
Works with Bitwarden but not with Proton Pass.
Using CachyOS + Sway.

<img width="464" height="137" alt="Image" src="https://github.com/user-attachments/assets/7ceee9f4-800e-4217-84d7-f1cdd03299b3" />

**Comment by phi3nix** [comment]
The same issue on 1.22.2b. I checked Firefox too. I can reproduce this issue on Firefox and Zen. I will contact Bitwarden support.
