### ISSUE TITLE
Cant install on linux (AUR)

### ISSUE THREAD

**Issue by Ghostblackout** [zen-browser/desktop#11306]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

yay and on the website can download zen "https://github.com/zen-browser/desktop/releases/download" dose not dose not exist this is the same if I use "yay -S zen-browser" I can still install zen if I go to the github and get the tar my self I think this is easy fix. 

This is my first real Bug Report and the only time I will use github plz be nice

 yay -S zen-browser-bin
AUR Explicit (1): zen-browser-bin-1.17.7b-1
:: PKGBUILD up to date, skipping download: zen-browser-bin
  1 zen-browser-bin                  (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
  1 zen-browser-bin                  (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
==> Making package: zen-browser-bin 1.17.7b-1 (Sun 16 Nov 2025 12:14:52 AM EST)
==> Retrieving sources...
  -> Found zen-browser.sh
  -> Found zen.desktop
  -> Found policies.json
  -> Downloading zen-browser-1.17.7b-1-x86_64.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0   0     0   0     0     0     0  --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/zen-browser/desktop/releases/download/1.17.7b/zen.linux-x86_64.tar.xz
    Aborting...
 -> error downloading sources: /home/ghost/.cache/yay/zen-browser-bin
	 context: exit status 1

### Expected behavior

To download zen

### Actual behavior

Not downloading zen

### Steps to reproduce

yay -S zen-browser or yay -S zen-browser or got to website and then download for Linux

### Version

1.17.7.b

### What platform are you seeing the problem on?

Linux (Tarball)

### What component is this issue related to?

Other

### Relevant log output if applicable

```shell

```

**Comment by teknxs** [comment]
It appears the latest Zen release was removed, as the newest build shown is 1.17.6b. Attempting to download from the official website also results in a 404 error.

**Comment by mr-cheffy** [comment]
This should be fixed automatically shortly

**Comment by m-perfect** [comment]
This has not yet been resolved as of 0928 PST, 16 Nov 2025.

**Comment by Shreesh-o** [comment]
<img width="1351" height="977" alt="Image" src="https://github.com/user-attachments/assets/1554b355-5916-4f5c-b57b-590dd2fbf7d4" />

Issue still not fixed!

**Comment by Ghostblackout** [comment]
yeah I can say that it is still not fixed I tested it dose the same thing. The website is fixed not the aur zen

**Comment by Victor-Void** [comment]
The AUR is down at the moment, might be the cause

https://status.archlinux.org/

**Comment by mr-cheffy** [comment]
Try running the following

```
rm -rf ~/.cache/yay/zen-browser-bin
yay
```

**Comment by Ghostblackout** [comment]
I can say it works now fixed yippe
