### ISSUE TITLE
Opening a glance in split view also opens the link in a new window when using "Shift" as modifier

### ISSUE THREAD

**Issue by Rosalina121** [zen-browser/desktop#11409]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

When opening a glance from a link in a tab in split view, the glance pops-up, but also a new window is created with the same link open. Unable to reproduce this on a single tab (not-split), or when the glance modifier is set to "Alt" or "Ctrl".
On 1 hand, I'd assume some conflict with the default Firefox action, but it's odd it only happens in split-view.

If relevant, OS is Arch Linux with KDE Plasma 6.5.3

### Expected behavior

A glance is opened when Shift-clicking on a link in a tab split view

### Actual behavior

A glance and a separate window is opened when Shift-clicking on a link in a tab split view

### Steps to reproduce

1. Open 2 separate tabs
2. Join them in split view
3. Shift-click on a link in either tab

The glance and a new window will pop-up

### Screenshots and videos

Shift-click (actual):
https://github.com/user-attachments/assets/74212217-f6f2-4d05-ae29-d1952c816b0c

Alt-click (expected):
https://github.com/user-attachments/assets/c7d5f987-29e9-4af2-a575-64f65330011b

### Version

1.17.8b

### What platform are you seeing the problem on?

Other, Linux (Tarball)

### What component is this issue related to?

Glance

### Relevant log output if applicable

```shell

```

**Comment by mr-cheffy** [comment]
Was this happening on previous versions?

**Comment by Rosalina121** [comment]
Hi. No, this has started with the 1.17.8b.

**Comment by TenBryBry2003** [comment]
I am having this issue as well with all tabs – not just tabs open in split view.

I am on 1.17.9b

**Comment by TenBryBry2003** [comment]
sometimes a new window is opened with the link along with glance

using the context menu and choosing "open link in glance" does not cause this problem

**Comment by angrybacon** [comment]
Fixed on Linux for me, but I can reproduce on macOS. The difference now is that links found in https://zen-browser.app/release-notes/#1.17.10b open Glance properly but any other links (Duck Duck Go search results for instance) still open a new window

**Comment by TenBryBry2003** [comment]
Yes, I still encounter the issue. It seems to happen when I open a glance for one link, close it, and then open a glance for a link that isn't "highlighted/selected“. Not sure what the proper term is.

**Comment by TenBryBry2003** [comment]
Actually I'm not sure but I can say that it happens when the cursor doesn't appear as a hand and you click a link.
