### ISSUE TITLE
Every time browser get updated, permission for share screen is not recognized

### ISSUE THREAD

**Issue by JosephSanjaya** [zen-browser/desktop#1157]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Every time the Zen Browser is updated, the screen sharing permission is not recognized by the browser. Even though the permission is already granted and checked in the system settings, the browser fails to acknowledge it.

Steps to Reproduce:
1.  Update Zen Browser to the latest version on macOS Sequoia.
2. Attempt to share your screen.

Expected Behavior: The browser should recognize the existing screen sharing permission and allow screen sharing without any additional steps.

Actual Behavior: The browser does not recognize the screen sharing permission. To resolve this, I need to:

1. Remove the screen sharing permission in the system settings.
2. Restart Zen Browser twice.
3. Re-request the screen sharing permission.

This issue disrupts workflow and requires multiple steps to re-enable screen sharing after each browser update. A fix or workaround would be highly beneficial.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a33

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by mauro-balades** [comment]
Does it happen with firefox as well?

**Comment by JosephSanjaya** [comment]
No in firefox is working fine

**Comment by mauro-balades** [comment]
This should be fixed for the next release, as I started signing the application

**Comment by thornjad** [comment]
This is still happening to me with v1.0.0-a.35, even with an entirely fresh install

**Comment by JosephSanjaya** [comment]
The issue persists in version v1.0.0-a.37. Could you please provide an update on the timeline for releasing the signed application?

**Comment by edmarshallio** [comment]
This is still happening for me. I can't share regardless of how many times i check and uncheck it in settings. It means I have to swap browsers when taking calls, not ideal!

**Comment by barqus** [comment]
hi @edmarshallio, I had the same issue, had to install firefox, enable screen sharing of firefox and zen in macos settings and it started working, hope it helps!

**Comment by fixiee** [comment]
I still have the same problem, so i guess it is still not fixed and it is quite annoying.

**Comment by edmundml** [comment]
Yep I'm still getting the same problem - wish this would be fixed

**Comment by soundstep** [comment]
Same here, that is a deal breaker.

Note that it is the screen sharing that is not working, sharing a window works.

```
1.7.6b (Firefox 135.0) (aarch64)
Max OS Sonoma 14.7.1 (23H222)
Macbook pro laptop, no second monitor.
```

Tried several OS Setting screen share updates (on and off, etc), browser restart, etc...

<img width="827" alt="Image" src="https://github.com/user-attachments/assets/82fbbafb-43fa-4320-8e92-e16ad4ad77df" />

![Image](https://github.com/user-attachments/assets/830e3aa9-af1b-4dbc-a361-20fb4efdae3c)

<img width="508" alt="Image" src="https://github.com/user-attachments/assets/a09ec4ac-27d4-4a74-8500-6d8be7a5375d" />

**Comment by rahulbarwal** [comment]
For me, screen sharing is not working at all. 

I have given the required permission:
![Image](https://github.com/user-attachments/assets/1eb8e073-b893-41fc-9fd0-0331c6288913)

On Google Meet, I get this: 
![Image](https://github.com/user-attachments/assets/3d9bd9af-1552-4918-bd87-ebe4ea7bedb5)

And on Slack huddles, the screen-sharing button does nothing.

**Comment by Sabreclaw** [comment]
Screensharing is not working for me as well

![Image](https://github.com/user-attachments/assets/1d7bcc35-65e5-4abc-8f22-f02ef05bf8e7)

![Image](https://github.com/user-attachments/assets/c8a4ea5c-fe0e-43ce-9e94-a77cdde4276e)

**Comment by joelazar** [comment]
I was able to fix it by completely removing the Zen Browser from the MacOS Screen & System Audio Recording list and then adding it back again.

**Comment by Sabreclaw** [comment]
> I was able to fix it by completely removing the Zen Browser from the MacOS Screen & System Audio Recording list and then adding it back again.

Verified the workaround by @joelazar , it worked for me as well.
