### ISSUE TITLE
Profile locks are being ignored, causing weird synced behavior

### ISSUE THREAD

**Issue by Test-Account666** [zen-browser/desktop#11750]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

Opening a second instance of Zen (through desktop files or executing `zen` in a CLI) causes the instances to be synced.

Not only is this extremely confusing, but also destructive.
Closing the latest instance and then the oldest will result in all tabs being lost.

I have read in the changelogs:
```
Merged window syncing! Now, when you open multiple windows of Zen, they will stay in sync with each other. Changes made in one window will automatically reflect in all other open windows. (Experimental, some features such as glance still can't sync yet.)
```

Does that mean this is intentional? If so, I do not see any reason for this to ever be useful.
Especially, if you have muscle memory to open a second instance or forgot about your previous one.

If this is actually intended AND here to stay, at least make it optional, please.

### Expected behavior

Opening a new instance should create a completely separate window

### Actual behavior

Opening a second instance creates a window that is fully in-sync with the previous instance

### Steps to reproduce

1. Open Zen
2. Open a few tabs
3. Open a second instance of Zen

### Version

1.18t

### What platform are you seeing the problem on?

Linux (Tarball), Other

### What component is this issue related to?

Other

### Relevant log output if applicable

```shell

```

**Comment by Fxxxlei** [comment]
The syncing behavior is intended and was one of the most requested features recently so a fair share of users have a use for it, myself included, but I do understand this may break habits and use cases.

> Closing the latest instance and then the oldest will result in all tabs being lost.

If you mean that tabs disappeared, when you closed windows (not the tabs in the windows), I had that happen once, but can't reproduce it. That is probably a bug.

The lost tabs might have been the tabs opened after the initial install of Twilight Zen, these weren't properly synced in the first place (Pinned and essentials were properly synced from the start).

**Comment by Fxxxlei** [comment]
By creating a new profile, I was able to reproduce the bug.

On a new profile, the initial normal tabs don't seem to be synced beyond copying the initial state when creating a new window.
As long as there are improperly synced tabs, tabs may disappear.

At some point I stopped getting improperly synced tabs and I stopped losing tabs when closing windows.

**Comment by Test-Account666** [comment]
Are there any plans on making this an optional feature?

Also, could you explain one use case to me? (This is just general interest as I'm trying to understand this feature properly) 

Since I personally cannot understand how it would be useful to have synced workspaces on local deviceses.

Especially since I haven't found any keyboard shortcuts to quickly move tabs between workspaces.

And pressing the Back/Forward button on my mouse sometimes switches between workspaces instead of going back/forward on the tab's history, making productive work with workspaces kind-of annoying

**Comment by Fxxxlei** [comment]
> Are there any plans on making this an optional feature?
That would be a question for the devs.

> Also, could you explain one use case to me? (This is just general interest as I'm trying to understand this feature properly)

My use cases generally involve either:
- not caring and not remembering in which window a tab is but knowing the associated space (I associate windows with a position on my screens and spaces with a theme or project),
- wanting to temporarily work on a tab from a different window often,
- or needing access to the same instance of a tab in every window.

Specific story: I need Element Chat quite often, so I pinned it, but now it's visible in every window. Element only allows a single tab to work, so I have to find the correct window to actually use the tab. Syncing the tab between windows solves this issue.
 
> Especially since I haven't found any keyboard shortcuts to quickly move tabs between workspaces.

More people may request this when synced tabs are in use. 

> And pressing the Back/Forward button on my mouse sometimes switches between workspaces instead of going back/forward on the tab's history, making productive work with workspaces kind-of annoying

This happened to me inconsistently as well. It is only supposed to happen when the mouse is in the sidebar.

**Comment by Test-Account666** [comment]
> not caring and not remembering in which window a tab is

That's what search bars are for, usually...

> wanting to temporarily work on a tab from a different window often

What's stopping you from simply dragging the tab outside the current window? 

> or needing access to the same instance of a tab in every window.

And we circle back to the initial question?

Are you like... Dual or Tripple wielding browser windows and rapidly switch between them while working on a single task? 


> I need Element Chat quite often

Sounds to me like you should get a dedicated client or use the search bar more often...

**Comment by Test-Account666** [comment]
To clear things up:
What I'm trying to say isn't that anyone's wrong, but that I personally don't understand as I have a different workflow.

It would be much appreciated, if there was an option to disable the feature(s) added in #10034 to allow both workflows to co-exist

**Comment by mr-cheffy** [comment]
>  What I'm trying to say isn't that anyone's wrong, but that I personally don't understand as I have a different workflow.

You can drag a tab outside to make an unsynced window

>  Closing the latest instance and then the oldest will result in all tabs being lost.

Could you show a video?

**Comment by Test-Account666** [comment]
> You can drag a tab outside to make an unsynced window

No, that doesn't work for me, for whatever reason. Maybe a Wayland/Plasma6 thing?

Which is why I specifically had to open a new instance to drag windows over. 


> Could you show a video?

Sure. Could've been that one-off issue that has been mentioned already tho.

(Even though it happened at least twice to me already)

**Comment by Test-Account666** [comment]
Here's a video where the workspace sync deletes tabs, however, this is not quite the same issue I had been experiencing before:

https://workupload.com/file/Lq3G4wRCkEd

**Comment by mr-cheffy** [comment]
It can be disabled in about:config by searching window-sync, but it may or may not lose all your tabs / spaces as you are telling zen to stop caring about syncing (just like firefox)

**Comment by mr-cheffy** [comment]
> Here's a video where the workspace sync deletes tabs, however, this is not quite the same issue I had been experiencing before:
> 
> [workupload.com/file/Lq3G4wRCkEd](https://workupload.com/file/Lq3G4wRCkEd)

@Propheticus can you also repro this?

Edit: I can indeed reproduce as well, I wonder why this happens...

**Comment by Test-Account666** [comment]
> It can be disabled in about:config by searching window-sync, but it may or may not lose all your tabs / spaces as you are telling zen to stop caring about syncing (just like firefox)

An accessible toggle would be nice (And shouldn't be too hard, hopefully? Like... Treat every new window besides the first as temporary)

**Comment by Test-Account666** [comment]
Btw, here's a video showing the broken tab drag behavior:

https://workupload.com/file/5FxSG4cRK4j


I'm pretty certain this isn't a Zen issue specifically - Even though other browsers seem to work (Only tested Chromium)

**Comment by Propheticus** [comment]
> > Here's a video where the workspace sync deletes tabs, however, this is not quite the same issue I had been experiencing before:
> > [workupload.com/file/Lq3G4wRCkEd](https://workupload.com/file/Lq3G4wRCkEd)
> 
> [@Propheticus](https://github.com/Propheticus) can you also repro this?
> 
> Edit: I can indeed reproduce as well, I wonder why this happens...

I can when I open the tab in window 2 first.
It gets synced to window 1, but when I close window 2 first and then 1, upon restart it's gone.
If I open the tab on window 1, it gets synced to 2. Now closing 2 and then 1 does remember the tab.

**Comment by Propheticus** [comment]
> Btw, here's a video showing the broken tab drag behavior:
> 
> https://workupload.com/file/5FxSG4cRK4j
> 
> I'm pretty certain this isn't a Zen issue specifically - Even though other browsers seem to work (Only tested Chromium)

This is a separate pre-existing Linux version issue, where dragging left does not detach the tab. Dragging (far) right might work. (It works on Windows)

https://github.com/zen-browser/desktop/issues/8418 this looks like it doesn't work at all for some.

**Comment by Test-Account666** [comment]
> > Btw, here's a video showing the broken tab drag behavior:
> > https://workupload.com/file/5FxSG4cRK4j
> > I'm pretty certain this isn't a Zen issue specifically - Even though other browsers seem to work (Only tested Chromium)
> 
> This is a separate pre-existing Linux version issue, where dragging left does not detach the tab. Dragging (far) right might work. (It works on Windows)
> 
> [#8418](https://github.com/zen-browser/desktop/issues/8418) this looks like it doesn't work at all for some.

Even moving the tab to my second monitor does not detach it

**Comment by mr-cheffy** [comment]
Does it work on firefox?

**Comment by Test-Account666** [comment]
> Does it work on firefox?

Actually, seems to work on Firefox (146.0.1).

Though, not particularly smooth

**Comment by mr-cheffy** [comment]
Every issue should be fixed now (and a new shortcut to open an unsynced window has been added as cltr+alt+N)

**Comment by Test-Account666** [comment]
Ctrl + Alt + N opens a blank window (See image)

And dragging a tab still doesn't work for me :/

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c908bfe7-697e-4712-9ea2-e6bb024d1240" />
