### ISSUE TITLE
Task Manager Icon Missing in Flatpak Version 

### ISSUE THREAD

**Issue by zabulonian** [zen-browser/desktop#146]
### What happened?

The icon displays as a generic Wayland icon in the icons-only task manager using the Flatpak version.
More specifically, when launching, two icons appear - one with the Zen logo, and one generic Wayland icon. The Zen logo one has a loading indicator on it. Once it is done, it disappears, and only the Wayland one remains.

OS: OpenSUSE Tumbleweed 
DE: KDE Plasma 6.1.3

The icon does display properly using the appimage version. Also, the icon displays properly everywhere else (application menu, etc), just not in the panel.

I found another user having this issue on Debian 12 using the zip version of the browser: https://www.reddit.com/r/zen_browser/comments/1ehhm0d/no_zen_browser_logo_shows_on_linux_debian_12/

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.8

### Severity impact

Low

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
It should be fixed now 👍🏽 

https://flathub.org/apps/io.github.zen_browser.zen

**Comment by zabulonian** [comment]
Thank you for your quick response and action!
I have updated the flatpak to version 1.0.0-a.11. Unfortunately, the issue persists.

**Comment by mauro-balades** [comment]
NOW it's fixed and confirmed by testers, let's see what happens in version .13

**Comment by zabulonian** [comment]
Bug persists in version 1.0.0-a.13.

Is there something I can do to provide additional information?

**Comment by zabulonian** [comment]
Sort of a workaround for KDE Plasma. I'll explain why "sort of" after.

With Zen browser selected, press alt+F3 and select More actions -> Special Application Settings. Then, hit Add Property and select Desktop file name. There, enter the name of the Desktop file, without the path. I am using the Flatpak, and the filename at time of writing is io.github.zen_browser.zen.desktop. Make sure "apply initially" is selected in the dropdown, and then restart the browser.

You will now see that it properly displays the icon.

Now, why this is "sort of" a workaround: It appears the Flatpak desktop file calls something else to launch. So, if you, like me, have pinned the application to your panel, you will be left with two Zen browser icons sitting there. The pinned, inactive one that simply launches the second one, and the second one, which originally had a Wayland default icon until you followed the steps above.

I have attached a picture below to give you an idea of what I mean. 

Definitely a low severity issue, but I look forward to seeing it resolved!

![image](https://github.com/user-attachments/assets/7fe96e3c-b85a-4db6-a9fa-ecbcbfefe5e6)

**Comment by PanIntegralus** [comment]
This happens in the latest version at the time I'm writing this, 1.0.0-a.19

![image](https://github.com/user-attachments/assets/88b5c077-7f3a-4b34-a5c7-b7f2476b2af0)
