### ISSUE TITLE
Sidebar and Topbar overlap each other in compact mode when one of them is pinned.

### ISSUE THREAD

**Issue by Glitchy-Sheep** [zen-browser/desktop#1503]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Topbar and Sidebar overlap each other when:

1. Compact mode is enabled
2. Topbar OR sidebar pinned with `ctrl + t` or `ctrl + s` accordingly

## For example, in non-compact mode (works great):
![image](https://github.com/user-attachments/assets/b505d061-7778-4046-8fb8-3f76ab7315b8)

## And in compact mode with topbar or sidebar pinned:
![image](https://github.com/user-attachments/assets/f760c3f4-3324-45cd-82d9-4fd422745659)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.1 (64bit)

### What platform are you seeing the problem on?

Windows

**Comment by Dean-Corso** [comment]
I have similar problem in compact mode (default run / after manually resize of expand sidebar the problem is gone) and another problem with the basic context menu on the URL bar. It's never showing the full menu with paste & go so long I go into customize toolbar and go out (ESC) again so then the right context menu pop ups. Must be some bug so please fix that. Just disable the simple context menu on URL bar.
![A1_2024-09-17_231225](https://github.com/user-attachments/assets/55eb9545-7ae2-42c8-b5fb-cd1c0c864d6b)

**Comment by dhirajksharma** [comment]
I am facing a similar issue, earlier in version 1.0.a39 the sidebar used to dynamically change height based on the window's inner height, but now it is static and overlaps the bookmark bar as seen below

![Screenshot from 2024-09-18 19-49-16](https://github.com/user-attachments/assets/adc0398d-19df-418a-bc14-0b203fdbd0be)

**Comment by mauro-balades** [comment]
This has been fixed, thanks!

**Comment by Glitchy-Sheep** [comment]
> This has been fixed, thanks!

I apologize for reaching out again, but after the latest update, I'm still experiencing the same issue (top-right corner):
It appears _only in compact_ mode with `ctrl+t` and `ctrl + s` enabled simultaneously.

![image](https://github.com/user-attachments/assets/159f3466-f4c9-4b85-9fb6-64bfbc60cc95)

**Comment by EgorBakanov** [comment]
Reproducible in 1.0.1-a.19

![zen_ElCRO3zZA4](https://github.com/user-attachments/assets/0c78024d-789f-4417-bc74-66c93c69384d)
