### ISSUE TITLE
Font Size too Small

### ISSUE THREAD

**Issue by diligentlystereotypedinvestment** [zen-browser/desktop#1544]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hi, I am using the appimage file of the Zen Browser, and the font size is too small in the browser.

Here is a picture of what I see
![image](https://github.com/user-attachments/assets/078e6993-240e-419b-a3cd-472eb648ed81)

I think it is because my screen's DPI is too high.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
After running the AppImage, I get this:

ATTENTION: default value of option mesa_glthread overridden by environment.
```

**Comment by m-p-3** [comment]
Also, the font size of the tab label appears a bit small compared to everything else.

![image](https://github.com/user-attachments/assets/a9a83273-1391-4946-ae5e-098a946cc7bd)

OS: Windows 11
Version: `1.0.1-a.2 (64-bit)`

**Comment by Megafrox** [comment]
Agreed

**Comment by Samueru-sama** [comment]
I have this on my .css

```
:root .tab-content {
    font-size: 12px !important;
    font-weight: bold !important;
    font-family: 'Nimbus Sans Narrow' !important;
}
```

![image](https://github.com/user-attachments/assets/ef2c5ee4-e433-42de-a7f5-2e8cf131e59e)

**Comment by diligentlystereotypedinvestment** [comment]
This is in your chrome.css just like that? My chrome.css doesn't seem to be organized like that bit of code you shared.

**Comment by Samueru-sama** [comment]
> This is in your chrome.css just like that? My chrome.css doesn't seem to be organized like that bit of code you shared.

iirc zen doesnt have a userChrome.css by default, since the themes instead are in a bunch of directories in the same dir where userChrome.css is.

but yes that is what I have:

![image](https://github.com/user-attachments/assets/09e25720-066b-4aef-b33a-e6eee38949ad)

Also I just added "Compact tabs title" from the zen store and changed it to display more than 3 characters, and now the tabs in compact mode look like this with the narrow font: 

![image](https://github.com/user-attachments/assets/b3d7a29e-859d-4d7a-a857-98eb89679096)

which is great because I usually just need the first few letters from the tab title and not all.

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks!

**Comment by diligentlystereotypedinvestment** [comment]
I suspect it is a bad setting because I still have this issue.

**Comment by penderuk** [comment]
@diligentlystereotypedinvestment I also have this issue.

1.0.1-a.19 (Firefox 132.0.1) (64-bit)

**Comment by diligentlystereotypedinvestment** [comment]
@penderuk I just changed layout.css.devPixelsPerPx in about:config and it seems to work well.

**Comment by prasoon2211** [comment]
I had to add `.tab-text.tab-label{ font-size: 14px; }` to my userChrome.css to fix this issue - for anyone stumbling on this thread.
