### ISSUE TITLE
Keyboard shortcuts Not working

### ISSUE THREAD

**Issue by RABINGG** [zen-browser/desktop#1577]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The default shortcut for workspace cycling is ctrl+shift+E.

Expected : Cycle Workspace
Reality: Opens developer tool window (specifically network)

Update the default shortcut as it conflicts with developer tools shortcuts. Also developer tools shortcut should work only if its opened

PS : Also noticed ctrl+shift+C opens Pick an element in inspector of developer tool window (should works only if the developer tool is already opened).

PSS: I use ctrl+shift+c in arc to copy the website url which is handy. Hoping the same get implemented in Zen also.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.2 (64-bit)

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
This has been fixed, thanks!

**Comment by sjclayton** [comment]
@mauro-balades 

This needs re-opening.

Not fixed on 1.0.1-a.3 on Linux here... If these fixes you are doing require people to create a new profile for them to take effect then maybe you should let people know, if not then obviously these fixes are not being tested before being rolled out. 😞

**Comment by mauro-balades** [comment]
> @mauro-balades 
> 
> This needs re-opening.
> 
> Not fixed on 1.0.1-a.3 on Linux here... If these fixes you are doing require people to create a new profile for them to take effect then maybe you should let people know, if not then obviously these fixes are not being tested before being rolled out. 😞 

Today I'll release a fix with new keyboard shortcuts.

**Comment by tiimonn** [comment]
is this fixed because I have the same issue on windows?

**Comment by svengt** [comment]
I have the same issue on MacOS, version 1.0.1-a.17 (Firefox 132.0) (aarch64)

**Comment by vivek-dodia** [comment]
no updates? its 2025...
