### ISSUE TITLE
Nvidia RTX video super resolution doesn't work in Zen

### ISSUE THREAD

**Issue by PushaG** [zen-browser/desktop#1849]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

gfx.webrender.overlay-vp-super-resolution is enabled but still RTX video enhancement is inactive in Zen, whereas in Firefox it works as intended.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Windows

**Comment by Robot-Inventor** [comment]
I was experiencing the same issue.

When I checked `about:support`, I found that `VIDEO_HARDWARE_OVERLAY` was `Blocklisted by gfxInfo`. In my environment, setting `gfx.webrender.dcomp-video-hw-overlay-win-force-enabled` to `true` in `about:config` allowed VSR to work properly.

**Comment by PushaG** [comment]
> I was experiencing the same issue.
> 
> When I checked `about:support`, I found that `VIDEO_HARDWARE_OVERLAY` was `Blocklisted by gfxInfo`. In my environment, setting `gfx.webrender.dcomp-video-hw-overlay-win-force-enabled` to `true` in `about:config` allowed VSR to work properly.

Hey, thank you for your suggestion. Unfortunately no matter what i do i still can't get it to work. I have both gfx.webrender.dcomp-video-hw-overlay-win-force-enabled and gfx.webrender.overlay-vp-super-resolution to true but still says inactive in NVCP.

**Comment by MfiCore** [comment]
Hello @PushaG, I m coming from my super resolution issue.  https://github.com/zen-browser/desktop/issues/2082#issue-2584257432

Unfortunately, Zen Browser (or any Mozilla-based browser) does not use this setting by default. Go to the about:prefences
section (Settings), navigate to the Performance section, and you'll see that Use recommended performance settings is checked. Uncheck the box. A new option will appear as shown in my screenshot; check that option. Restart your browser. Then, apply the procedure suggested by Robot-Inventor, and your issue should be resolved. If not, go to your graphics card settings. Check if Super Resolution is enabled. Try watching YouTube in fullscreen mode, especially with cinematic content or on multiple monitors. It should say Active. 

If it still doesn’t, install the standard Mozilla version and apply the same setting in the preferences. Try accessing YouTube again on the normal Mozilla browser. If it works there and you see Active in your graphics card settings, try completely uninstalling Zen Browser using a tool like Revo Uninstaller and reinstalling it. If Super Resolution doesn’t show as active in the original Firefox browser either, uninstall your graphics card driver completely and reinstall it.

Note: Super Resolution only works for videos with a resolution lower than your monitor’s resolution. For example, if you play a 2K video on a 2K monitor, it won’t be active. Similarly, if you play 1080p or higher on a 1080p monitor, it won’t activate. However, if you play a 480p or 1080p video on a 2K or 4K monitor, it will work.

Note 2: I am aware that on some websites, videos may appear to be 1080p but still look extremely bad. For those videos, select one resolution lower than your screen’s resolution in the player. This will activate RTX Super Resolution, and it will process the resolution.

Have a nice day.

Settings screenshot:
![firefox_jMEyJgb7IC](https://github.com/user-attachments/assets/98798cdb-8940-4a84-b343-eea0190110ba)

**Comment by glassd** [comment]
I don't know about @PushaG, but I can confirm this is still an issue. I've done both what @xxMFIxx and @Robot-Inventor suggested and it still does not activate. 

VIDEO_HARDWARE_OVERLAY is active and use hardware acceleration is enabled.

**Comment by mwinnicki1** [comment]
I have similar problem:

- gfx.webrender.overlay-vp-super-resolution - set to true
- gfx.webrender.dcomp-video-hw-overlay-win-force-enabled - set to true
- VIDEO_HARDWARE_OVERLAY displays as available

Super Resolution works ONLY when playing video in fullscreen mode - on YouTube and other platforms.
This is not the case for Firefox and Chrome where it is Active in both fullscreen and standard windowed mode all the time.

**Comment by mwinnicki1** [comment]
Seems that the problem is not existant in version 1.0.1-a.20

**Comment by glassd** [comment]
I just updated and it does appear to be working correctly in 1.0.1-a.20.

**Comment by mwinnicki1** [comment]
aaaand it stopped working again in a.22 :D (it was still working on a.21 tho)
@glassd, is it the same for you?

**Comment by glassd** [comment]
Same. They fixed the issue with the address bar and broke this again.

**Comment by glassd** [comment]
It now appears fixed in 1.0.2-b.0

**Comment by Leo9481** [comment]
Always had this issue, from the alpha till now. Had it in 1.0.2-b.0, I still have the issue in 1.0.2-b.1

- gfx.webrender.overlay-vp-super-resolution - set to true
- gfx.webrender.dcomp-video-hw-overlay-win-force-enabled - set to true
- VIDEO_HARDWARE_OVERLAY displays as available
- Use recommended performance settings unchecked
- Hardware acceleration enabled
- GPU drivers cleaned with DDU and installed latest version

For me, the VSR and HDR work the first few seconds of a video, then they just turn off.
Please, fix this issue, it's literally the only thing preventing me from switching to Zen

**Comment by PushaG** [comment]
Yeah i have everything enabled same as @Leo9481 but it still doesn't work even after updates.

**Comment by Leo9481** [comment]
1.0.2-b.2, not fixed

**Comment by glassd** [comment]
Something has to be different with you setups vs mine. I just did a fresh setup with gfx.webrender.dcomp-video-hw-overlay-win-force-enabled set to true and hardware acceleration turned on and it's working without issues. Those were the only settings I changed. Both super resolution and HDR are working as expected. Did you change anything else?

**Comment by Leo9481** [comment]
1.0.2-b.3, aaaand.... not fixed

**Comment by Leo9481** [comment]
> Something has to be different with you setups vs mine. I just did a fresh setup with gfx.webrender.dcomp-video-hw-overlay-win-force-enabled set to true and hardware acceleration turned on and it's working without issues. Those were the only settings I changed. Both super resolution and HDR are working as expected. Did you change anything else?

Nope, everything I've done is listed in my message. Anyway, the dev acknowledged it as well, so it is a bug

**Comment by Leo9481** [comment]
I finally found out what the problem is. It's related to the NVIDIA Control Panel settings. If in your Global 3D app settings, you have capped your FPS, it will cause the issue. I had mine capped to 167fps so that the GSYNC could work. The easy solution is to simply head into the 3D settings, go to Program Settings, Add, choose Zen. Now, scroll down and turn off the FPS cap. This will only affect Zen, so you won't have any problems with other apps and games. @PushaG

**Comment by wyndon** [comment]
I'm still getting the issue of it not working if the video isn't in fullscreen, EXCEPT if I use PiP, the pop-out video feature. Which is fine by me, but still worth noting that the issue persists on non-fullscreen.

**Comment by Leo9481** [comment]
> I'm still getting the issue of it not working if the video isn't in fullscreen, EXCEPT if I use PiP, the pop-out video feature. Which is fine by me, but still worth noting that the issue persists on non-fullscreen.

oh yeah, it never worked if not in fullscreen for me. To be fair, only Auto-HDR is supposed to work when not in fullscreen. It'd be nice if it did, but as long as it works in fs I'm good

**Comment by NotAkitake** [comment]
Can confirm still not working for me, fullscreen or not.
As wyndon mentioned above, if I PiP the video THEN fullscreen that, it does work.

Version: 1.7.6b (20250207111303)

**Comment by Qiiks** [comment]
Same issue. I have done everything the Leo9481 did, but my VSR doesnt work if the video isnt fullscreened

**Comment by teoshibin** [comment]
> Can confirm still not working for me, fullscreen or not. As wyndon mentioned above, if I PiP the video THEN fullscreen that, it does work.
> 
> Version: 1.7.6b (20250207111303)

Same version as him, it only works in fullscreen.

**Comment by Zil0s** [comment]
1.9.1b version and works in full screen only 
Edit: Works also while using picture-in-picture feature, Doesn't matter if full screen or not in that case
2nd edit: doesn't work while there are captions visible in videos even in full screen so if there is characters talking in a video for example the captions appears then VSR stops working, after the characters stop talking caption become invisible then VSR works again (That doesn't apply to all sites, Works fine with youtube)

**Comment by Starry-AXQG** [comment]
It doesn't work whether I'm full screen or not.
Version 1.10b

**Comment by PushaG** [comment]
Good if it works for some of you, it never worked before and it still doesn't work me. I gave up some time ago and now i have Firefox nightly just for stuff like this.

**Comment by dog6o** [comment]
I also have 1.10.1b and VSR and HDR are not enabled unless in full screen.
I recently started using Zen and am impressed that Zen is a very nice browser.
However, this VSR bug is the only thing that is very disappointing.
Please fix this bug as soon as possible, please.

**Comment by mr-cheffy** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=Nvidia%20RTX%20video%20super%20resolution%20doesn%27t%20work%20in%20Zen%0A

**Comment by schzbayl** [comment]
> I was experiencing the same issue.
> 
> When I checked `about:support`, I found that `VIDEO_HARDWARE_OVERLAY` was `Blocklisted by gfxInfo`. In my environment, setting `gfx.webrender.dcomp-video-hw-overlay-win-force-enabled` to `true` in `about:config` allowed VSR to work properly.



> I was experiencing the same issue.
> 
> When I checked `about:support`, I found that `VIDEO_HARDWARE_OVERLAY` was `Blocklisted by gfxInfo`. In my environment, setting `gfx.webrender.dcomp-video-hw-overlay-win-force-enabled` to `true` in `about:config` allowed VSR to work properly.

WORKED

**Comment by PushaG** [comment]
I can confirm it does work now.

**Comment by kingghallab** [comment]
> I can confirm it does work now.

it doesn't work with me on zen, how do i fix it ??

**Comment by Humaman** [comment]
Here's how I fixed VSR (in full-screen only)

**Zen** (about:config)
`VIDEO_HARDWARE_OVERLAY` to `true`
`gfx.webrender.dcomp-video-hw-overlay-win-force-enabled` to `true`

**NVIDIA Control Panel:**

- Display -> Adjust desktop Size and position -> Scaling 
- then set your monitor to `No scaling`

3D settings -> Manage 3D settings -> Program Settings -> zen.exe (add it if it's missing)

- set `Image scaling` to `off`
- set `Vertical sync` to `off`
- set `Monitor Technology` to `Fixed Refresh`

Try restart Zen or reboot

Here's the full config for Zen, just in case

Feature | Setting
-- | --
Image Scaling | Off
Ambient Occlusion | Not supported for this application
Anisotropic filtering | Use global setting (Application-controlled)
Antialiasing - FXAA | Use global setting (Off)
Antialiasing - Gamma correction | Use global setting (On)
Antialiasing - Mode | Use global setting (Application-controlled)
Antialiasing - Setting | Use global setting (Application-controlled)
Antialiasing - Transparency | Use global setting (Off)
Background Application Max Frame Rate | Use global setting (Off)
CUDA - GPUs | Use global setting (All)
CUDA - Sysmem Fallback Policy | Use global setting (Driver Default)
Low Latency Mode | Use global setting (Off)
Max Frame Rate | Use global setting (Off)
Monitor Technology | Fixed Refresh
Multi-Frame Sampled AA (MFAA) | Use global setting (Off)
OpenGL GDI compatibility | Use global setting (Auto)
OpenGL rendering GPU | Use global setting (Auto-select)
Power management mode | Use global setting (Normal)
Texture filtering - Anisotropic sample optimization | Use global setting (Off)
Texture filtering - Negative LOD bias | Use global setting (Allow)
Texture filtering - Quality | Use global setting (Quality)
Texture filtering - Trilinear optimization | Use global setting (On)
Threaded optimization | Use global setting (Auto)
Triple buffering | Use global setting (Off)
Vertical sync | Off
Virtual Reality pre-rendered frames | Use global setting (1)
Virtual Reality - Variable Rate Super Sampling | Not supported for this application
Vulkan/OpenGL present method | Use global setting (Auto)

**Comment by TheBearOfJare** [comment]
Having done all of the above, it worked fine in 1.18 versions, but has since broken in 1.19 versions again. I cannot for the life of me get it to work in 1.19 (currently using v1.19.2b). Has anyone gotten it working?

**Comment by Starry-AXQG** [comment]
It works fine on my divice. However, it's only available in full-screen mode. It seems to not work in PIP or non-full-screen modes. (v1.19.2b)

> Having done all of the above, it worked fine in 1.18 versions, but has since broken in 1.19 versions again. I cannot for the life of me get it to work in 1.19 (currently using v1.19.2b). Has anyone gotten it working?

**Comment by finejustice** [comment]
With Game Ready Driver 595.97, RTX Video is not working even on official Firefox(149.0). 
So I guess nvidia should be blamed for recent issue.

**Comment by ZloyPirozhok** [comment]
> Here's how I fixed VSR (in full-screen only)

It worked for me, but only when I select "Extend to both monitors" in Windows. I use a monitor and a TV so that they don't mirror each other, and when I switch to "Duplicate monitors," VSR doesn't work. Do you know how I can fix this?
