### ISSUE TITLE
Screenshots overlay out of place in split tabs view 

### ISSUE THREAD

**Issue by Jai-JAP** [zen-browser/desktop#1967]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [ ] I am not filing an enhancement request.

### What happened?

When taking webpage screenshots in zen browser using firefox's built-in screenshot utility, if split tabs is enabled, the screenshot overlay is completely out of place and cannot be used at all.

It behaves as if its focusing on the sidebar instead.

![Screenshot From 2024-10-08 18-43-40](https://github.com/user-attachments/assets/0b9ee2d8-5da4-43ec-8e6a-4c1cc653a17c)

The same behavior occurs when either of the splits is active/focused.

Possibly related #1913 #1653 

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.7

### What platform are you seeing the problem on?

Linux

**Comment by BrhmDev** [comment]
Seems like this is fixed in 1.0.1-a.8

**Comment by Jai-JAP** [comment]
The issue is still the same on 1.0.1-a12

![image](https://github.com/user-attachments/assets/69339001-93a0-4df2-8f6d-e967837a06b2)


EDIT: To clarify things, By overlay i mean the screenshot buttons that are moved on to the left edge near the floating sidebar which just opens up while taking screenshot.

**Comment by Jai-JAP** [comment]
@BrhmDev This issue should be reopened as it's still present on latest version

**Comment by Jai-JAP** [comment]
This issue is partially fixed in 1.0.1-a18 as the screenshot overlay now lies in place as in firefox but its not possible to take screenshot of the split view using it.

Also note that the compact sidebar still gets expanded when using the screenshot tool.

[preview](https://github.com/user-attachments/assets/838853fc-2616-4de0-872f-28722175ef4b)

EDIT: This was my mistake as this issue is not related to the current one and is occurring when not using compact mode.


@BrhmDev

**Comment by Jai-JAP** [comment]
@mr-cheff @BrhmDev 
This is still an annoying issue in latest 1.0.1-a22. I use this feature a lot and its still completely broken. Please reopen issue and look into this.

The above comment was an incorrect one as it was completely an unrelated issue occurring when compact mode is disabled

**Comment by mr-cheffy** [comment]
Please don't ping us

**Comment by Jai-JAP** [comment]
The issue is slightly more improved on as taking screenshot does no longer trigger the tabs bar hovering and taking focus for the screenshot menu. 

However the issue is still relevant as screenshot menu is not in the correct place as it lies outside the current split and with change split on hover enabled, its impossible to use it.

![image](https://github.com/user-attachments/assets/3fde8c30-5d46-4597-a799-105b8c7c036b)

The solution here would be to make the screenshot menu lie inside the currently active split and when the user goes to other tab, shift the menu to the respective split

**Comment by Jai-JAP** [comment]
![Image](https://github.com/user-attachments/assets/1ea15edb-140a-4c40-b274-8da45788b548)

Apart from the screenshot buttons, the copy/download dialog is also out of place and very large

**Comment by Jai-JAP** [comment]
In v1.9.1b the preview seems to be in correct position but except this time the z-indexes are messed up,

Here I have 3 splits, created in the order right to left, When previewing screenshots, the dialog behaves differently for each split as follows.

Screenshot on split 1
![Image](https://github.com/user-attachments/assets/fa802460-30f0-459a-874d-92cf2cd4e5e0)

Screenshot on split 2
![Image](https://github.com/user-attachments/assets/62c77ddd-fb60-45bd-a5c1-1f73505bc5dc)

Screenshot on split 3
![Image](https://github.com/user-attachments/assets/c6058c0c-6a0a-4c3d-a394-b8f8f9af0b3f)

It behaves like the splits are being added on top of each other in terms of z-index, and the same behaviour is observed in case of other layouts with varying split counts.

**Comment by mr-cheffy** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=Screenshots%20overlay%20out%20of%20place%20in%20split%20tabs%20view%20%0A
