### ISSUE TITLE
Tabs sidebar "Expand on Hover" casuses jank with latest UI

### ISSUE THREAD

**Issue by michaelhthomas** [zen-browser/desktop#2033]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Seemingly due to the additional space consumed by the workspaces when the sidebar is compact (which are unnecessary as mentioned in #1791) there is a lot of jank when moving between the compact and expanded sidebar on hover. Beyond just the amount of time it takes for tabs at the bottom of the sidebar to become visible, there is also clearly some jank in the layout of the actual browser page, as displayed in the video below. It appears that the actual browser chrome is overflowing the viewport while transitioning.

https://github.com/user-attachments/assets/f75aeb88-dc9d-43a2-a416-d6a8ee5747be

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.8

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by giaaaacomo** [comment]
i'd like to add that if you click the 
![image](https://github.com/user-attachments/assets/64709e12-6a0b-4143-8ee7-5d970ac86933)  
button, the hover to expand disables even if you click it again. the expected behavior is that by clicking it expands until reclicked, that would make it go back with the hover to expand setting

**Comment by mr-cheffy** [comment]
This has been fixed, for the next version, thanks!

**Comment by kranthivakati** [comment]
this issue is resolved in latest build 1.0.1-a.9

https://github.com/user-attachments/assets/cec9bee2-48bc-45a1-bb1e-cef1bb104b66

**Comment by ivanjx** [comment]
i am still experiencing this issue on ubuntu with wayland


https://github.com/user-attachments/assets/83904e63-26ca-4dea-adeb-ff8a1f175bdd

**Comment by jwueller** [comment]
Yeah, this still happens in `1.0.1-a.10` as well. Some dimensions seem to change during the animation. I also notice that the bottom offset of the browser viewport is sometimes missing when you have a lot of tabs, which you can also briefly see flashing during the transition.

https://github.com/user-attachments/assets/cf3e4d1e-66b5-4e3d-86af-a62d65ec81c8

My hunch is that there is some combination of CSS overflow/transform issue at work here. My expectation would be that the viewport never changes dimensions due to the sidebar overlay.

**Comment by michaelhthomas** [comment]
Yep, can confirm that the behavior in `1.0.1-a.10` is exactly the same as it was in `1.0.1-a.8`. If this has truly been fixed, then the fix has not yet been released. I'm in favor of reopening this until the fix is actually released.

**Comment by mr-cheffy** [comment]
Oh, sorry about that...

**Comment by mr-cheffy** [comment]
This has been fixed for the next release (tested it out). Thanks!

**Comment by ivanjx** [comment]
seems good on a.12

**Comment by michaelhthomas** [comment]
This is still broken for me on `1.0.1-a.12`. I may take a look at the CSS myself to see if I can fix it.


https://github.com/user-attachments/assets/5d8fce53-19d6-4b42-8299-cb29f502b624

**Comment by jwueller** [comment]
Yeah, the viewport no longer overflows the window, but the sidebar jank is still very much present.

**Comment by csolisr** [comment]
Same here - on 1.0.1-a12, the issue with pinned tabs while "Expand Tabs on Hover" is on has been solved (now they have full width instead of being a grid), but the lower part of the sidebar shifts layouts between vertical (while not expanded) and horizontal (while expanded). This seems to be the core cause of the layout jank, as the amount of space in the tabs list needs to change. I've already tried to move the Zen Sidebar and Workspace buttons out of the lower part of the tabs sidebar, but even with just the New Tab button, the layout rearrangement issue seems to persist. A potential fix to this issue could be to use the layout that Microsoft Edge uses, basically replicating what was already done with the pinned tabs and making the vertical buttons full-width with text.

Also, in related news: the "Expand Sidebar" button toggles between "Expand Tabs" and "Do Not Expand Tabs", but never restores the "Expand Tabs On Hover" unless one goes directly to the settings.
