### ISSUE TITLE
what is "null"?

### ISSUE THREAD

**Issue by AlexCat315** [zen-browser/desktop#3237]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

top show. 'null'
<img width="631" alt="截屏2024-11-28 10 56 42" src="https://github.com/user-attachments/assets/59e539f6-ddde-4a15-a958-d4339d898bc2">

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.1-a.20

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by shinyuta** [comment]
I believe it's a bug with the new update. Thought I messed up my CSS or something because the timing was right when I made a lot of config changes across my machine. On [reddit](https://www.reddit.com/r/zen_browser/comments/1h1je2l/please_dont_update_to_version_20/) maubg asks people not to update while he works on a fix.

**Comment by blakegearin** [comment]
Duplicate: #3218

**Comment by matthewblott** [comment]
I have the same. I'm also unable to move the browser window on the left-hand side:

![Screenshot 2024-11-28 at 08 37 23](https://github.com/user-attachments/assets/2e5add75-0ed8-419b-92ca-c782ec69d0b2)

**Comment by DanRioDev** [comment]
First time I had to rollback a browser update, this a20 was a mess.

**Comment by SunflowerFuchs** [comment]
I'm pretty sure that was the "collapse sidebar" button, which broke when they removed the collapsible sidebar and now cannot be removed by the user anymore.

**Comment by RayZ3R0** [comment]
Version a20 is filled with some bugs, a21 is going to be released soon, please try that when it comes out. For now, I would suggest downgrading to a19 until a21 comes out, which should be very soon.

**Comment by RayZ3R0** [comment]
Fixed in a21, please update! Reopen the issue if this still happens

**Comment by SunflowerFuchs** [comment]
The old null issue has been fixed by a21, however a new null has now appeared 😄 
Not sure if this is appropriate here or should be a new issue
![image](https://github.com/user-attachments/assets/575bd34d-3716-4f4a-9917-010bef283660)

**Comment by ArchitektApx** [comment]
> The old null issue has been fixed by a21, however a new null has now appeared 😄 Not sure if this is appropriate here or should be a new issue ![image](https://private-user-images.githubusercontent.com/18332886/390720349-575bd34d-3716-4f4a-9917-010bef283660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODY0MDYsIm5iZiI6MTczMjc4NjEwNiwicGF0aCI6Ii8xODMzMjg4Ni8zOTA3MjAzNDktNTc1YmQzNGQtMzcxNi00ZjRhLTk5MTctMDEwYmVmMjgzNjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA5MjgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NGE1YTA0NmJiZWQzNWU5MDQ1ZDczODk0M2E2NjNmYWRmMzNlODdjNTg3OGQzNTFlOTQ5ZDJkMjA2YTUxMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tRZw-kINedxXDM4-doTQElaWfBwUpU-ePvKNYwOi_3o)

Same for Linux aarch64 -> the "null" just moved

**Comment by fauzie811** [comment]
a21 didn't fix the issue, it just moved the "null"s

<img width="518" alt="Screen Shot 2024-11-28 at 16 29 23" src="https://github.com/user-attachments/assets/39ab8213-c63e-4daf-907a-efe54c2f6453">

**Comment by RayZ3R0** [comment]
Yep that has been found out. Will be fixed in a22 which is releasing soon
