### ISSUE TITLE
clicking with mouse doesn't open website in floating url bar after typing, but pressing enter on keyboard works.

### ISSUE THREAD

**Issue by PushaG** [zen-browser/desktop#3540]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

When i open new tab and start typing i can't mouse click on suggestion, but if i click on url bar first and type after, then can i open website with click. Typing, using arrows for navigation and enter to confirm works normally in floating url bar. This only happens with mouse click. All mods are disabled.

Check out this reddit post that i made showing the bug in action: https://www.reddit.com/r/zen_browser/comments/1hbb26p/when_i_open_new_tab_and_start_typing_i_cant_mouse/

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.0 

### What platform are you seeing the problem on?

Windows

**Comment by kittybwained** [comment]
I have this issue too

**Comment by soratoyuki** [comment]
Also having the issue, see #3581

**Comment by soratoyuki** [comment]
Issue seems to persist in 1.0.2-b.1 (Firefox 133.0) (64-bit).

**Comment by seyoatda** [comment]
For me, if opening url bar by clicking it works just fine. but when opening url bar by shortcuts like Alt + D / Ctrl + L，it can not handle mouse clicking

**Comment by mandiuk** [comment]
Same here, it's impossible to click any link on the floating URL bar.

It only works if you manually click in the URL bar with the mouse at the top of the browser. However, if you open a new tab or press Ctrl+L, it becomes unclickable.

Windows 11, 1.0.2-b.1 (Firefox 133.0) (64-bit)

**Comment by PushaG** [comment]
This issue has been fixed in latest update 1.0.2-b.2

**Comment by jarz76** [comment]
> This issue has been fixed in latest update 1.0.2-b.2

what zen url behavior you use?

I'm still having the issues if i use the "Always Floating".

https://github.com/user-attachments/assets/0516e502-fcd1-4272-86cc-21737d740a77

**Comment by ghost** [comment]
Issue duplicated on #3671 
Confirming still present in 1.0.2-b.2
Platform and build independent
​
​
Conditions -

1. URL behaviour must be set to "Always floating"  
    -  "Normal" and "Floating only when typing" do not exhibit the bug.
​    
2. Focus the bar either through a shortcut or use the auto focus on opening a new tab
    -  Focusing the bar by clicking on it does not exhibit the bug.
​    
3. Click on a suggestion
    -  Keyboard selection works normally.

**Comment by PushaG** [comment]
> > This issue has been fixed in latest update 1.0.2-b.2
> 
> what zen url behavior you use?
> 
> I'm still having the issues if i use the "Always Floating".
> zen_DBuwai5Oks.mp4

You're right. When i tested it 2 days ago, default setting was "floating only when typing" and it works as it should with this setting enabled. But after setting it to "always floating" i can confirm that issue still persists.
