### ISSUE TITLE
weird title bar

### ISSUE THREAD

**Issue by valkyrieglasc** [zen-browser/desktop#3693]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/6c535668-f40f-4742-a1f9-2b54ce22f389)
after the update, there's a weird top bar color appear behind my tab. It doesn't goes away
![image](https://github.com/user-attachments/assets/8bb908ad-1df8-4f54-b0a4-42cb8b0c9ea6)
and yesterday, it was purple btw, now it's blue

I did turn off all my mods and extensions but it still there, I also have the same problem when I tried using Zen Twilight

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2 b.t 64 bit

### What platform are you seeing the problem on?

Windows

**Comment by ruzfyi** [comment]
I have this same issue. Somehow mine changed to being transparent.

![image](https://github.com/user-attachments/assets/ccd6d12c-4225-419b-bd83-6dc9dac29d8f)

Hovering over the close button on anything other than a "New Tab" will cause the block to shrink almost but still be visible. It becomes about the same width as the borders around windows on Zen.

I should also add that it appears the same as Yapper27's if I go into Compact Mode with both bars.

**Comment by MemQu** [comment]
It is not just a twilight release issue.

My current version:
1.0.2-b.2 (Firefox 133.0.3) (64-bit)

![image](https://github.com/user-attachments/assets/e509e9b1-b20b-4f3e-a4dd-5ea460f0fd56)

Stretching the webpage to cover all of the screen is a much cleaner experience. The highlights distract and waste pixels

**Comment by joaorego01** [comment]
Same here, I think the color might be your desktop theme color.
![Screenshot 2024-12-16 100445](https://github.com/user-attachments/assets/9d1025ed-8268-435e-bc0d-71042a4c16d5)

**Comment by jenilradadiya98** [comment]
I tried enabling Title bar and yes, that is the title bar that should not be visible but somehow is visible.

This with title bar option turned on:
![image](https://github.com/user-attachments/assets/251a3b73-d5e1-480e-bfc5-58cc95538745)


This is with title bar option turned off
![image](https://github.com/user-attachments/assets/c67df244-198e-498a-b115-908351d6defa)

Edit: Issue only started to happen after the browser updated to new version.

**Comment by JSGRD22** [comment]
That is the windows title bar showing. Try disabling “show accent color on title bar and window borders” in windows settings, or disable mica in about:config.

**Comment by valkyrieglasc** [comment]
> That is the windows title bar showing. Try disabling “show accent color on title bar and window borders” in windows settings, or disable mica in about:config.

OMG THAT'S WORKED!! TYSM

**Comment by jenilradadiya98** [comment]
> That is the windows title bar showing. Try disabling “show accent color on title bar and window borders” in windows settings, or disable mica in about:config.

Well, Thank you for solving this issue, but I don't remember enabling this so I think this should be fixed in next version.

**Comment by bubin7766** [comment]
![image](https://github.com/user-attachments/assets/14503aa3-43e2-418d-9db9-2b790148aaab)
Can confirm that the issue is still present with the new update

**Comment by mr-cheffy** [comment]
>  I have searched existing issues and avoided creating duplicates.

**Comment by mr-cheffy** [comment]
https://github.com/zen-browser/desktop/issues/3469

**Comment by kris3713** [comment]
> ![image](https://private-user-images.githubusercontent.com/83966481/395450478-8bb908ad-1df8-4f54-b0a4-42cb8b0c9ea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MTM2MzgsIm5iZiI6MTczNjgxMzMzOCwicGF0aCI6Ii84Mzk2NjQ4MS8zOTU0NTA0NzgtOGJiOTA4YWQtMWRmOC00ZjU0LWIwYTQtNDJjYjhiMGM5ZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDAwMDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMGVkZjMwZDU4MTY3NmQwMWE3N2NkOTIxOGIyY2FiMjZkMzE5NDAyM2MzOWNkNjJhYjc3N2UzNGRiOTM1NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dvEVpD7ORnIPw6tDkm2pa5D3rzi6FKDGEfxVA_QJ4d8)

I know this is off-topic but could you show how you made your desktop look like that, it looks very pretty.
