### ISSUE TITLE
URL Bar weird behaviour on compact mode and shortcuts

### ISSUE THREAD

**Issue by shaeriz** [zen-browser/desktop#3757]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

The URL bar is not aligned on compact mode and the floating url bar still remains when shortcuts like CTRL + T or ALT + D are pressed.

![zen_zFS7yrGmDE](https://github.com/user-attachments/assets/4c6cf2e6-8b5e-493a-812d-ffa9cfa7faf2)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-t.3

### What platform are you seeing the problem on?

Windows

**Comment by atouu** [comment]
Fixed it with this css
```
#urlbar[breakout][breakout-extend] {
   min-width: 0 !important;
   top: 0 !important;
}
```

Then setting Zen URL Behavior to Normal

**Comment by RodsonMatos** [comment]
For me it only works when the bar is empty

**Comment by shaeriz** [comment]
Using 1.0.2-t.3 here and the issue was partially fixed, the url bar is now aligned but its behavior when triggered by shortcuts like alt + D or typing right after making a new tab with ctrl + T still makes it float (if that's intentional please ignore this comment and close the issue).

Also thank you for the great work, Cheff!

**Comment by theodorlevi** [comment]
it happens to me  aswell. the url bar is often just completely missing. also happens on linux at least wayland.

**Comment by syscat29** [comment]
This has been fixed in Twilight 1.0.2-t.4

![image](https://github.com/user-attachments/assets/ae8bbe12-5902-4624-8aa5-14cf1f056a5d)

https://github.com/user-attachments/assets/102d199c-a98a-4a3a-bc9f-ee419f33fe1c

**Comment by shaeriz** [comment]
strange, I'm on 1.0.2-t.4 right now and the problem persists even on a new profile, did you edit something?

**Comment by syscat29** [comment]
> strange, I'm on 1.0.2-t.4 right now and the problem persists even on a new profile, did you edit something?

Negative, chief all the custom css has been disabled but none of the changes were relevant to the url bar

**Comment by shaeriz** [comment]
> Negative, chief all the custom css has been disabled but none of the changes were relevant to the url bar

which OS are you using?

**Comment by syscat29** [comment]
> > Negative, chief all the custom css has been disabled but none of the changes were relevant to the url bar
> 
> which OS are you using?

Windows 11

**Comment by shaeriz** [comment]
> > > Negative, chief all the custom css has been disabled but none of the changes were relevant to the url bar
> > 
> > which OS are you using?
> 
> Windows 11

Hmm I'm using windows 10, not sure if it can be related to it

**Comment by theodorlevi** [comment]
> > > > Negative, chief all the custom css has been disabled but none of the changes were relevant to the url bar
> > > 
> > > which OS are you using?
> > 
> > Windows 11
> 
> Hmm I'm using windows 10, not sure if it can be related to it
> 

Tried it on windows 11 and it doesn't happen there. But it does happen on linux(fedora 41).

**Comment by syscat29** [comment]
For those that may not know, there are settings to change this behavior.

Settings > Look and Feel > Zen URL Bar

![image](https://cdn.discordapp.com/attachments/1302759683882225774/1319434195747082250/image.png?ex=6765f25a&is=6764a0da&hm=e0e6c92b0d1f74e8a19290b826d1f023a64d790b010eff5f07649014ffa4fb0d&)

**Comment by shaeriz** [comment]
oh nevermind it's a setting now, yea the issue can now be closed, it's fixed on 1.0.2-t.4.
![image](https://github.com/user-attachments/assets/86105752-c0f2-4c79-90fd-d95a88c349b2)

**Comment by syscat29** [comment]
@Cat86x Can you confirm if using the options above solves your problem?

**Comment by theodorlevi** [comment]
> @Cat86x Can you confirm if using the options above solves your problem?

Yes Tried it and worked. The bar is appearing now.
