### ISSUE TITLE
Zen specific keyboard shortcuts not working in Mac

### ISSUE THREAD

**Issue by thelazyoxymoron** [zen-browser/desktop#376]
### What happened?

I just installed this on M1 Mac and the Zen specific keyboard shortcuts are not working (e.g. cycle workspaces, split view grid etc.). Firefox specific shortcuts work correctly (e.g. Command + T to open new tabs).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.26 (64-bit)

### Severity impact

Low

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by thezacharytaylor** [comment]
I can confirm this issue on a M1 Pro MacBook Pro running Sonoma 14.5. Close Split View works, however.

That said, I want to add on to this that attempting to modify the split view shortcuts doesn't work. It will not take letters. For example I try to change it to `Cmd + Alt + G` and it comes out as `Alt + Meta + `. I tried with both my external and MBP keyboard and got the same result. I also use Karabiner to modify some keys (swapping alt w/ windows key on my external to mirror my MBP keyboard for example), but not letter keys. It seems to detect the changes I did make properly anyway. That said, I do use Colemak, but that is set through the system settings.
![Screenshot 2024-08-21 at 12 59 08](https://github.com/user-attachments/assets/ab5a1ab4-fa52-4d80-a805-4db5279a1343)

**Comment by thelazyoxymoron** [comment]
I can also confirm the bug mentioned by @thezacharytaylor. In my case, it takes some weird greek letters.

![Screenshot 2024-08-22 at 12 05 37 AM](https://github.com/user-attachments/assets/ba5552d4-ad1a-4792-9196-347a25fb200c)

**Comment by Amplificator** [comment]
Same issue here on a Macbook Air M1 using macOS Sonoma 14.6.1

**Comment by bartenalles** [comment]
The custom shortcut that I have configured for switching between workspaces (Cmd + E) does work, but the other shortcuts do not. Zen 1.0.0-a.27, M3 MacBook Pro.

**Comment by dannymasao** [comment]
I can confirm this is happening on my mac too. I tried setting command + shift + c and it keeps saving it as Shift + Meta + C.
Intel Macbook Pro, Sonoma 14.5
Zen 1.0.0-a27

![Screenshot 2024-08-22 at 21 52 55](https://github.com/user-attachments/assets/ee20a515-057c-4d93-b430-a590e04c731f)

**Comment by DwieDave** [comment]
I can also confirm that Shortcuts on Mac appear to be flaky. 
After trying to find working alternative hotkeys for the Split View commands the new Tab Shortcut using the Command Key on mac is not working anymore regardless the other settings. 
When using e.g. Alt+t it works as expected.

It also works when selecting the "File" Menu in the macOS Menubar and then doing the Cmd+t hotkey.


Version: 1.0.0-a.28
macOS: Sonoma 14.5

**Comment by lethanix** [comment]
Some workarounds:

- The `Ctrl` key listed in the shortcuts actually uses `Cmd`, in other words, if you have a shortcut listed as `Ctrl + Alt + G`, you can use `Cmd + Alt + G`. 

- To avoid using greek letter with the `Alt` key, you can go to `Settings > Keyboard > Input Sources`, select the `+` icon, scroll all the way down to select `Others` and add the *Unicode Hex Input*

Go ahead and test it!

Note: I'm not able to get the grid view, only the side by side view 😞

**Comment by DwieDave** [comment]
Sadly both workarounds are not working for me so I can get my Cmd + T Shortcut for opening new Tabs back. 

I also tried reinstalling everything but nothing gave me back the orginal gesture and I don't want to mentally remap new Tabs to a different one. 

Maybe this is a different bug then.

**Comment by JamesRivers** [comment]
confirmed this is an issue on macos - ProductVersion:14.5 
Shame as this is the feature I wanted to see and use, coming from FireFox.

**Comment by Myran** [comment]
Can confirm this issue. No workaround works and this keeps me from using zen at all unfortunately.

**Comment by vineethvijayan314** [comment]
I remapped the keys to 

<img width="740" alt="image" src="https://github.com/user-attachments/assets/47649ca4-c2c9-4dd2-9d24-2f37656db0a7">

but it only works with CMD instead to Ctrl.

It is a bit of an annoyance, since you will loose the easy navigation to 1-4 tabs

**Comment by mauro-balades** [comment]
Although it displays "Ctrl" on the settings, im actually setting them to `accel`, because firefox handles it like this:

```
accel ->
   windows/linux: Control
   macos: Meta
```

The display issue on the settigns will be fixed for the next release

**Comment by JohnnWi** [comment]
same problem very very bad

**Comment by HarryHeres** [comment]
Adding to this issue, when the checkbox "Disable Zen specific keyboard shortcuts" is checked, the shortcut for refreshing the page (CMD + R) stops working.

**Comment by pachungulo** [comment]
Another issue, using control gets interpreted as CMD in keybind remapping, and CMD gets interpreted as meta. Weird...

**Comment by neilgilmour** [comment]
I was looking for a way to set keymaps in a config file or something. I haven't found that yet but [this line](https://github.com/zen-browser/components/blob/36e62781e27c19fade2df4d6a63e9062862ce7b0/src/ZenKeyboardShortcuts.mjs#L343) seems to be where we get the `Ctr` vs `Cmd` issue.

**Comment by mauro-balades** [comment]
@harryheres you've got this, right?

**Comment by HarryHeres** [comment]
Yes, already testing out some stuff

**Comment by n7itro** [comment]
Fixed with version `1.0.0-a.38`.

**Comment by HarryHeres** [comment]
> Fixed with version `1.0.0-a.38`.

*should be

**Comment by neilgilmour** [comment]
> > Fixed with version `1.0.0-a.38`.
> 
> Partial fix for CMD shortcuts in 38, more fixes coming soon

On 39 (after using the in-app updater) for me it still shows `meta` for Cmd, and `Cmd` for Ctrl.

**Comment by Amplificator** [comment]
Same for me, so adding a shortcut such as Cmd+Ctrl+X for next tab and Cmd+Ctrl+Z for previous tab, doesn't work.

**Comment by HarryHeres** [comment]
Yeah, seems like the build was done in the mean time some PRs were being merged. Postponing the full fix into future versions. Sorry about that.

**Comment by bmdev88** [comment]
Hi, 

should it be fixed now?
I've still the topic that the shortcuts are not correct:

![CleanShot 2024-09-14 at 18 29 39](https://github.com/user-attachments/assets/3e6609bd-7e67-4666-9101-b09061019484)

**Comment by HarryHeres** [comment]
No, it's still WIP. Watch #1363 for current progress.

**Comment by vineethvijayan314** [comment]
the combo I got is 

<img width="728" alt="image" src="https://github.com/user-attachments/assets/d4fd3f70-6320-4efd-b121-fdb2538a1a99">


even though it shows ¡,™,£,¢

its option+command+[1-4] 
this way I wont loose the command + number for navigation

**Comment by entermask** [comment]
same

**Comment by leikoilja** [comment]
dang it, same issues for me. 
Ctrl+Option+s gives me greek letters

<img width="637" alt="Image" src="https://github.com/user-attachments/assets/c72fcf9b-28b6-493f-9795-be4f236f4ca3" />

**Comment by Myran** [comment]
Still an issue in 1.12.8b

**Comment by ChildishhAlbino** [comment]
This issue has plagued me every time I've tried to switch to Zen. Please reopen the issue.
