### ISSUE TITLE
Loose my Essentials and Pinned tab icons after restarting

### ISSUE THREAD

**Issue by tanaybhomia** [zen-browser/desktop#3899]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

![image](https://github.com/user-attachments/assets/ecde2c10-5606-48db-8984-d719164025a7)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.3

### What platform are you seeing the problem on?

Linux

**Comment by djorium** [comment]
Do you delete cached images after restart in ur settings?

**Comment by tanaybhomia** [comment]
In the browsers setting ? NO

**Comment by tanaybhomia** [comment]
![image](https://github.com/user-attachments/assets/68f50a2a-0540-4d0c-adb2-cd9ae2ea46aa)
Here in the first profile the youtube logo is there but in the other profile Youtube icon does not cache.

**Comment by Tehhaas** [comment]
Same thing happens to me, but I've noticed that my second workspace seems to keep the pinned tabs. It's just the primary workspace that loses pinned tabs. Essentials are gone for both workspaces.

**Comment by zplawecki** [comment]
just checked it for build 1.0.2-b.5 (Windows) and this issue is still present, I wonder when it will be solved

**Comment by tanaybhomia** [comment]
I dont know why but bug stopped happening on my machine after I unchecked this option
![image](https://github.com/user-attachments/assets/b85db291-a853-4239-9a07-ac8c49e1bb58)
Check if this works for you guys

**Comment by zplawecki** [comment]
I don't have it checked

**Comment by asidius** [comment]
This started happening to me after I dragged a tab out to a new window. The new window for some reason had no essentials or pinned tabs. I closed the new window, but Zen used that new window to override my main setup, removing all my pinned tabs and essentials.

It has happened multiple times since beta released. I have not experienced this issue in Twilight, but it has it's own issues so still a lose lose situation...

**Comment by mr-cheffy** [comment]
This shoud've had been fixed in b5

**Comment by zplawecki** [comment]
> This shoud've had been fixed in b5

but this specific case described by Asidius or issues with missing essentials and pinned in general? because, as I wrote previously, I'm using b5 and it's not fixed

**Comment by asidius** [comment]
Happened to me in b5 today.

**Comment by luke-monroe** [comment]
This issue is related to opening and closing multiple windows of Zen. Some weird stuff starts happening when you do that

**Comment by r0bbie** [comment]
Every time Zen updates and restarts I lose all my essentials, and it's super frustrating. (or today randomly all of them aside from one)

**Comment by mr-cheffy** [comment]
Guys telling me it doesn't work doesnt provide anything helpful. Im gonna need videos

**Comment by zplawecki** [comment]
> Guys telling me it doesn't work doesnt provide anything helpful. Im gonna need videos

here's my recording: https://drive.google.com/file/d/1bYgmDpYBs-4oROT_h_NV8rQK7oL-hsTS/view?usp=sharing

today I discovered that when I was adding pages to Essentials (that's what "Dodaj do niezbędnych" means in Polish on video), I could suddenly see all previously added pages, but when I closed and reopened it - all of them were gone (or more like "hidden"?) again
