### ISSUE TITLE
Issue with Toolbar Pinning/Unpinning Affecting Sidebar Width in Zen Browser

### ISSUE THREAD

**Issue by UtkuGARIP** [zen-browser/desktop#4108]
### Captchas

- [X] I have read the instructions.
- [X] I have searched existing issues and avoided creating duplicates.
- [X] I am not filing an enhancement request.

### What happened?

Hello Zen Browser Team,

I noticed an issue while pinning or unpinning any extension to the toolbar. When the sidebar on the left (the one showing tabs) is minimized, it resets to its default width or expands after this action.

I believe the sidebar's width should remain unchanged during such operations to maintain user preferences.

Thank you for your attention to this matter!

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.2-b.5 (Firefox 133.0.3) (64 bit)

### What platform are you seeing the problem on?

Windows

**Comment by JSGRD22** [comment]
Probably fixed with an overflow menu in the latest release

**Comment by milindpatel63** [comment]
I still have this issue in the latest release.
 
I can manually reduce the width of the sidebar, and extra items go into overflow menu, but after browser restart, the width resets back to default max based on the items pinned in the toolbar.

Kindly look into this.

**Comment by milindpatel63** [comment]
> I still have this issue in the latest release.
> 
> I can manually reduce the width of the sidebar, and extra items go into overflow menu, but after browser restart, the width resets back to default max based on the items pinned in the toolbar.
> 
> Kindly look into this.

I managed to temporary fix this by adding this to my userChrome.css
```
#navigator-toolbox {
  width: 305px !important;
  min-width: 250px !important;
  max-width: 305px !important;
}
```
After that, the sidebar remains at fixed 305px width across reboot as per my preference.

**Comment by mr-cheffy** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=Issue%20with%20Toolbar%20Pinning%2FUnpinning%20Affecting%20Sidebar%20Width%20in%20Zen%20Browser%0A
