### ISSUE TITLE
No button to enable compact mode in settings page

### ISSUE THREAD

**Issue by unnath0** [zen-browser/desktop#4473]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

There is no button to enable compact mode, but it can still be enabled through keyboard shortcut

![Image](https://github.com/user-attachments/assets/f659995a-cb8e-49d8-b30f-0612b4c0adf5)

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.1b (64-bit)

### What platform are you seeing the problem on?

Windows

### Relevant log output if applicable

```shell

```

**Comment by sekhar546** [comment]
I want to know about the same issue. Compact mode is the primary reason that I use the zen browser. Now that's gone, I'm not sure when it's coming back. I hope this is fixed soon.

**Comment by neu-ma-tic** [comment]
> I want to know about the same issue. Compact mode is the primary reason that I use the zen browser. Now that's gone, I'm not sure when it's coming back. I hope this is fixed soon.

 it still exists, you just must use the keybind in this release for some weird reason

**Comment by JSGRD22** [comment]
[#4454](https://github.com/zen-browser/desktop/issues/4454#issuecomment-2602438074)
Please, read the release notes

**Comment by unnath0** [comment]
Thanks for the clarification. I must have missed that thread since I used "compact" while searching
