### ISSUE TITLE
Opening the overflow menu twice freezes the browser window on MacOs

### ISSUE THREAD

**Issue by ArchitektApx** [zen-browser/desktop#4489]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Both in the most recent Twilight and Beta Version, opening the overflow menu for a second time causes the browser window to freeze and zen has to be force quit. 

The following is a fresh profile with no zen-mods:

https://github.com/user-attachments/assets/c37b0c29-7927-4a82-a4dd-4b1fe6768a08

After the second time clicking the overflow menu, the cursor turns into the mac "spinning loader" (which is not visible in the recording) and stays that way until zen is force quit. No clicks are recognized anymore as seen in the recording.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7 and up

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output if applicable

```shell

```

**Comment by ArchitektApx** [comment]
Issue persists with latest release of 1.7.2t

**Comment by pray3m** [comment]
also experiencing this issue where the app becomes unresponsive, requiring me to force close it to regain control.

**Comment by ArchitektApx** [comment]
seems this was fixed in https://github.com/zen-browser/desktop/commit/a3bebadff87d5b4315e9917810b9d69213cfdf5c

**Comment by lmBored** [comment]
This issue still persists for me on 1.7.5b, even tried it in a new clean profile to make sure.

Another person on reddit is also having this issue, I don't think this is fixed yet.
