### ISSUE TITLE
Printing preview loads indefinitely

### ISSUE THREAD

**Issue by LilithL** [zen-browser/desktop#4555]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

The preview when printing a PDF loads infinitely.

in the console, i get this kind of error : 
```js
Warning: Invalid absolute docBaseUrl: "file:///C:/Users/****/****.pdf". pdf.worker.mjs:344:13
PDF a2ee3b5828a3d3ff9493b54d02dce2b6 [1.7 PDFlib+PDI 9.1.2p1-i (OS X/macOS) / Serif Affinity Publisher (Sep 26 2019)] (PDF.js: 4.9.14 [bff673896]) viewer.mjs:12482:13
Uncaught DOMException: Window.print: No browsing context
    triggerPrinting resource://pdf.js/web/viewer.mjs:12696
    dispatch resource://pdf.js/web/viewer.mjs:1323
    dispatch resource://pdf.js/web/viewer.mjs:1380
    bindListeners resource://pdf.js/web/viewer.mjs:11356
2 viewer.mjs:12696
```

I checked the browser toolbox just in case, i get these errors (some may be irrelevant to this bug, i added it for extra info that could help solve this issue): 
```js
12:25:13.883 Uncaught TypeError: tab is undefined
    shouldOpenTabInGlance chrome://browser/content/zen-components/ZenGlanceManager.mjs:326
    onTabOpen chrome://browser/content/zen-components/ZenGlanceManager.mjs:339
    browser_createContentWindowInFrame chrome://browser/content/browser.js:4462
ZenGlanceManager.mjs:326:19
12:25:13.893 Already stopped listening to server sent events for this window. server-sent-events.js:81:17
12:25:13.903 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. print.html
12:25:13.920 TypeError: browsingContext.currentWindowGlobal is null
    checkForSelection chrome://global/content/printUtils.js:76
    init chrome://global/content/print.js:180
    <anonymous> chrome://global/content/print.js:89
    EventListener.handleEvent* chrome://global/content/print.js:81
printUtils.js:80:15
    checkForSelection chrome://global/content/printUtils.js:80
    init chrome://global/content/print.js:180
    <anonymous> chrome://global/content/print.js:89
    (Async: EventListener.handleEvent)
    <anonymous> chrome://global/content/print.js:81
12:25:13.920 TypeError: sourceBrowsingContext.currentWindowGlobal is null
    init chrome://global/content/print.js:185
    async* chrome://global/content/print.js:89
    EventListener.handleEvent* chrome://global/content/print.js:81
print.js:89:71
    _initialized chrome://global/content/print.js:89
    (Async: promise callback)
    <anonymous> chrome://global/content/print.js:89
    (Async: EventListener.handleEvent)
    <anonymous> chrome://global/content/print.js:81
12:25:14.164 Error: ChromeUtils.importESModule: global option is required in DevTools distinct global CacheEntry.sys.mjs:7:13
12:26:15.051 SearchEngine: getSubmission: searchTerms is empty! SearchEngine.sys.mjs:1208:23
```

I checked and i don't have this issue on firefox dev edition (version 135.0b6), which gives me this console log :
```js
Partitioned cookie or storage access was provided to “file:///C:/Users/****/****.pdf” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Warning: Invalid absolute docBaseUrl: "file:///C:/Users/****/****.pdf". pdf.worker.mjs:345:13
PDF a2ee3b5828a3d3ff9493b54d02dce2b6 [1.7 PDFlib+PDI 9.1.2p1-i (OS X/macOS) / Serif Affinity Publisher (Sep 26 2019)] (PDF.js: 4.10.22 [4547f230b]) viewer.mjs:12605:13
```

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.2b

### What platform are you seeing the problem on?

Windows

### Relevant log output if applicable

```shell

```

**Comment by High-rider** [comment]
Same, for me its also stuck on print preview
![Image](https://github.com/user-attachments/assets/f01c3915-4815-44e7-aac5-7cf65487d476)

**Comment by PHATWalrus** [comment]
can confirm

**Comment by schembriaiden** [comment]
Same here

![Image](https://github.com/user-attachments/assets/faa98fb9-76a4-4a67-95fe-9580b820e9eb)

**Comment by kneekna** [comment]
same :/

**Comment by mr-cheffy** [comment]
This has been fixed for the next release, thanks!

**Comment by kneekna** [comment]
i'm still having this issue after updating

**Comment by pajades** [comment]
This issue persists in the latest version 1.7.2b
Build ID: 20250122122842
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0
OS: Linux 6.8.0-52-generic #53-Ubuntu SMP PREEMPT_DYNAMIC Sat Jan 11 00:06:25 UTC 2025

Additionally, tyring to print [site generated PDFs](https://syndication.andrewsmcmeel.com/puzzles/crosswords) fails to keep the print preview window open (the Print Preview window breifly opens, then closes)

![Image](https://github.com/user-attachments/assets/396e0661-9f0a-4ecc-8908-8d653e141030)

Here is the code from the console when clicking "[print] Blank":
```

TypeError: browsingContext.currentWindowGlobal is null
    checkForSelection chrome://global/content/printUtils.js:76
    init chrome://global/content/print.js:180
    <anonymous> chrome://global/content/print.js:89
printUtils.js:80:15
```

```
TypeError: sourceBrowsingContext.currentWindowGlobal is null
    init chrome://global/content/print.js:185
print.js:89:71
```

These functions operate as expected in other browsers: Firefox and Librewolf.

**Comment by pajades** [comment]
> i'm still having this issue after updating

I did, too, but after a system restart & Zen actually updated to 1.7.4b the issue went away
