### ISSUE TITLE
Bug, tabs getting "stuck" randomly, unclickable

### ISSUE THREAD

**Issue by sanasol** [zen-browser/desktop#4583]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

 Using pinned/unpinned tabs, closing it with Cmd + W

And when I do it in my usual manner pretty fast its often make opened tabs unclickable until I close and reopen it.

Somehow I found out that its actually another tab active at this moment, while I clicked to some other tab and its displayed over the active tab all click going to different tab that is not visible/hidden by current visible content from unclickable tab.

Trying to use Zen since yesterday, but this thing makes it unusable.

I tried to enable/disable glance, side web panels. No difference.

Also found out that Glance works despite the Enable glance checkbox value. 

https://github.com/user-attachments/assets/042f6eb4-4e95-4e82-820a-5ecc8dcaaad6

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.2b

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output if applicable

```shell

```

**Comment by gallantcrusader** [comment]
Happens with me as well, with the added benefit of the main webpage renderer just being completely blank 

![Image](https://github.com/user-attachments/assets/70ce91b7-7c0f-425a-b4c0-4c73673ab61d)

**Comment by oerix** [comment]
Same issue here, have to force quit every time.

**Comment by KorigamiK** [comment]
possible duplicate #4583

**Comment by JSGRD22** [comment]
> possible duplicate [#4583](https://github.com/zen-browser/desktop/issues/4583)

Did you mean to reference another issue? This is #4583

**Comment by KorigamiK** [comment]
> Did you mean to reference another issue? This is [#4583](https://github.com/zen-browser/desktop/issues/4583)

my bad i meant #4690 which is the duplicate instead

**Comment by mr-cheffy** [comment]
This shoud've had been fixed with the latest release, can anyone check?

**Comment by Machete3000** [comment]
Not fixed... Happened to me 3 times since yesterday... my first day using Zen. 1.7.6b (Firefox 135.0) (64-bit). 

Doesn't happen with Firefox, which I've been using for a long time.

ComfyUI is pretty effective crashing Zen.

**Comment by JVPH** [comment]
Still happening, changing between tabs seems to 'un-freeze' it.

edit: this is not zen specific, the bug is present in firefox as well.

**Comment by oerix** [comment]
Seems like in has reappeared in 1.7.6b. It hangs after a while, possible memory leak.

**Comment by nguu0123** [comment]
happens multiple time recently for me when I move from 1.7 to 1.10

**Comment by mr-cheffy** [comment]
Could you please provide videos?

**Comment by 0Ky** [comment]
@mauro-balades I'm not sure if this is the same issue, but this is how you re-produce the bug where `tabs getting "stuck"`:
```cpp
1. Open Zen Browser.
2. Use the "Ctrl+Shift+P" keyboard shortcut to open a new private window.
3. Visit any website.
4. Pin the tab.
```
At this point any new opened tabs cannot be viewed by either clicking on them or using the keyboard shortcut ctrl+tab/ctrl+shift+tab.

This was tested in both Linux and Windows operating system.

https://github.com/user-attachments/assets/6ee43ae6-60bd-47fe-b2c7-743040a17fac

**Comment by Cobesz** [comment]
Is this fixed? Because I get this multiple times a day still. It unfreezes when you start dragging the browser window. Looks like the entire browser freezes.

Using Linux, bazzite distro. It happens on both my laptop and desktop. Desktop using KDE and laptop using Gnome.
Also, my desktop is using the .appimage and my laptop uses the flatpak

**Comment by MBausson** [comment]
I'm also getting these freezes as well. Reloading freezed page does not work. I fix the tab by closing it and re-opening it

**Comment by Cobesz** [comment]
> Is this fixed? Because I get this multiple times a day still. It unfreezes when you start dragging the browser window. Looks like the entire browser freezes.
> 
> Using Linux, bazzite distro. It happens on both my laptop and desktop. Desktop using KDE and laptop using Gnome. Also, my desktop is using the .appimage and my laptop uses the flatpak

Any idea how this happens?

**Comment by lparolari** [comment]
In my case, tabs freeze when I receive a message on WhatsApp web . It is open in a tab pinned in the Essentials.

I am using Zen Browser version 1.16.4b (Firefox 143.0.4) (64-bit).
I am on Bluefin (Version: 42.20251005.1). My desktop environment is Gnome 48. I am using Wayland.

**Comment by adamjcc** [comment]
Same for me, my browser tabs continue to freeze and the whole browser gets frozen. Only way to fix is to end task in Task Manager and relaunch Zen.
I find that especially happens when I have Essential tabs open, but sometimes also happens when I am not doing anything. 

I am using Zen browser version 1.17.7b (Firefox 145.0) (64-bit)

**Comment by airstrikeit** [comment]
why was this closed? I am having the same issue too so it doesnt seem to be solved

**Comment by dafzthomas** [comment]
Same having this issue. It seems to freeze for about 5 seconds, then it resumes with all of the clicks and keystrokes that I tried on it happening in sequence immediately. As if it wasn't frozen underneath.

**Comment by cerise-fox** [comment]
I have this exact same issue. It doesn't occur in Firefox.

**Comment by SaishoVibes** [comment]
this issue still persists
