### ISSUE TITLE
You Tube live streaming is not working

### ISSUE THREAD

**Issue by Naveenv01** [zen-browser/desktop#477]
### What happened?

Playing live feed is not working in ubuntu 24 04
![image](https://github.com/user-attachments/assets/d9676801-25a7-46d1-a02d-882aa328b84d)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.28 (2024-08-22)

### Severity impact

Critical

### What platform are you seeing the problem on?

Linux

**Comment by mauro-balades** [comment]
Could you try removing cache?

**Comment by zoovasoup** [comment]
> Could you try removing cache?

i have the same problem and removing cache doesn't fix the issue 

for me this issue also appear on twitch and instagram 
![Screenshot from 2024-08-24 21-15-28](https://github.com/user-attachments/assets/7d466022-b8a5-4e39-ad83-492e13a1a09d)
![Screenshot from 2024-08-24 21-14-53](https://github.com/user-attachments/assets/c7e96523-81ab-4bd2-83ce-6c855256c535)

im on nixos 24.11 with the same zen version i got from flatpak

**Comment by nx2k3** [comment]
even I am having the same problem on nixos 24.05

**Comment by TheBlueOompaLoompa** [comment]
I'm having what I assume is the same issue with regular video playback. It can be triggered by starting playback from any point in the video other than the start (occasionally this will work fine).

I've narrowed it down to broken AV1 decoding. Using this extension [Your Codecs](https://addons.mozilla.org/en-US/firefox/addon/your-codecs/) I was able to disable AV1 and go back to VP8/9 and it worked, better performance, and no playback errors.

I have attached YouTube debug playback info because it appears to include logging from the ffmpeg decoder.
[youtube_debug_info.txt](https://github.com/user-attachments/files/16737940/youtube_debug_info.txt)

**Comment by zoovasoup** [comment]
i tried @TheBlueOompaLoompa solution by disabling av1 with that plugin, and it only resolve the issue for youtube. but the problem still persisted on other platform

after some tinkering, it seems like installing [mediastreamer openh264](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=mediastreamer-openh264) fixed the issue across other platform for me 

i don't know the core issue why this thing is happening because i only have this problem on zen-browser and not on floorp or firefox

**Comment by TheBlueOompaLoompa** [comment]
That's strange, I checked and that was preinstalled for me on flatpak.

**Comment by HarryHeres** [comment]
Might be a long shot but have you tried installing/upgrading ffmpeg?

**Comment by MoAlHemyari** [comment]
I wrote about this in reddit [here](https://www.reddit.com/r/zen_browser/comments/1f7u8qk/youtube_playback_errors_page_loading_speed/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

I've tried to navigate the issue with the console of YT's page, in Zen & Librewolf (as an example), and this is what I've got:
1-  The console shows several warning logs related to media decoding, i.e `NS_ERROR_DOM_MEDIA_DECODE_ERR` and `avcodec_send_packet` error, & specific media resources (e.g., blob:https://www.youtube.com/...) fail to decode.

2- There is a warning log about WEBGL debug renderer: `WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER`.

3- Warnings indicate that error messages will be blank when `privacy.resistFingerprinting` it says `This error message will be blank when privacy.resistFingerprinting = true.  If it is really necessary, please add it to the whitelist in MediaError::GetMessage: NS_ERROR_DOM_MEDIA_DECODE_ERR (0x806e0004) - virtual MediaResult mozilla::FFmpegVideoDecoder<60>::DoDecode(MediaRawData *, uint8_t *, int, bool *, MediaDataDecoder::DecodedData &): avcodec_send_packet error: Unknown error occurred`.

**Comment by MoAlHemyari** [comment]
> I wrote about this in reddit [here](https://www.reddit.com/r/zen_browser/comments/1f7u8qk/youtube_playback_errors_page_loading_speed/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
> 
> I've tried to navigate the issue with the console of YT's page, in Zen & Librewolf (as an example), and this is what I've got: 1- The console shows several warning logs related to media decoding, i.e `NS_ERROR_DOM_MEDIA_DECODE_ERR` and `avcodec_send_packet` error, & specific media resources (e.g., blob:https://www.youtube.com/...) fail to decode.
> 
> 2- There is a warning log about WEBGL debug renderer: `WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER`.
> 
> 3- Warnings indicate that error messages will be blank when `privacy.resistFingerprinting` it says `This error message will be blank when privacy.resistFingerprinting = true. If it is really necessary, please add it to the whitelist in MediaError::GetMessage: NS_ERROR_DOM_MEDIA_DECODE_ERR (0x806e0004) - virtual MediaResult mozilla::FFmpegVideoDecoder<60>::DoDecode(MediaRawData *, uint8_t *, int, bool *, MediaDataDecoder::DecodedData &): avcodec_send_packet error: Unknown error occurred`.


[MY ISSUE FIXED IN 1.0.0-a.35 RELEASE]

**Comment by mauro-balades** [comment]
Thanks you good sir

**Comment by thiphariel** [comment]
Just a heads up, but the issue is back on 1.0.1-a.17 (probably earlier)

Edit : Ok my bad, it seems like it was more like a codec issue, I switch from `wireplumber` to `pipewire-media-session` and it seems ok for now :shrug:

**Comment by MuteSTEVE** [comment]
![Image](https://github.com/user-attachments/assets/26e055a2-f774-4f2c-a4c9-c1de03feb810)
![Image](https://github.com/user-attachments/assets/1a27f469-5e57-4061-829a-210da7d7a611)

Same problem for me, i even switched to pulseaudio and still facing the same problem
Not only on youtube, but some of my go-to streaming website also facing the same problem

But this problem doesn't appear on normal Firefox, everything is working normally
Maybe there's some problem with Zen-browser video codec? pardon me if i'm wrong
