### ISSUE TITLE
Closing a tab causes the tab bar to scroll to the top automatically.

### ISSUE THREAD

**Issue by sweetbbak** [zen-browser/desktop#4840]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

https://github.com/user-attachments/assets/3a39755e-e98c-4b36-943e-989199fc78b0

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.4b (Firefox 134.0.2) (64-bit)

### What platform are you seeing the problem on?

Linux (Tarball)

### Relevant log output if applicable

```shell

```

**Comment by sweetbbak** [comment]
Opening a new tab also doesn't jump to the bottom to focus it either.

**Comment by Greyti8888** [comment]
Seems like the problem is in ZenUIManager.mjs in updateTabsToolbar method. 
I think we can fix that by adding something like const scrollbarPosition = tabs.scrollTop before manipulations with tabs height and then setting tabs.scrollTop = scrollbarPosition at the end, after tabs.style.maxHeight is set.

**Comment by Arctomachine** [comment]
Not only current tab, but also closing any other tab with cross or context menu.

**Comment by Arctomachine** [comment]
And resizing browser window too

**Comment by Hate9** [comment]
Fixed in the newest version.

**Comment by sweetbbak** [comment]
Can confirm, I guess I will close this issue to get it out of the way.

**Comment by Arctomachine** [comment]
Problem still remains for window resize.
That happens primarily when moving browser between screens

**Comment by granpepito** [comment]
It still happens when you watch a video in full screen mode

**Comment by KacperMucha** [comment]
In my case, changing workspaces also scrolls back to the top.

**Comment by mr-cheffy** [comment]
Should be fixed now.

> In my case, changing workspaces also scrolls back to the top.

Id move this to a different issue
