### ISSUE TITLE
New Tab Button (and middle click on tab bar) does not work after opening customize toolbar

### ISSUE THREAD

**Issue by InterstellarOne** [zen-browser/desktop#5067]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Whenever I use the customize toolbar menu, even after I close it, the new tab button no longer works, as well, middle clicking on the toolbar doesn't open a new tab. I have zen.urlbar.replace-newtab turned off.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.5b

### What platform are you seeing the problem on?

Linux (AppImage)

### Relevant log output if applicable

```shell

```

**Comment by LordEnder-Kitty** [comment]
~I can't middle click on the tab bar to open a new tab now. Wasn't this update supposed to improve productivity? It just made it worse for those who don't like the new url bar thing. Please fix this!~

**Comment by InterstellarOne** [comment]
> I can't middle click on the tab bar to open a new tab now. Wasn't this update supposed to improve productivity? It just made it worse for those who don't like the new url bar thing. Please fix this!

I don't think this is related to the issue you are commenting on, and this bug has been fixed in 1.7.6b

**Comment by Anoms12** [comment]
'zen.urlbar.replace-newtab' to false in about:config to revert

The dev said he did it to speed up productivity and apparently Arc browser did a bunch of research on it, it's apparently the best option 🤷 Idk I like it.

**Comment by LordEnder-Kitty** [comment]
> > I can't middle click on the tab bar to open a new tab now. Wasn't this update supposed to improve productivity? It just made it worse for those who don't like the new url bar thing. Please fix this!
> 
> I don't think this is related to the issue you are commenting on, and this bug has been fixed in 1.7.6b

Oop. My bad. I wasn't in a pleasant mood upon writing and saw "middle click" and "new tab" in the title and jumped to conclusions. That's my bad.
Although, my issue is still not properly fixed. It works but just searches whatever is in my clipboard for some reason. lol

**Comment by JSGRD22** [comment]
I will be closing this issue since it is fixed. @LordEnder-Kitty, if you have an yet-unsolved issue, standard procedure: search to see if someone else is experiencing the same thing, if not, create a new bug report.

**Comment by LordEnder-Kitty** [comment]
> I will be closing this issue since it is fixed. [@LordEnder-Kitty](https://github.com/LordEnder-Kitty), if you have an yet-unsolved issue, standard procedure: search to see if someone else is experiencing the same thing, if not, create a new bug report.

https://github.com/zen-browser/desktop/issues/5113
