### ISSUE TITLE
New Tab Menu Not Displayed During Fullscreen Video Playback

### ISSUE THREAD

**Issue by elfoteo** [zen-browser/desktop#5229]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

**Description:**
When attempting to open a new tab while playing a video in fullscreen mode with the new feature enabled, the new tab menu does not appear, and the video continues playing uninterrupted. The expected behavior is for the browser to either exit fullscreen mode to display the new tab menu or remain in fullscreen while rendering the new tab menu overlay.

**Steps to Reproduce:**
1. Enable the new feature in Zen Browser settings. (it should be enabled by default with the latest update 1.7.6b)
2. Navigate to a website with video content.
3. Play a video and switch to fullscreen mode.
4. Attempt to open a new tab using the designated shortcut (CTRL+T).

**Expected Behavior:**
Upon initiating the action to open a new tab during fullscreen video playback, the browser should either:
- Exit fullscreen mode and display the new tab menu.
- Maintain fullscreen mode and render the new tab menu as an overlay.

**Actual Behavior:**
The new tab menu does not appear (I belive it is rendered in the background and not visible due to the video being in fullscreen), and the video continues playing in fullscreen mode without any indication of the menu being opened (if you type the keypresses get registered by the website not by the menu).

**Environment:**
- **Operating System:** *Arch Linux x86_64 Kernel: 6.13.1-arch2-1*
- **Extensions/Add-ons Installed:** *Dark Reader | uBlock Origin*

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.6b

### What platform are you seeing the problem on?

Other

### Relevant log output if applicable

```shell

```

**Comment by mr-cheffy** [comment]
Fixed in twilight!

**Comment by shailantani** [comment]
> Fixed in twilight!

Hi! I'm on Zen Twillight 1.8t (Firefox 135.0.1) (2025-02-23) (aarch64)
And this issue seems to exist. I'm on MacOS.

**Comment by elfoteo** [comment]
I am on Zen 1.7.6b (Firefox 135) on Linux and the issue still exists

**Comment by Cyliann** [comment]
Issue still exists on 1.8.2b (Linux)

**Comment by elfoteo** [comment]
Issue still exists in version 1.10b linux

**Comment by mennigju** [comment]
Issue still exists on 1.11.3b Windows 11

**Comment by elfoteo** [comment]
Yep, exists on Linux too

**Comment by mr-cheffy** [comment]
We know, it's on all platforms. Please avoid "this happens to me as well" comments, only the ones that proportionate something useful towards the issue are wanted. Thanks

**Comment by GevaX** [comment]
The issue is still happening on the latest version of Zen

**Comment by elfoteo** [comment]
Yep, confirmed

**Comment by ahmed-z0** [comment]
+1

**Comment by KitsuneKode** [comment]
Issue still persists on Linux

**Comment by elfoteo** [comment]
This issue was opened in February , could this issue get some attention?

**Comment by PeterCardenas** [comment]
Issue still persists on macos v1.14.11b

**Comment by elfoteo** [comment]
Yep, it still is

**Comment by BAT-FA** [comment]
Issue still persists on macos v1.16.1b

**Comment by AKP2401** [comment]
Issue still persits on Windows and Linux (CachyOS/Hyprland) on v1.16.2b.
