### ISSUE TITLE
New Tabs open in pinned tabs

### ISSUE THREAD

**Issue by BlueFox1616** [zen-browser/desktop#5264]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

What the tittle says pretty much the new version was supposed to fix it but it didnt

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.7t 

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output if applicable

```shell

```

**Comment by jobsrobson** [comment]
Same issue here (Windows, Zen 1.7.7t). New tabs open inside the Pinned Tabs container and also in the Essentials container. The issue started occurring after the update to 1.7.7t. 

https://github.com/user-attachments/assets/84678de4-c930-4055-b4a5-dea7de6f0d9d

**Comment by DavidScann** [comment]
Using a new profile works around this issue. However, I do not know what caused it in the first place.

**Comment by BlueFox1616** [comment]
fixed on the new updaate

**Comment by hugevibes** [comment]
Still happening for me as of 1.8.2b, also after reinstall and creating an entirely new profile.
