### ISSUE TITLE
System Crashing when opening pdf

### ISSUE THREAD

**Issue by Postboote1** [zen-browser/desktop#5507]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Hello
Today I wanted to upload an PDF file for School on a Website. However when loading this PDF file my whole system freezes (Linux Kernel 6..13.2), I can't even change tty. After doing a hard reset I tried opening the PDF File with the Browser without uploading it, same issue. Also trying out a different file lead to the same outcome. 
But when I use google-chrome everything functions fine.

System:
Linux 6.13.2
Nixos 25.05
Installed via Flatpak

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.7.6b

### What platform are you seeing the problem on?

Linux (Flatpak)

### Relevant log output if applicable

```shell
I don't know which logs I should post. If you need any just ask.
```

**Comment by Postboote1** [comment]
Resolved it by allowing Zen to access the Homefolder trough Flatseal. 
But it is still weird that this caused my whole system to freeze.

**Comment by Marwan-Mamdouh** [comment]
i have the same problem and i am running 
##System:##
Linux 6.13.4
fedora 41
Installed via Flatpak
##Version##
1.8.2b

**Comment by Marwan-Mamdouh** [comment]
> Resolved it by allowing Zen to access the Homefolder trough Flatseal. But it is still weird that this caused my whole system to freeze.

I tried it but still the same problem even after installing version 1.9b

**Comment by zen-browser-auto** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=System%20Crashing%20when%20opening%20pdf%0A
