### ISSUE TITLE
[Twilight 1.8] Sidebar is misalligned upon initlialization

### ISSUE THREAD

**Issue by gordonn** [zen-browser/desktop#5560]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

![Image](https://github.com/user-attachments/assets/f0758419-27df-45d9-a740-c194137c2d60)

It happens for a brief period.

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.8t

### What platform are you seeing the problem on?

All platforms

### Relevant log output if applicable

```shell

```

**Comment by mr-cheffy** [comment]
Should be fixed once the latest build finishes 👍🏽

**Comment by gordonn** [comment]
@mauro-balades Can still see the misaligned UI for a brief period during initialization but is barely noticeable
