### ISSUE TITLE
Floating URL bar appears way off the expected position

### ISSUE THREAD

**Issue by neilio** [zen-browser/desktop#5609]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

Not sure when this started, but when I put focus into Zen Twilight's address bar and start typing, the bar and autocomplete dropdown appear in the bottom right corner of the screen. I turned off Zen Mods, thinking it was a conflict, but the issue remains.

I can't reproduce this on the main app.

![Image](https://github.com/user-attachments/assets/514fd1e7-c862-4c70-9ba9-78ba834ae516)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.8t

### What platform are you seeing the problem on?

macOS - aarch64

### Relevant log output if applicable

```shell

```

**Comment by belenos** [comment]
Same here. I am on Arch Linux with Gnome (Wayland). It happens no matter the size of the window. 

I tried to change the URL bar to normal behavior until a fix is released. But then I found out if the toolbar is hidden while in compact mode, the URL bar looks like this, and you can't see what is being typed.

![Image](https://github.com/user-attachments/assets/b2cd54d3-14dd-4505-aa65-a76880ce24ae)

**Comment by barman-peppermint** [comment]
I am having the same issue, it is so irritating, for me it only happens when we are in the compact mode.

System - Debian 22.0

![Image](https://github.com/user-attachments/assets/9b6886f0-d4f6-420f-a4f0-0961d2f7f4cf)

**Comment by belenos** [comment]
Ok, so I did some tests, [as recommended here](https://www.reddit.com/r/zen_browser/comments/1iwv70n/comment/mehbqxc/), with my current profile and a new, empty one.

In both profiles, the issue occurs only when the browser layout is set to a collapsed toolbar with compact mode enabled and configured to hide the toolbar. If the mode is set to hide only the sidebar or both the toolbar and sidebar, the issue is not reproducible. In all other layout combinations, the URL bar is displayed correctly in the center of the window.

**Comment by MuntasirSZN** [comment]
Me also. Archlinux. Goes to right bottom. Irritating. As I need to use stable no matter what, I have downgraded to 1.7.6b for some time. I will upgrade again. As @belenos said, thats basically the issue.

**Comment by aswinbennyofficial** [comment]
![Image](https://github.com/user-attachments/assets/0ce76d14-0030-4ca9-b02e-212b61b11d7c)

This issue happens to me only when tool bar is hidden on compact mode.

**Comment by Radrahil** [comment]
Same situation on here, also on arch. Is there a specific setting for its position?
Also, The position is the exact same on hide both as it is in hide top bar. Maybe that's where the problem is? It's setting the position based on hide top bar?

**Comment by MuntasirSZN** [comment]
Is it fixed in 1.8.1b?

**Comment by belenos** [comment]
> Is it fixed in 1.8.1b?

I don't think it does, or mods would have closed this thread by now.

**Comment by aswinbennyofficial** [comment]
> Is it fixed in 1.8.1b?

Looks like issue is fixed for me on `1.8.1b`

**Comment by MayiVT** [comment]
same issue on Windows 11 1.8.1b

![Image](https://github.com/user-attachments/assets/1c5dae59-8ded-47e3-ac41-a639026ab51b)

**Comment by WithoutAName25** [comment]
> Is it fixed in 1.8.1b?

I had the same issue on Arch when the url bar was hidden in compact mode and for me it is fixed now

**Comment by Radrahil** [comment]
It is fixed now.

**Comment by g-flame** [comment]
### What happened?

## 📝 Description  
After updating to Zen **v1.8b** on **Windows**, I've encountered two major UI issues related to opening new tabs (`Ctrl + T`) and new tab windows:  

### **🔍 Observed Issues:**  
1. **Off-Position UI Elements on `Ctrl + T`**  
   - Pressing `Ctrl + T` to open a new tab sometimes causes UI elements to be misaligned or appear in the wrong position.  
   - This makes navigation difficult and disrupts the user experience.  

![UI Bug](https://github.com/user-attachments/assets/576c2a74-86c7-47bf-83cc-a9efcc2cb3fb)

2. **Blank Screen in New Tab Window**  
   - When opening a **new tab window**, instead of displaying the expected interface, Zen sometimes fails to open the new window properly.  
   - If the window is closed, a **gray blank screen** appears instead of returning to the main interface.  
   - Example:  
     ![Blank Screen](https://github.com/user-attachments/assets/4769c1af-512b-4ad8-abfe-1b8d1e40eb39)  

### **🛠 Steps to Reproduce:**  
1. Ensure Zen is updated to **v1.8b** on **Windows**.  
2. Open Zen and press `Ctrl + T`.  
   - Observe if any UI elements are out of position.  
3. Open a **new tab window** instead of a normal tab.  
   - Notice that it sometimes **doesn't open properly** and may **close immediately**.  
4. If the new window fails, close it and check if a **gray blank screen** appears.  

### **✅ Expected Behavior:**  
- Pressing `Ctrl + T` should open a new tab without UI glitches.  
- A new tab window should open properly and display the expected interface.  
- Closing a failed tab window should **not** leave a blank screen.  

### **❌ Actual Behavior:**  
- `Ctrl + T` causes UI elements to appear in the wrong position.  
- Opening a new tab window sometimes **fails, closes, or results in a gray blank screen**.  

## **📢 Zen Dev Team – Please Investigate!**  
This issue makes it difficult to use multiple tabs efficiently. Let me know if you need logs or additional details to help troubleshoot. Thanks in advance! 🙏  
---

### Some info

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
Version 1.8.1b (64-bit)
Windows

**Comment by g-flame** [comment]
> It is fixed now.

## well ...
- no in new version still there 
- in the change log they mentioned this 
 > Fixed floating urlbar when entering compact mode using double toolbars 
### but not fixed 
![Image](https://github.com/user-attachments/assets/a1f09a60-78df-40e7-93f7-b8419fda9790)

**Comment by MayiVT** [comment]
> same issue on Windows 11 1.8.1b
> 
> ![Image](https://github.com/user-attachments/assets/1c5dae59-8ded-47e3-ac41-a639026ab51b)

Issue still there in 1.8.2b

**Comment by neilio** [comment]
> 2. **Blank Screen in New Tab Window**
>    
>    * When opening a **new tab window**, instead of displaying the expected interface, Zen sometimes fails to open the new window properly.

Hey, please open a separate ticket for different bugs so the original one can be tracked properly.

**Comment by sschzrk** [comment]
I rolled back to [v1.7.6b](https://github.com/zen-browser/desktop/releases/tag/1.7.6b). On that release the toolbar is working for me

**Comment by MuntasirSZN** [comment]
> I rolled back to [v1.7.6b](https://github.com/zen-browser/desktop/releases/tag/1.7.6b). On that release the toolbar is working for me

Same for me.

**Comment by neilio** [comment]
I managed to get it to work on 1.8.2b, although I'm not 100% sure what I did to fix it. I mostly disabled or uninstalled any mod that affect the URL bar or dropdown and that seemed to fix the issue. Now the address bar/autocomplete appears in the middle of the browser window, which I believe is the correct location.

**Comment by EnzoPV25** [comment]
> I managed to get it to work on 1.8.2b, although I'm not 100% sure what I did to fix it. I mostly disabled or uninstalled any mod that affect the URL bar or dropdown and that seemed to fix the issue. Now the address bar/autocomplete appears in the middle of the browser window, which I believe is the correct location.

Same here, I can't find the name of the mod I used but it was affecting the url bar. Removing it fixed it (however couldn't find it to reinstall to see the bug coming back because I couldn't remember the name -_-')

**Comment by MuntasirSZN** [comment]
anyone who is using a mod, that modifies toolbar or similar things, go to settings, zen mods, check for updates, wait a bit, when showing successfully, close and reopen zen, it will fix the off pos problem.

**Comment by EnzoPV25** [comment]
I found back the plugin that used to break it : Floating URLbar (which seems to have been removed from the store). I guess it's no longer usefull since it's native in zen browser.

**Comment by sschzrk** [comment]
I've removed all mods (none were toolbar-specific) and restarted Zen, but the problem persisted.

I then uninstalled Zen and removed the following folders:

*   `C:\Users\Me\AppData\Local\zen`
*   `C:\Users\Me\AppData\Roaming\zen`

Afterward, I installed the latest version of Zen. The toolbar is now working again. I reinstalled all my previous mods, and the toolbar continues to function perfectly.

**Comment by MuntasirSZN** [comment]
Mine is fixed. None Were causing issues. I just didn't update my mods.

**Comment by g-flame** [comment]
mine is fixed too but this still exists with closing the new tab tab 

![Image](https://github.com/user-attachments/assets/f0864c4d-7c7d-4545-a35d-eea1dcdc2096)

**Comment by sschzrk** [comment]
I've noticed a change: the URL bar is now hidden as soon as the flying URL bar opens. I believe previously, both were visible simultaneously.

![Image](https://github.com/user-attachments/assets/bc00cf7c-df38-43b4-b885-0aec6baa0327)

**Comment by neilio** [comment]
> mine is fixed too but this still exists with closing the new tab tab

File a new bug on that issue as it's not related to this one. The chances of it getting fixed are low if it's in another bug's comments.

**Comment by neilio** [comment]
If you still have this problem, make sure any mods that affect the URL bar are disabled, or even better, uninstalled. I have a suspicion that turned off mods are still somehow affecting the UI as I was able to reproduce this with the mod feature turned off. It wasn't until I went through and uninstalled all of the URL bar mods that it was fixed.

**Comment by ziewenn** [comment]
> If you still have this problem, make sure any mods that affect the URL bar are disabled, or even better, uninstalled. I have a suspicion that turned off mods are still somehow affecting the UI as I was able to reproduce this with the mod feature turned off. It wasn't until I went through and uninstalled all of the URL bar mods that it was fixed.

Yeah i had the Super Url  Bar mod installed and enabled, it got fixed when i disabled it.

**Comment by MuntasirSZN** [comment]
I didn't had to remove any mod, I just updated them.

**Comment by Romanhan** [comment]
I've deleted "Floating url bar" mod and that helped me.

**Comment by plutonium-239** [comment]
@MayiVT your issue is because the mod "Floating URL Bar" got broken with the 1.8.xb updates, so the mod author will have to fix this.

**Comment by JSGRD22** [comment]
Does disabling the mod(s) fix the problem for everyone?

**Comment by Raekh** [comment]
No mods installed, still reproduce the problem.
For me it clips into the top of the browser.
I have a g9 screen (5120x1440), and when the window is reduced to a standard ratio, the popup appears in a more logical position.

![Image](https://github.com/user-attachments/assets/510b144b-1385-4c50-9cc0-f31c4344559e)
![Image](https://github.com/user-attachments/assets/76a0cbbc-7b1b-467d-92f6-99ad4b4bbe8b)
![Image](https://github.com/user-attachments/assets/8e852022-a469-4303-8bed-edd5cafe4a6e)
![Image](https://github.com/user-attachments/assets/4ff5ae05-7500-4e6b-9fe0-3a6f4630e67c)

**Comment by zen-browser-auto** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=Floating%20URL%20bar%20appears%20way%20off%20the%20expected%20position%0A
