### ISSUE TITLE
Sideberry bug in new v1.8b

### ISSUE THREAD

**Issue by DRYN07** [zen-browser/desktop#5653]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

I'm not sure if this error is related to the Zen browser or Sideberry, but the new 1.8b update makes Sideberry unusable. If I open a new tab in any web panel, all tabs disappear and I can't open new tabs anymore.

I updated everything, both the browser and Sideberry, and deleted cookies and all data as well.

If I restore 1.7b, everything works properly.

I wrote on the addon's GitHub page as well, but since I don't know what the error belongs to, I thought I'd mention it here too.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.8b

### What platform are you seeing the problem on?

Windows

### Relevant log output if applicable

```shell

```

**Comment by bachrc** [comment]
On Linux here , and to some point when I open a new tab, it doesn't even show in Sidebery. Soon after, there's a CPU spike and Zen becomes unresponsive

**Comment by AndehCreates** [comment]
Im leaning more towards sideberry breaking because of zen updates
https://zen-browser.app/release-notes/

**Comment by adam2am** [comment]
Same, also when switching between different workspaces, different tabs now would not be visible in different sideberry workspaces (unless you re-open the sideberry fully) but then other tabs from previous workspace would dissapear

**Comment by lmBored** [comment]
Same Im also having this error

**Comment by lmBored** [comment]
@DRYN07 how did you restore zen to version 1.7b?

**Comment by adam2am** [comment]
> [@DRYN07](https://github.com/DRYN07) how did you restore zen to version 1.7b?

Check the github releases, the 1.7.6b works fine with tabs

**Comment by bachrc** [comment]
Yup, stuck with 1.7.6 for now. Tree style tabs in Sdebery are way too useful for me to get back haha

**Comment by zen-browser-auto** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=Sideberry%20bug%20in%20new%20v1.8b%0A

**Comment by bachrc** [comment]
No problem, I did not kept updated the issue but the bug is fixed now!

**Comment by adam2am** [comment]
> No problem, I did not kept updated the issue but the bug is fixed now!

@bachrc , okay, you totally jebaited me! I updated the browser, but the bug is still present when trying to manage multiple workspaces, and old tabs are acting weirdly/have to reopen the sideberry cuz its not showing some tabs. Did you have to reopen everything from scratch? Because even when I try to do it, it's still super weird and inconsistent

**Comment by bachrc** [comment]
Wait what? I can assure you it's been a few versions that the bug has been fixed for me, that Sidebery crashes, becomes inconsistent with real tabs and stuff
Now it works well on my end, but maybe you talk about something different?

I only have one workspace, maybe that's the difference?

**Comment by adam2am** [comment]
Yeah, unfortunately, there's still a bug with multiple workspaces+sideberry.
Or some new way of handling it under the hood, idk
