### ISSUE TITLE
URL bar does not hide completely in compact mode

### ISSUE THREAD

**Issue by belenos** [zen-browser/desktop#5755]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

A bit of the bottom of the URL bar is still visible in compact mode (collapsed toolbar). It's possible to fix it by changing the browser layout and back, but it's not permanent. The problem persists after launching the browser again. 

https://github.com/user-attachments/assets/f941219b-2edd-47f7-828e-054812c89fd9

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.8.1b

### What platform are you seeing the problem on?

Linux (Tarball)

### Relevant log output if applicable

```shell

```

**Comment by JSGRD22** [comment]
This should be fixed in 1.8.2b

**Comment by UserJHansen** [comment]
> This should be fixed in 1.8.2b

I'm still receiving this issue

![Image](https://github.com/user-attachments/assets/108bd9f2-9ddf-494e-80a2-73502e15824c)

**Comment by belenos** [comment]
It's still happening in version 1.9b, but less frequently now. I've tried to find a way to reproduce, but it still seems random.

https://github.com/user-attachments/assets/559aa40f-1b6b-4625-8308-3f0ce9008919

**Comment by zen-browser-auto** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=URL%20bar%20does%20not%20hide%20completely%20in%20compact%20mode%0A
