### ISSUE TITLE
Searchbar isnt center and a bit hidden on widescreen

### ISSUE THREAD

**Issue by t1gu1** [zen-browser/desktop#5880]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

I'm on a odyssey G9 
32:9 ratio
5120 x 1440

As you can see, the "search" dialog is hidden at the top and not center.

I think it is not center because it doesn't consider the side bar at the right.

But for the hidden part at the top, it purely related to the wide screen.
If i size it down in to "normal ratio" it hide less and less in the top until i reach a 16:9 ratio.

![Image](https://github.com/user-attachments/assets/dd119c78-4829-46b1-a7ea-a81afbb0746a)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.8.2b

### What platform are you seeing the problem on?

Linux (Flatpak)

### Relevant log output if applicable

```shell

```

**Comment by Stocki10** [comment]
I inquired the same Problem but resizing the Window sadly didn't fix it.

![Image](https://github.com/user-attachments/assets/b001f10b-5a4e-41a4-b82b-29056ebb1b02)

**Comment by ScreepCode** [comment]
This is a demonstration of resizing Zen and seeing the issue with hiding the searchbar on widescreen
https://github.com/user-attachments/assets/8b660c61-1bc6-460a-8ec8-b615f172bcd9

Sorry for the very low resolution video, but maybe this helps (the file was to big for GitHub Comments)
The problem seems to be related to the heigth of the searchbar but more width the application ratio to which this height seems to be cuppled. 

My Screen: 
Philips Evnia 49M2C8900L/00
32:9 ratio
5120 x 1440

Zen-Version: Version 1.8.2b (64-bit)

**Comment by ScreepCode** [comment]
@t1gu1 

On my side the issue is resolved with update to Version 1.9b
Maybe give it a try :)

**Comment by Stocki10** [comment]
Sadly its still not working it just shifted 😥

![Image](https://github.com/user-attachments/assets/d42f7850-30b7-464d-b1b2-77b5667cbb6c)

**Comment by zen-browser-auto** [comment]
## Closing this issue as part of a repo cleanup

Due to technical-debt we had in the past, we are currently clearing out old, duplicate, stale, and non-actionable issues to improve issue tracking and make it easier to focus on fixing real bugs.

If this issue is still relevant, please open a new issue using our updated issue template, which will help us categorize and address it more efficiently.

Thanks for your understanding and for helping us improve the project! 🚀

This issue can be reopened at: https://github.com/zen-browser/desktop/issues/new?template=bug_report.yml&title=Searchbar%20isnt%20center%20and%20a%20bit%20hidden%20on%20widescreen%0A
