### ISSUE TITLE
URL Bar only showing up when typing.

### ISSUE THREAD

**Issue by 0PandaDEV** [zen-browser/desktop#6369]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.

### What happened?

When I want to open a new tab or edit the URL of the current tab using the shortcuts CTRL + T and CTRL + L the URL bar only shows up when I start typing instead of showing up instantly.

https://streamshare.wireway.ch/download/cjdl5qfl.mp4

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

all versions

### What platform are you seeing the problem on?

Windows, macOS - aarch64

### Relevant log output if applicable

```shell

```

**Comment by 4fuu** [comment]
I have the same bug, is someone going to deal with it?

**Comment by 4fuu** [comment]
@0PandaDEV 
I've noticed that this issue seems to have been fixed on [Zen Twilight](https://zen-browser.app/download?twilight), and you can also check and verify it.

**Comment by 0PandaDEV** [comment]
I am on Zen Twilight already and there are no new updates and the issue is still here.

**Comment by 4fuu** [comment]
Really? This issue might be caused by the overlap of old and new configurations. Have you ever downloaded Zen instead of Zen Twilight? If not, you can download it to verify if the problem is due to leftover old data. Check if the newly downloaded browser can pop up windows normally. Here, I just downloaded Zen Twilight, so I haven't observed this issue, but my Zen browser has had this problem for several versions.

**Comment by 0PandaDEV** [comment]
I found the issue. When I create a completely new browser profile regardless if it's stable or twilight it does actually work, so the issue is gone, but as soon as I log into my Firefox account it comes back.
However, if you log out again, the issue still persists.

### Steps to Reproduce
1. Create new profile or reinstall browser
2. Try editing a URL or creating a new tab (The issue should be gone)
3. Log in using a Firefox account
4. The issue is back

**Comment by 4fuu** [comment]
Oh, that issue is consistent with #5410

**Comment by 4fuu** [comment]
@mauro-balades  Hi there!   

Thanks for your work on Zen! I'm experiencing an issue related to #6369 and #5410 where the address bar overlay doesn't appear when triggering a new tab action while logged into a Firefox account.   

Steps to reproduce:    

    Log into Firefox account  
    Press CTRL + T or click the "+" button to create a new tab  
    Expected:  Address bar overlay appears immediately  
    Actual:  Overlay only appears after typing characters (e.g., "g" for Google search)
     

This behavior doesn't occur in:   

    When logged out of Firefox account  
    Fresh browser profiles

Would you have any insight into what might be causing this conflict?

**Comment by mr-cheffy** [comment]
![Image](https://github.com/user-attachments/assets/96444b0e-41e0-483c-a877-981fee363783)

Hi! This is because you have "shortcuts" disabled in your search preferences
