### ISSUE TITLE
New Tab Opens in Current Tab Instead

### ISSUE THREAD

**Issue by 0Ky** [zen-browser/desktop#7010]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

1. When using modifier keys (`Ctrl`/`Alt`/`Shift`) and pressing `Enter` in the URL address bar while an open tab is selected, the current tab switches to the selected tab instead of opening the webpage in a new tab.

2. When holding down the `Alt` key and pressing `Enter` in the URL address bar while a new website URL or a search term is typed, the active tab is replaced with the opened webpage instead of opening it in a new tab.

It was quite frustrating when I encountered this bug organically.

#### 1: Tab Switched Instead of Opening in New Tab

1. In a new tab open any website.
2. Create another new tab and open any website.
3. Use `Ctrl + T` or `＋ New Tab` button to focus the URL address bar.
4. Type `%` and press the spacebar key.
5. Select an open tab using the down arrow key.
6. Hold down any one modifier key and press enter (`Ctrl + Enter`, `Alt + Enter` or `Shift + Enter`).

#### 2: Active Tab Replaced Instead of Opening in New Tab

1. In a new tab open any website.
2. Use `Ctrl + T` or `＋ New Tab` button to focus the URL address bar.
3. Type a website URL or a search term.
4. Hold down the `Alt` modifier key and press enter (`Alt + Enter`).

### Actual Result

- 1\. The tab will switch to the selected open tab.
- 2\. The current active tab will be replaced by the opened webpage.

### Expected Result

- 1\. Holding down any one modifier key and pressing enter should stop the tab from switching and instead open in a new tab.
- 2\. The webpage should be opened in a new tab.

### Video Demonstration

https://github.com/user-attachments/assets/b8a85b54-d289-497b-9d64-2ada8bbd09a0

### Version

1.11.2t

### What platform are you seeing the problem on?

Linux (AppImage), Linux (Flatpak), Linux (Tarball), macOS - aarch64, macOS - Intel, Windows - x64, Windows - aarch64, Other

### What component is this issue related to?

Tabs

### Relevant log output if applicable

```shell

```

**Comment by Propheticus** [comment]
So you're using % in the URL bar that normally allows selecting and switching to already opened tabs, but then press `Ctrl` to take that tab's URL and create a new tab from it. 

It says "Switch to tab", but then on pressing `Ctrl` it no longer does (correct)

https://github.com/user-attachments/assets/ebbeb6f9-f9c6-4546-b78f-b055bdb625f5

... but it still switches instead of opening a new tab (incorrect)

I can reproduce, also on Twilight. Retesting in Firefox leads to expected result: Ctrl-key modifier causes a new tab with the URL copied from the other tab.

**Comment by 0Ky** [comment]
@Propheticus That's correct, it's also not limited to `Ctrl`, but other modifier keys like `Shift` and `Alt` too. I've updated the OP with clearer explanation and steps to reproduce, there's also another similar issue:

> When holding down the <ins>Alt</ins> key and pressing <ins>Enter</ins> in the URL address bar while a new website URL or a search term is typed, the active tab is replaced with the opened webpage instead of opening it in a new tab.

Also, the expected results align with the same behavior in Firefox.

**Comment by mr-cheffy** [comment]
Should be fixed now with https://github.com/zen-browser/desktop/commit/964dedba0f58818c03926acd68c6dbe0e6befab6#diff-bcc38a6003fd5dd5c026b5ffe6e3bc00896f05aa37525b791a26994f884c6a0d 👍🏽

**Comment by 0Ky** [comment]
@mauro-balades This isn't fixed, who's performing the tests before you merge and close these issues ?

**Comment by mr-cheffy** [comment]
My bad, I thought it was referring to a different issue

**Comment by 0Ky** [comment]
@mauro-balades To be fair from OP you've fixed `2: Active Tab Replaced Instead of Opening in New Tab`, but not the other one:

> #### 1: Tab Switched Instead of Opening in New Tab
>
> 1. In a new tab open any website.
> 2. Create another new tab and open any website.
> 3. Use `Ctrl + T` or `＋ New Tab` button to focus the URL address bar.
> 4. Type `%` and press the spacebar key.
> 5. Select an open tab using the down arrow key.
> 6. Hold down any one modifier key and press enter (`Ctrl + Enter`, `Alt + Enter` or `Shift + Enter`).

Also, you've killed the __default behavior__ of [`Shift + Enter`](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs) that's suppose to open the tab in a new window and [`Ctrl + Enter`](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_miscellaneous) that adds a `.com` to the searched address.
* Tests was done building commit dd005b31a460e21e1c6d9a35fce39aa0961aaff9 from source in Linux.

> I thought it was referring to a different issue

Both issues are related to holding down a `modifier key` while pressing `Enter` in the address bar.

In the first case, the modifier key affects how a selected tab behaves and in the second, the modifier changes how a typed URL or search opens.

Since the root cause is the modifier key changing how the browser handles keyboard shortcuts, just in slightly different contexts. I thought these shouldn't be treated as separate issues.

**Comment by Propheticus** [comment]
Maybe interesting observation:

- When using `Ctrl + T` on this github page and then entering search term 'good' > `Ctrl + Enter` (to add .com) : It opens a copy of this tab's URL in a new tab.

**Comment by 0Ky** [comment]
@mauro-balades I believe this issue needs to be reopened.

**Comment by 0Ky** [comment]
The issue still persists in the latest version 1.13t (Firefox 139.0.1) (2025-05-29) (64-bit) (build 20250529110242).

1. Using `Shift + Enter` in the address bar does not open the _search_ or _address_ in a new window.
2. Using `Shift + Enter` in the address bar does not open the _address_ in the current tab when an existing tab (Switch to tab) is selected.
3. Using `Ctrl + Enter` in the address bar does not open the _address_ in the current tab when an existing tab (Switch to tab) is selected.
4. Using `Alt + Enter` in the address bar does not open the _address_ in the current tab when an existing tab (Switch to tab) is selected.
