### ISSUE TITLE
Web pages are blurry/fuzzy on macOS, but only when Zen is fullscreen

### ISSUE THREAD

**Issue by rewgs** [zen-browser/desktop#707]
### What happened?

On macOS, if Zen is fullscreen (occupying its own Space, achieved by clicking the green button in the top left) or maximized (as large as the screen without occupying its own Space, achieved by Option+clicking the green button in the top left), the page is blurry. Any other size, the page is perfectly crisp.

For reference, I'm on a 32" Dell 4k display.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.29

### Severity impact

Medium

### What platform are you seeing the problem on?

macOS - aarch64

**Comment by DD3Boh** [comment]
The same thing happens for me on KDE Wayland. The page is blurry only when the window is full screen'd.
I think it could be related to fractional scaling, since that's known to give issues similar to this one.

**Comment by rewgs** [comment]
Yup, I think you're right. I tested on my Linux machine running Hyprland, and at 2x zoom it's fine, but any fractional scaling is blurry. I'm not surprised Wayland has that issue, but I am surprised that macOS is experiencing it.

**Comment by amtoaer** [comment]
This issue doesn't occur on my aarch64 Mac with 27" 4K display. I'm currently on version a.30.

**Comment by mauro-balades** [comment]
Close?

**Comment by rewgs** [comment]
Nope, still having the issue with a.30 on macOS. Specifically, an M1 MacBook Air running Sonoma 14.6.1. My display is 3840x2160, but is scaled to look like 3008x1692.

**Comment by mauro-balades** [comment]
Does this still happen?

**Comment by rewgs** [comment]
Still happening on macOS, 1.0.0-a.33.

**Comment by pvharmo** [comment]
Installed Zen (Flatpak) today on my Ubuntu 24.04 with fractional scaling and I'm getting this issue too. However, I noticed that the text becomes clearer if I highlight it and remains clear afterwards. The same thing happens when I hover buttons.

**Comment by morinted** [comment]
I'm also on macOS - aarch64, when I double-click to expand to fill the screen, I see the text blurring issue. It's not present in Firefox.

Hovering with the mouse does make the text clear again.

**Comment by bravecrayon** [comment]
Also reported in #440

**Comment by rve0** [comment]
I have a hypothesis in mind that this is a font rendering issue. This is mainly speculation, so I'd appreciate it if anyone could check if images are blurry too.

**Comment by bravecrayon** [comment]
@rve0 
I thought this was fixed as part of #440. I'm running 1.0.1-a.12 and it's looking good to me. Images and text appear sharp even in full screen.

**Comment by timolins** [comment]
I'm still experiencing full-screen rendering issue on 1.0.1-a.14:

https://github.com/user-attachments/assets/c99c51f7-445b-49b6-925a-5551f3cab020

In the screen recording you can see that it affects both fonts and images.

**Comment by littleblack111** [comment]
hmm... seem like a regression, before yesterday's update i dont have this issue...

im using arch btw and installed from aur.

also i dont think it's necessarily full screen related as it happens when its tiled(im on hyprland btw), and if i float it and make it smaller a little bit, it will disappear. 

also it only affect web pages, the toolbar, sidebar are all fine

**Comment by harryheres** [comment]
Can confirm, happens when the window is maximized/fullscreen only on 1.0.1-a.13 and a.14. Anything rendered in the actual html content area is blurry (even settings and such, not just sites). Didn't experience this on previous versions.

**Comment by harryheres** [comment]
Closing in favor of #2375
