### ISSUE TITLE
Authentication on sites via a certificate (such as a Smart Card) broken on macOS since 1.10b

### ISSUE THREAD

**Issue by chopstix2594** [zen-browser/desktop#7144]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

Smart Card authentication seems to have stopped working in 1.10b, and remains nonfunctional in 1.10.3.b. Reverting to 1.9.1b fixed the issue, and it also functions properly on Firefox 136.0.4.

The following message is displayed, when in previous versions or Firefox the prompt for the Smart Card PIN would appear:

Secure Connection Failed

An error occurred during a connection to . SSL peer was unable to negotiate an acceptable set of security parameters.

Error code: SSL_ERROR_HANDSHAKE_FAILURE_ALERT

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.

[Learn more…](https://support.mozilla.org/1/firefox/1.10b/Darwin/en-US/connection-not-secure)

### Version

1.10.3b

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Security

### Relevant log output if applicable

```shell

```

**Comment by CarlosML27** [comment]
Hi there! I’m experiencing what appears to be the same issue, but on Linux (Fedora Workstation 41) using the Flatpak version.  I’m trying to use a YubiKey 5 NFC configured with a digital certificate (Spanish government-issued .p12, imported via OpenSC into the PIV slot). The PKCS#11 module (`opensc-pkcs11.so`) is correctly loaded and visible in the browser via: `Settings → Privacy & Security → Security Devices`.

The module shows up fine, but the “Log In” button is always greyed out, making it impossible to authenticate or view the certificate.

The .so file is fully accessible inside the Flatpak sandbox (~/.pkcs11/opensc-pkcs11.so) and Flatpak has full permissions (`flatpak override app.zen_browser.zen --device=all --filesystem=$HOME/.pkcs11:ro --talk-name=org.freedesktop.pcsc-lite`). `pcscd` is running and correctly detects the YubiKey (using `opensc-tool -l` for example), and the same PKCS#11 setup works perfectly in Firefox. This strongly suggests the problem lies in how Zen Browser handles the PKCS#11 login process (either a regression or missing some NSS support).

If helpful, I can share my profile config, modutil outputs or any specific logs you guys need. Thanks in advance, and let me know if I can help with any debugging.

**Comment by steve28** [comment]
I am seeing this too on 1.12.1b (Firefox 138.0.1) (aarch64).  Bummer too, because needed for work

**Comment by shokinn** [comment]
This issue is still relevant and 1.12.10b is affected

I've tested it with Nexus Smart ID, either with a physical and virtual Smart Card.

Physical:
* Card reader: Gemalto USB SmartCard Reader
* Smart card: CardOS V5.3

Virtual:
* basically certificates, but the Smart ID App exposes them as a Smart Card to the system

**Comment by shokinn** [comment]
The issue still persists in 1.14.5b.

**Comment by evevseev** [comment]
1.14.11b — issue is present

**Comment by Surrylic** [comment]
I am currently experiencing this issue on MacOS with version 1.15t, but not Windows with 1.15t.

**Comment by samwick07** [comment]
I currently am experiencing this issue on Fedora 42, Zen Version 1.15.5b.

**Comment by kmandarin-orange** [comment]
I can also confirm that I'm running into this issue on Fedora Workstation 42, Zen version 1.15.5b, with the Flatpak package. I'm using a Yubikey Security Key C NFC.

**Comment by mfx00** [comment]
Can confirm I’m running into this issue with version 1.15.5b flatpak and AppImage versions on Ubuntu 24.04, Project Bluefin, Bazzite, and RHEL 9.6. I’m using a smart card.

**Comment by evevseev** [comment]
1.16.4b — no change.

Interestingly, when I build the application locally by following the steps in the [contribution guide](https://docs.zen-browser.app/contribute), it works as expected.

**Comment by Surrylic** [comment]
Weird - I see the same thing. When building the application myself the smart card authentication works properly.

**Comment by Surrylic** [comment]
For anyone still wanting to use Zen with a Smart Card (on Mac, at least), if you run the two below commands in Terminal it fixes the smart card issue. This will probably break on updates, and unfortunately it breaks Apple's iCloud Passwords extension (which I rely on). 

```
sudo xattr -rc /Applications/Zen.app
sudo codesign --force --deep --sign - /Applications/Zen.app
```

Re-signing the app ad-hoc removes Apple’s original signature, notarization, and hardened runtime enforcement. This reduces macOS-level security guarantees and breaks Apple-trusted integrations (like iCloud Passwords), but it allows smart card access that appears to be blocked in the official signed build. The underlying browser security model remains unchanged; the difference is OS-level trust and entitlement enforcement.

**Comment by Surrylic** [comment]
Yes this is still an issue. Authentication is still broken.

**Comment by mr-cheffy** [comment]
Please let me know if its fixed in `1.20.1b`! As firefox fixed some smart card issues within that release.

**Comment by Surrylic** [comment]
I’m still getting the same error when attempting to access sites that require smart card authentication. I’m not a SME in anything related to this, but for what little it’s worth I don’t think this is a Firefox issue… I can access these same sites in Firefox and Floorp (Firefox-based browser) that I’m unable to get to from Zen.

**Comment by spettinichi** [comment]
Also having this issue. I am on MacOS 26.6.2 and Zen Version 1.21.14b (64-bit). It also works perfectly fine for me in Firefox. This is the major blocker from rolling out Zen as the preferred browser at my company
