### ISSUE TITLE
[BUG] Extensions become huge after collapsing the side bar

### ISSUE THREAD

**Issue by LittleHaku** [zen-browser/desktop#7246]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

The issue is that when you enable the compact mode, the extension icons becomes huge, making it quite cluttered and uncomfortable.

![Image](https://github.com/user-attachments/assets/c4f71988-d9db-452d-b6b2-95edf25b38ea)

What I found as a temporal solution is that if you open and close the compact mode quickly enough (you can use the shortcut Alt+B) it gets rendered properly.

![Image](https://github.com/user-attachments/assets/50c32541-4ce5-4144-b581-8dddebb81912)

### Version

1.10.3b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Compact Mode

### Relevant log output if applicable

```shell

```

**Comment by Propheticus** [comment]
Can reproduce. Only happens when using the single toolbar layout.

**Comment by sporocyst** [comment]
but the pictures look like collpased mode, not compact mode?

**Comment by LittleHaku** [comment]
> but the pictures look like collpased mode, not compact mode?

You are right, I always confuse them. I just edited it! Thank you

**Comment by CodingOnCoughSyrup** [comment]
Can confirm. Facing the same issue

**Comment by Propheticus** [comment]
Good new, looks fixed in twilight 1.11.2t coming to a release soon <sup>:copyright:</sup>

**Comment by LittleHaku** [comment]
I just got the 1.11.4b update and I still have this happening!

**Comment by Propheticus** [comment]
Ok additional point:
It happens to me when the pinned extension does not fit in the single sidebar.
If the sidebar is wide enough so that the pinned extension does fit, it does not become 'huge' upon switching to collapsed mode.

If it does not fit in the single sidebar, huge:
![Image](https://github.com/user-attachments/assets/a34446e3-8872-49ba-937e-7b448ec55164)

![Image](https://github.com/user-attachments/assets/395cc230-bc65-4e1b-b5e7-a25699d95d2d)

If it fits in the single sidebar, not huge:
![Image](https://github.com/user-attachments/assets/763ba98d-a480-4916-93c0-7b28845df314)

![Image](https://github.com/user-attachments/assets/ed6e62e4-7e70-44fa-9846-1e6de7da0ccb)

**Comment by Propheticus** [comment]
Happens while switching between single and multiple toolbar modes as well:

https://github.com/user-attachments/assets/e5a5fc68-dd01-431b-9940-9644c64afa13
