### ISSUE TITLE
Complete JPEG-XL Support

### ISSUE THREAD

**Issue by gianni-rosato** [zen-browser/desktop#726]
### What feature would you like to see?

Currently, there is a flag disabled by default to support the JPEG-XL image format which works similarly to Firefox Nightly. This is great! However, there's a bit more to the story when it comes to complete JXL support:

- Firefox Nightly stopped maintaining their JPEG-XL support when the Chrome team made the controversial decision not to support JPEG-XL
- Since then, a the patchset has evolved to provide full JPEG-XL support without bugs. Bugs in the current implementation include:
  - Broken animation
  - Broken transparency
  - Improper color profile handling
- Browsers such as [Waterfox](waterfox.net/), [Floorp](https://floorp.app/en), and [r3dfox](https://github.com/Eclipse-Community/r3dfox) have implemented the patches fully. In order to test this, you can use this [JPEG-XL test page](https://jpegxl.info/test-page/).

### Other details

Here's a proper implementation (via Waterfox):

![waterfox_jxl](https://take-me-to.space/87mmtcYx.avif)

And here's Zen's current implementation (presumably carried over from Firefox Nightly):

![zen_jxl](https://take-me-to.space/2B4519W9.avif)

I think it is super awesome that the JPEG-XL flag is enabled in the first place, but this is an opportunity to go the extra mile for JXL support as it continues to improve elsewhere. The entire Apple ecosystem supports JPEG-XL, and Cloudinary cites serving billions of JPEG-XL images regularly. In addition, there are rumors that the [iPhone 16 may shoot JPEG-XL images by default](https://appleinsider.com/articles/24/08/22/exclusive-every-iphone-16-iphone-16-pro-camera-spec-capture-button-detail-revealed).

If you're interested in making this work, I can point you in the direction of the patchset & connect you with some developers who may be interested in helping make this work. Zen is really cool by the way, and given this issue is addressed, I'll happily switch from Waterfox to Zen without question! Thanks for your great work!

**Comment by mauro-balades** [comment]
This is fixed for the next release

**Comment by junedabat** [comment]
As of 1.0.0-a.35, JPEG-XL support still isn't enabled by default for me.

![image](https://github.com/user-attachments/assets/9c4ffab9-445d-4b28-8d52-bacbc51bb9f0)

Setting the `image.jxl.enabled` flag in `about:config` to `true` manually does enable it, but animated JPEG-XLs don't work.

Essentially, the problem is the same.
![image](https://github.com/user-attachments/assets/edb46e94-ebd3-42ea-8871-0764ecab1b2a)

**Comment by zzzsyyy** [comment]
As of 1.0.0-a.39, the jxl support is still incomplete

**Comment by onzecki** [comment]
> This is fixed for the next release

JXL is now indeed enabled by default but it still lacks the patches needed for the aforementioned issues to be fixed. Check [the JPEG XL test page to see it yourself.](https://jpegxl.info/resources/jpeg-xl-test-page.html)
The issue isn't quite yet resolved.

**Comment by NOCanoa** [comment]
@onzecki  are the patches in ff under a about:config flag? or wold we need to do it ourselvs?

**Comment by onzecki** [comment]
> @onzecki are the patches in ff under a about:config flag? or wold we need to do it ourselvs?

As @gianni-rosato mentioned, they're not under FF sadly, however several Firefox forks, (Waterfox f.e., as mentioned) have applied patches for animations, transparency, color profiles and more to work correctly

**Comment by gianni-rosato** [comment]
JXL support continues to be incomplete in 1.0.1-a.7. I think this should be reopened, as the initial issue still exists; any updates?

**Comment by mauro-balades** [comment]
It would be great if you could send those patches other forks do to have complet jxl

**Comment by zzzsyyy** [comment]
these links might be useful 

https://github.com/BrowserWorks/Waterfox/pull/2938

https://codeberg.org/librewolf/source/src/branch/main/patches/JXL_improved_support.patch

**Comment by onzecki** [comment]
This still isn't fixed, I think the issue should definitely be reopened @mr-cheff

**Comment by mr-cheffy** [comment]
Firefox needs to finish support for animated jxls yeah
