### ISSUE TITLE
Window does not close with last tab, even with `browser.tabs.closeWindowWithLastTab` set to true

### ISSUE THREAD

**Issue by BNTFryingPan** [zen-browser/desktop#7327]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

Closing the last tab of a window with `browser.tabs.closeWindowWithLastTab` set to `true` should result in the window closing, but it does not.

### Version

1.10.3b (Firefox 136.0.4) (64-bit)

### What platform are you seeing the problem on?

Linux (Flatpak)

### What component is this issue related to?

Tabs

### Relevant log output if applicable

```shell

```

**Comment by D-Brox** [comment]
Same thing is happening when closing the last tab of a `Private window` or when moving the last tab of a window to another window

Edit: the `Private Window` bug has been fixed, but moving tabs between windows hasn't

**Comment by bobbymannino** [comment]
this is still happening on mac, figured out its because of essentials. if you have 0 essentials then it closes but if you have one or more it wont, unless you change the tab setting of close pinned tab to close, then it will but it removes the essential when it does so either way bad things are happening

<img width="721" alt="Image" src="https://github.com/user-attachments/assets/419cb50f-19c6-49e0-abd6-a4f92563832f" />

**Comment by DioLps** [comment]
This is happening intermittently on windows as well.  Can't close the browser with the X native button.

**Comment by mauro-balades** [comment]
Make sure you have `browser.tabs.closeWindowWithLastTab` turned on in about:config

**Comment by BNTFryingPan** [comment]
this still happens to me, but im not sure if im on the latest version (will check in a few hours when i get home)

**Comment by bobbymannino** [comment]
still works for me, im on the latest version, it has persisted every version since commentating this, it also doesnt close if there are any pinned tabs too, so essentials or pinned tabs and it wont close, im using 2 different macs and a windows pc and it is on all of them for me

**Comment by bobbymannino** [comment]
still the issue persists

**Comment by nasserd** [comment]
I cannot reproduce this issue on the latest build (1.14b) -- in fact, I have already filed a different issue as a result of this behavior working as intended!!!
