### ISSUE TITLE
Toolbar disappears

### ISSUE THREAD

**Issue by Dornersito** [zen-browser/desktop#7746]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

In compact mode, when trying to access my bookmarks in the toolbar, it expands normally to access them, but when moving the mouse over my bookmarks, it disappears, preventing access to them

### Version

1.11.4b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Compact Mode

### Relevant log output if applicable

```shell

```

**Comment by Dornersito** [comment]
https://youtu.be/odNLI8FKvD8

**Comment by Propheticus** [comment]
Can reproduce.
A kind of workaround: navigate the mouse sideways along the top and at the bookmark you want only move straight down and click.
Another: click to open a bookmark folder > while the folder is expanded the bar does not hide.

**Comment by Dornersito** [comment]
Please fix it, it's very annoying 😭

**Comment by Dornersito** [comment]
https://youtu.be/gwq1t46wnfs

**Comment by Dornersito** [comment]
Of course, it's still unbearable :(

**Comment by Munkhu1** [comment]
The issue is still present in v1.14.9b

https://github.com/user-attachments/assets/b03b1bde-b951-402f-b71e-c6de1f9cc1cf

**Comment by Propheticus** [comment]
If you feel comfortable being on a nightly release (and the possible breakage involved at times) you can try the latest https://github.com/zen-browser/desktop/releases/tag/twilight

We've been trying out some workarounds for this quirk that's caused by how mouse (window drag) events are listened for / handled in Firefox.

**Comment by Propheticus** [comment]
@Dornersito This is (mostly) fixed in [v1.14.10b](https://github.com/zen-browser/desktop/releases/tag/1.14.10b)

**Comment by Dornersito** [comment]
Thank you so much! It seems solved for now :D @Propheticus

**Comment by Munkhu1** [comment]
The issue is still present in 1.14.10b.

https://github.com/user-attachments/assets/6c01783c-4393-4d89-bf44-b1d19e88eec3
