### ISSUE TITLE
"New background tab" toast even for foreground tabs

### ISSUE THREAD

**Issue by Meryl** [zen-browser/desktop#8146]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

I have "Compact mode" enabled. When I open a tab with the tab bar closed, even stuff like opening the settings from the menu, I will get a "New background tab opened!" toast. I even get it when (such as when opening the settings) the new tab is the active tab.

### Version

1.12.2b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Compact Mode

### Relevant log output if applicable

```shell

```

**Comment by filipesmedeiros** [comment]
Even using CMD+T will trigger the toast, for me. (Thanks Zen team, you are the best, by the way)

**Comment by ArenfeIdt** [comment]
Any Idea how i can disable this Toast completely? — not really my thing tbqh

**Comment by jacksongoode** [comment]
I believe Zen needs some virtualized testing framework, otherwise these issues are going to pile up....

**Comment by Meryl** [comment]
> Any Idea how i can disable this Toast completely? — not really my thing tbqh

I personally ended up setting `display: none !important` on `#zen-toast-container` in my userChrome.css. This obviously disables ALL toasts, so take that into consideration.

**Comment by Noelind** [comment]
Just wanted to echo @ArenfeIdt 's question, I'd also prefer an on/off setting for this Toast (or even pick & choose?).
Thanks again though Zen team for all your work, I'm a recent Arc convert and no way I'm going back!

**Comment by corb06** [comment]
Yeah I have this toast at all times, really annoying. It also blocks website buttons and functions that are located behind it sometimes. 
![Image](https://github.com/user-attachments/assets/f66813e5-a95a-4dac-a69c-79e1e68c33d3)

**Comment by M-O-Z-G** [comment]
They say that it was fixed in 1.12.3b:

> Fixed compact mode always showing a background tab has been added 

But I still can see this constantly, even if new tab is opening in the foreground. Looks a little bit annoying.

**Comment by M-O-Z-G** [comment]
They say that it was fixed in 1.12.3b:

> Fixed compact mode always showing a background tab has been added

But the issue is incomplete yet, this toast still appears even when new tab open in foreground.

**Comment by xeanth8** [comment]
Toast still appears when opening links with glance in compact mode.

**Comment by filipesmedeiros** [comment]
> But the issue is incomplete yet, this toast still appears even when new tab open in foreground.

I'm running 1.12.3b and I think the issue is solved for me

**Comment by M-O-Z-G** [comment]
> I'm running 1.12.3b and I think the issue is solved for me

Not.

> Toast still appears when opening links with glance in compact mode.

And also if a link opens a new tab in foreground but in a different container, for example, when a default container is set for domain.

**Comment by mr-cheffy** [comment]
> Not.

Did you even update?

**Comment by corb06** [comment]
I have updated to latest 1.12.3B , but the bug is still present. Here is a screenshot. 
NO tabs open after I closed down 10 tabs that I opened from a bookmark folder with middlebutton click. Closed them all, the "new background tab opened!" toast is still present.

![Image](https://github.com/user-attachments/assets/3be3a246-bfaf-4d11-bfb6-b60e5388efb9)

**Comment by mr-cheffy** [comment]
Oh, it's stuck? Try in latest twilight and let me know please

**Comment by wwsh123** [comment]
![Image](https://github.com/user-attachments/assets/383c3901-682d-4b75-99e6-5823f7a52b0f)
 It's still stuck.

**Comment by filipesmedeiros** [comment]
For what it's worth, I'm running on Mac M1 and it's all good for me (only shows when opening background and doesn't get stuck). I am running 1.12.3b.

**Comment by chrboesch** [comment]
> Any Idea how i can disable this Toast completely? — not really my thing tbqh

about:config -> zen.view.compact.show-background-tab-toast = false
