### ISSUE TITLE
Dragging a tab onto a Glance tab appends its favicon and renders the tab inaccessible

### ISSUE THREAD

**Issue by 0Ky** [zen-browser/desktop#8465]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

When using the Glance feature, dragging a tab onto a Glance tab triggers a bug where the dragged tab becomes inaccessible and appears visually merged with the Glance tab. The dropped tab remains active in the background, consuming memory and resources, but it can't be located or interacted with. Closing the Glance tab doesn't terminate those inaccessible dragged tabs, which lingers until the browser is restarted.

### Steps to Reproduce

1. Visit any website and `Alt + Click` a hyperlink to open it in the Glance view.
2. Open a separate tab and drag it on top of the Glance tab.

### Screenshot

![Image](https://github.com/user-attachments/assets/0559aa53-4930-4cb3-85bb-01902d666b8c)

### Version

1.12.6b and 1.13t 

### What platform are you seeing the problem on?

Linux (Tarball), Windows - x64

### What component is this issue related to?

Glance

### Relevant log output if applicable

```shell

```

**Comment by mr-cheffy** [comment]
@0Ky could you please test on https://github.com/zen-browser/desktop/actions/runs/15147133687

**Comment by 0Ky** [comment]
![Image](https://github.com/user-attachments/assets/1a5282d7-2585-45a1-b09c-6d28c9bb25e4)

Not fixed.

**Comment by mr-cheffy** [comment]
@0Ky what about on latest?

**Comment by 0Ky** [comment]
@mauro-balades Which latest? If you're referring to your previous comment, yes the test was conducted using the shared Actions.

**Comment by mr-cheffy** [comment]
I've pushed a new build: https://github.com/zen-browser/desktop/actions/runs/15155589848

**Comment by 0Ky** [comment]
Oke, I'll test it once Actions finishes building.

**Comment by 0Ky** [comment]
@mauro-balades
![Image](https://github.com/user-attachments/assets/b14755ea-e1c1-44da-a521-d843c8d5abdf)
Still reproducible 1.13t (Firefox 138.0.4) (2025-05-21) (build id 20250521065743)

It's somehow worse now, it broke the entire tabs in the window:
 
https://github.com/user-attachments/assets/42edf8a3-52b7-49ca-bd38-b5a1400c2ced

**Comment by mr-cheffy** [comment]
@0Ky could you send a video on reproducing it? Im trying every way possible and I just cant. With splitview, without split view. I used to be able to reproduce until newest twilight

**Comment by 0Ky** [comment]
@mauro-balades Unfortunately, I don't know the exact steps to _break_ the tabs as I showed in my [previous comment](https://github.com/zen-browser/desktop/issues/8465#issuecomment-2897901683).

Here's how I reproduced the issue:

https://github.com/user-attachments/assets/989b0f68-5a6c-48e9-ba96-ea19cc48efde

**Comment by mr-cheffy** [comment]
@0Ky https://github.com/zen-browser/desktop/actions/runs/15164171872

**Comment by 0Ky** [comment]
@mauro-balades Looks like it's resolved. I can't reproduce the issue anymore with the latest Actions build.
