### ISSUE TITLE
[regression] tab bar doesn't follow the currently selected tab.

### ISSUE THREAD

**Issue by KorigamiK** [zen-browser/desktop#8623]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

switching through tabs, either by using `ctrl+tab` or `alt+<number>` doesn't scroll the tab bar to the newly selected tab like before. 

### Version

Mozilla Zen 1.12.8b

### What platform are you seeing the problem on?

Linux (AppImage), Linux (Tarball)

### What component is this issue related to?

Tabs

### Relevant log output if applicable

```shell

```

**Comment by 0Ky** [comment]
Unable to reproduce, tested on `1.12.8b` (Tarball) with a complete fresh installation:
```shell
rm -rf ~/.cache/zen/ ~/.zen/ ~/.var/app/app.zen_browser.zen
```
I wonder if it's because of your environment, are you running on Wayland ?

**Comment by NaakkaDev** [comment]
I have this issue too. I'm on a fresh Arch Linux, Wayland, Hyprland. Browser version 1.12.10b.

**Comment by KorigamiK** [comment]
> Unable to reproduce, tested on `1.12.8b` (Tarball) with a complete fresh installation:
> ```shell
> rm -rf ~/.cache/zen/ ~/.zen/ ~/.var/app/app.zen_browser.zen
> ```
> I wonder if it's because of your environment, are you running on Wayland ?
> 

This issue was fixed in the newer updates for me

**Comment by NaakkaDev** [comment]
After I enabled the "Ctrl+Tab cycles through tabs in recently used order" setting, the issue went away and doesn't seem to resurface even when I turn it off.

**Comment by gaardhus** [comment]
I too am having this issue after the most recent update. I'm running sway on arch linux and tried toggling the "cycle through tabs" settings but that didn't solve it.

**Comment by KorigamiK** [comment]
> I too am having this issue after the most recent update. I'm running sway on arch linux and tried toggling the "cycle through tabs" settings but that didn't solve it.

~~Yeah this issue happens from time to time as you update zen. One easy way I've figured out which works is resetting the toolbar (right click and reset) and clearing the startup cache (go to about:support and clear startup cache).~~

Yeah not anymore

**Comment by KorigamiK** [comment]
This issue is still up on the latest release: `Mozilla Zen 1.13.2b`

**Comment by Propheticus** [comment]
Can't repro in 1.14.9b 

Going to assume fixed and close this issue... unless told otherwise, then we'll reopen if needed.
