### ISSUE TITLE
Sidebar stuck open, does not collapse when compact mode turned on.

### ISSUE THREAD

**Issue by michaelpulis** [zen-browser/desktop#8643]
### Captchas

- [x] I have read the instructions.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

With compact mode turned on, the side bar does not collapse when the mouse hovers away from it. After booting the browser this is not an issue, but randomly, roughly an hour into usage it happens and the side bar stops collapsing automatically. The sidebar is still functional, so is workspace switching when this happens. It also does not happen when the laptop awakes from sleep, it happens randomly when I move my mouse out of the sidebar, and it just doesn't go back in and stays like that.

This has been happening for the last few versions so I don't think it was something introduced just now. 

The only solution I have is to restart the browser entirely which is annoying because it forces me to lose progress, or to disable compact mode which is also not ideal as it reduces the page size too much for me.

### Version

1.12.8b (Firefox 138.0.4) (aarch64)

### What platform are you seeing the problem on?

macOS - aarch64

### What component is this issue related to?

Compact Mode

### Relevant log output if applicable

```shell

```

**Comment by PXNDA-E36** [comment]
This also an issue on Fedora 42 with the same Zen browser version (1.12.8b) but the sidebar is not fully functional for me. Tabs will not close with the little x but will close using the shortcut CTRL+W. The fix is the same - to restart the browser.

**Comment by InterstellarOne** [comment]
I have the same issue on Fedora 42 with 1.12.10b, but it gets stuck when the browser launches, and it will not close. I disabled all mods and custom css to make sure that wasn't the issue. 
[Video](https://files.catbox.moe/v8itsf.mp4)

**Comment by coffee-dan** [comment]
I am seeing a similar issue on Arch with version `1.13.2b (Firefox 139.0.4) (64-bit)`. I do not have any mods or custom CSS. I disabled all extensions to make sure that was not the cause.

For what it is worth, this typically occurs after opening a new tab using the new tab command palette via `ctrl+t`. This most recent occurrence came after opening the very Javascript heavy login page for Brex.

**Comment by tomrfitz** [comment]
I'm experiencing this issue on macOS 15.5 (24F74) + Twilight 1.14t 20250625024342 140.0, and the previous several builds as well.

Mods and custom css have been disabled. Relaunching the browser resolves the issue temporarily, but the sidebar becomes stuck again after opening / switching tabs several times. This occurs with single, multiple, and collapsed toolbar settings, but only affects the sidebar.

**Comment by 1999Markus** [comment]
Same issue on macOS 15.0.1 (24A348). Always reproducible when no tab is selected, i. blank tab. 

<img width="1800" height="1136" alt="Image" src="https://github.com/user-attachments/assets/9a2794c5-a112-4342-8475-e210d4217a64" />

**Comment by michaelpulis** [comment]
Is anyone looking into this ? It has become a lot more common nowadays, which is making the browser somewhat unusable, despite all the great work that has been going into it.

**Comment by Propheticus** [comment]
@1999Markus That's normal behaviour on empty state > indicate nothing's loading, browser is ready for you to start navigating.

The buggy behaviour as described in the opening post and as shown in the video of @InterstellarOne is obviously not normal.
@michaelpulis can you confirm this happens without custom themes / mods?

I have not encountered this on Windows. @mr-cheffy You're a Mac user, ever witnessed the stuck compact sidebar that only get fixed with a browser restart?

**Comment by michaelpulis** [comment]
<img width="676" height="391" alt="Image" src="https://github.com/user-attachments/assets/7779fcca-0670-434a-a4ff-424b1a117234" />

This is the only mod I use, I will disable it for a day and report if it happens at the end of that day.

**Comment by NorinB** [comment]
I'm also facing the same issue. However I noticed, that this bug seems to occur, when the sidebar is currently opened and I try to close a tab, which prompts a browser-native dialog asking me to confirm, that I want to leave the site.

**Comment by apogee-49** [comment]
I have the problem on windows. Side is stuck when in compact mode, usually happens after switching from one app to the other. Only restarting the browser works

**Comment by mr-cheffy** [comment]
> Same issue on macOS 15.0.1 (24A348). Always reproducible when no tab is selected, i. blank tab.

Note that this is expected.

> I'm also facing the same issue. However I noticed, that this bug seems to occur, when the sidebar is currently opened and I try to close a tab, which prompts a browser-native dialog asking me to confirm, that I want to leave the site.

I managed to reproduce this *once* on mac and never again... I wonder why

**Comment by michaelpulis** [comment]
Managed to replicate it again today, without any zen mods being turned on. Shows what I mentioned originally, where the UI is still fully functional and I can change workspaces. But the sidebar doesn't collapse when it should. Toggling the relevant setting did not fix it. This was fixed by restarting the browser.

https://github.com/user-attachments/assets/104add99-c2bd-43e6-87ee-17146d34c7f3

**Comment by mr-cheffy** [comment]
<img width="79" height="62" alt="Image" src="https://github.com/user-attachments/assets/fbb01a8c-fe51-4142-b39c-9e0797d421fa" />

Seems due to that this icon is marked as "opened", should be fixed next release

**Comment by Jellie06** [comment]
First time I've experienced this issue. Restarting it does fix it but also for mine it seems there's a correlation between how long I hover over it and it getting stuck. If I quickly flick back and forth it doesn't get stuck but also it gets stuck a lot if I press ctrl tab whilst hovering.

**Comment by BoscoDomingo** [comment]
Pretty sure this is a duplicate of #2945

**Comment by Herobrine4770v2** [comment]
Exactly same issue on windows 11.
1.17.15b (Firefox 146.0.1) (64-bit)

**Comment by karellm** [comment]
Is there any update on this? It started happening to me recently and has been quite annoying as it basically makes the browser unusable.

**Comment by mr-cheffy** [comment]
Could I please get logs from ctrl+shift+J?

Make sure to enable `zen.view.compact.debug` in about:config. Then just move the mouse in and out of the sidebar

**Comment by magikmw** [comment]
```
ZenSessionManager: Initializing session manager ZenSessionManager.sys.mjs:101:15
ZenSessionManager: Session file path: /home/magikmw/.zen/002b8uat.magikmw-default/zen-sessions.jsonlz4 ZenSessionManager.sys.mjs:101:15
ZenSessionManager: Reading Zen session file from disk ZenSessionManager.sys.mjs:101:15
ZenSessionManager: Restoring Zen session data into 2 windows ZenSessionManager.sys.mjs:101:15
[ZenMods]: No enabled Zen mods. 2 ZenMods.mjs:117:13
[Zen Compact Mode] Setting compact mode preference to true ZenCompactMode.mjs:106:15
[ZenMods]: No enabled Zen mods. ZenMods.mjs:117:13
[Zen Compact Mode] Setting compact mode preference to true ZenCompactMode.mjs:106:15
[Zen Compact Mode] Mouse entered URL bar: 
<html:moz-urlbar id="urlbar" class="urlbar" popover="manual" pageproxystate="valid" sap-name="urlbar" style="--zen-urlbar-top: 549.5p… --urlbar-height: 38px;" breakout="true" breakout-extend-animate="true" domaindir="ltr">
ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element <empty string> ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 2 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 2 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 2 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 2 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 2 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
ZenSessionManager: Saving Zen session data with 290 tabs ZenSessionManager.sys.mjs:101:15
ZenSessionManager: Saving Zen session data with 290 tabs ZenSessionManager.sys.mjs:101:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 2 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
ZenSessionManager: Saving Zen session data with 290 tabs ZenSessionManager.sys.mjs:101:15
NS_ERROR_NOT_AVAILABLE: 
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
ZenSessionManager: Saving Zen session data with 278 tabs ZenSessionManager.sys.mjs:101:15
ZenSessionManager: Saving Zen session data with 278 tabs ZenSessionManager.sys.mjs:101:15
ZenSessionManager: Saving Zen session data with 278 tabs ZenSessionManager.sys.mjs:101:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 2 ZenCompactMode.mjs:106:15
Content-Security-Policy warnings 3
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
Cookie warnings 2
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
ZenSessionManager: Saving Zen session data with 277 tabs ZenSessionManager.sys.mjs:101:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
Content-Security-Policy warnings 4
ZenSessionManager: Saving Zen session data with 276 tabs ZenSessionManager.sys.mjs:101:15
Content-Security-Policy warnings 5
ZenSessionManager: Saving Zen session data with 275 tabs ZenSessionManager.sys.mjs:101:15
Content-Security-Policy warnings 6
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
Content-Security-Policy warnings 2
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 2 ZenCompactMode.mjs:106:15
ZenSessionManager: Saving Zen session data with 275 tabs ZenSessionManager.sys.mjs:101:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 8 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 5 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 2 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 7 ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to false on element navigator-toolbox ZenCompactMode.mjs:106:15
[Zen Compact Mode] Setting zen-has-hover to true on element navigator-toolbox 3 ZenCompactMode.mjs:106:15
```

That's how it looks for me when it happened.

It goes from true to false, then immediately back to true when the mouse is leaving the sidebar. Further waving the cursor about sometimes makes it go to false and hide it.

This is Zen 1.18.10b on Fedora KDE.

**Comment by LAST7** [comment]
right click a superlink and select 'Open in New Tab' in a pinned tab can cause this as well.

1.17.15b (Firefox 146.0.1) (64-bit)
Zen Browser for Arch Linux
archlinux - 1.0

**Comment by supposede** [comment]
Man I regret everytime I update this browser. I get this bug suddenly too on Hyprland

**Comment by DRSdesign** [comment]
Also still experiencing this issue on windows PC.

**Comment by natiT** [comment]
same issue 

CachyOS (Arch) 
Wayland on Hyprland

**Comment by Maikhaaa** [comment]
Same on Arch linux with KDE using Wayland.
Strangely enough I had a similar issue on firefox too (probably unrelated but when bar was set to vertical and compact it sometimes got stuck as well).

**Comment by mr-cheffy** [comment]
Could this be related to https://github.com/zen-browser/desktop/issues/12648?

**Comment by InterstellarOne** [comment]
Probably not, as it happens when only one window is open

**Comment by ztan-dev** [comment]
Writing here because no one's mentioned this info yet. In my case (running on the macOS platform with automatic updates disabled) this typically happens when there's an update to Zen Browser that I haven't installed yet. 

In this case, the sidebar remains stuck open even in compact mode, and there is no indication that this is because of a pending update. Accepting the update prompt makes this issue go away almost immediately.

This might be intended behavior (to draw the user's attention to a pending update), but there should be some kind of indication to the user that there is an update waiting.

**Comment by Micnubinub** [comment]
Latest update (1.19.7b (Firefox 149.0.2) (aarch64)) has broken the sidebar for me. Hit and miss when it stays open, but seems to be mostly affecting google sites (youtube when a video is plaing and calendar)

**Comment by nikotonn** [comment]
Also happening to me. Seems to happen on some sites when any media is playing, or on youtube whether something is playing or not. This only happens in Only Sidebar mode- if I switch to Side+Top or Collapsed, the issue goes away.
While testing this again to make sure as I type this, I find also that if I switch from Collapsed to Only Sidebar, then the sidebar is displayed at half its normal width, with all elements resized and formatted appropriately.
I am using the Linux flatpak

**Comment by Egit90** [comment]
I'm experiencing this issue on macOS. Seems to happen when I have multiple windows open.

**Comment by Ebuall** [comment]
This appeared recently, probably last update. Windows OS. 2 windows, 2 workspaces, on 2 monitors.  Sidebar only layout. Only one of the windows is using compact mode.

**Comment by mr-cheffy** [comment]
Make sure you are on 1.19.8b.

@nikotonn @Ebuall @Egit90 @Micnubinub

**Comment by nikotonn** [comment]
It is now fixed on 1.19.8b. Had to wait overnight for it to hit flathub, though I saw the patch release yesterday evening

**Comment by Micnubinub** [comment]
@mr-cheffy update fixed it for me

**Comment by BoscoDomingo** [comment]
I can still reproduce in 1.19.8b, when using 2 windows and moving tabs from one to another (at least with 2 monitors). The original window gets the bug. The receiver window works as expected.

Video (recorded with Add-ons disabled to rule out that possibility):

https://github.com/user-attachments/assets/4c40e1e5-a5a0-4c8e-bfef-0eae0c2f20c6

Related to #13103

**Comment by thijmenketel** [comment]
> I can still reproduce in 1.19.8b, when using 2 windows and moving tabs from one to another (at least with 2 monitors). The original window gets the bug. The receiver window works as expected.
> 
> Video (recorded with Add-ons disabled to rule out that possibility):
> 20260412_210000_zen_Qc187mHknw.mp4
> 
> Related to [#13103](https://github.com/zen-browser/desktop/issues/13103)

It seems to get fixed by moving windows across again (either way), so that might by a kind-of workaround?

**Comment by sporocyst** [comment]
@BoscoDomingo Have you disabled windows sync?
I did some initial test and found that this issue is more prone to happen when windows sync is disabled, as what I wrote in https://github.com/zen-browser/desktop/issues/13195#issuecomment-4221984869. I am curious to know if this is a shared experience.

**Comment by BoscoDomingo** [comment]
> [@BoscoDomingo](https://github.com/BoscoDomingo) Have you disabled windows sync? I did some initial test and found that this issue is more prone to happen when windows sync is disabled, as what I wrote in [#13195 (comment)](https://github.com/zen-browser/desktop/issues/13195#issuecomment-4221984869). I am curious to know if this is a shared experience.

Yes, I did

**Comment by cfarvidson** [comment]
I get this issue since the `1.19.8b (Firefox 149.0.2) (aarch64)` I have not having it before.

**Comment by mr-cheffy** [comment]
Whats a consistent way of reproducing this?

**Comment by sporocyst** [comment]
>Whats a consistent way of reproducing this?

Not sure. But I got a console error when that happened. Hope it will help.

<img width="885" height="91" alt="Image" src="https://github.com/user-attachments/assets/5937df5e-d3e2-4af6-8d3a-3495caa41a99" />
  

<img width="879" height="113" alt="Image" src="https://github.com/user-attachments/assets/f12f77a2-31b9-4126-b7a2-7e31bef1ce67" />

**Comment by SergioFabresFilho** [comment]
It's happening to me on macOS as well, whenever I open the sidebar it may or may not get stuck, I wasn't able to pinpoint any common denominator when that happens

**Comment by mr-cheffy** [comment]
Hi, is this still happen on the latest version?

**Comment by NorinB** [comment]
> Hi, is this still happen on the latest version?

Hi, at least for me, it haven't happened for a long time now.

**Comment by sporocyst** [comment]
Don't know about initial issue, but for https://github.com/zen-browser/desktop/issues/8643#issuecomment-4232530393, yes, it is still there. (1.19.9b Win)

**Comment by mr-cheffy** [comment]
This issue has unfortunately been diverged into a mesh of common compact mode issues. The original issue is almost a year old so its likely it cant be reproduced anymore. 

That said, https://github.com/zen-browser/desktop/pull/13430 does handle drag and dropping making compact mode stuck. If there are any other related issue, please consider making a new one to keep this issue clean. Thanks!
