### ISSUE TITLE
Website slowing down popup coming in the wrong spot and is only partially visible

### ISSUE THREAD

**Issue by srynprjl** [zen-browser/desktop#87]
### What happened?

When a website slows down the browser, the popup comes in the sidebar, and only some part of it is visible

![zen-your-feedback-our-evolution-lots-of-improvements-made-v0-2cw2o1rmt2fd1](https://github.com/user-attachments/assets/b7253f4a-2528-4f42-aee7-919455480f7c)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0-a.7

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
What website is this? Instagram?

**Comment by srynprjl** [comment]
yes, it is instagram

**Comment by mauro-balades** [comment]
Fixed for the next release 👍🏽

**Comment by srynprjl** [comment]
> Fixed for the next release 👍🏽

i am in a.15 still, this type of popup comes in that spot

![image](https://github.com/user-attachments/assets/397e0eba-410b-4c93-9294-855939b9997a)

**Comment by tom-schmitz** [comment]
Just came across this popup in a newer version, and the popup placement seems a bit strange. Perhaps putting at the top or bottom of the main window would be nicer, instead of in the sidebar?

![image](https://github.com/user-attachments/assets/49585674-a3e0-4127-b50a-148b856cffb8)

Version: 1.0.0-a.34 (64-bit)
Platform: Windows 11

**Comment by mauro-balades** [comment]
This has been fixed for the next release, thanks you!

**Comment by definite-d** [comment]
Hi, I'm on v1.0.0-a.39, and the unresponsive warning still shows in the sidebar.
![image](https://github.com/user-attachments/assets/80a986d9-4791-41f4-87a5-c6743a5947be)

It also happens with extensions that slow down.

**Comment by definite-d** [comment]
Actually fixed in version 1.0.1-a.
