### ISSUE TITLE
Zen Browser isn't updating.

### ISSUE THREAD

**Issue by YoHighnessM** [zen-browser/desktop#8970]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

One Zen isn't updating automatically and even after updating it manually when I open the app I still get the "Update available" popup. I googled the latest version and it's "1.12.10b" and the version I have is the same but I don't know why it's asking me to update

### Expected behavior

After the manually updating it it was supposed to update 

### Actual behavior

Even if I downloaded the new version and updated manully I still get the "Update available" popup

### Steps to reproduce

1. downloaded the new update from the actual site
2. went through all the installation step
3. reopened zen the "Update available"  popup is still visible

### Version

1.12.10b

### What platform are you seeing the problem on?

Windows - x64

### What component is this issue related to?

Other

### Relevant log output if applicable

```shell

```

**Comment by mr-cheffy** [comment]
Try clearing startup cache in about:support

**Comment by arg387** [comment]
Try to uninstall the app then install it again. It worked for me.

**Comment by YoHighnessM** [comment]
> Try to uninstall the app then install it again. It worked for me.

I did it but it's still the same

**Comment by Waterstraal** [comment]
I have the same issue.

<img width="1161" height="494" alt="Image" src="https://github.com/user-attachments/assets/3d7a98af-374e-4ca4-8df6-d939fb70e2cd" />

**Comment by flmalte** [comment]
For me its also not updating from 1.13.2b. Im on macOS.

**Comment by Will-Georges** [comment]
> For me its also not updating from 1.13.2b. Im on macOS.

I'm having the exact same thing. There was another issue where it was also being discussed:
https://github.com/zen-browser/desktop/issues/9270

**Comment by Waterstraal** [comment]
> > For me its also not updating from 1.13.2b. Im on macOS.
> 
> I'm having the exact same thing. There was another issue where it was also being discussed: [#9270](https://github.com/zen-browser/desktop/issues/9270)

Why did they close that issue? Clearly it is still an issue?

**Comment by Will-Georges** [comment]
> Why did they close that issue? Clearly it is still an issue?

I created a new issue so hopefully the devs can have a look:
https://github.com/zen-browser/desktop/issues/9387#issue-3217771066

**Comment by mr-cheffy** [comment]
Should be fixed now 👍🏽

**Comment by javiersantos** [comment]
It still does not work, at least on OS X using “Zen Browser” instead of “Zen” package.
cc/ @mr-cheffy 

<img width="737" height="371" alt="Image" src="https://github.com/user-attachments/assets/49bf9b17-2eec-44b2-b678-66b7ad2b06a5" />

**Comment by mr-cheffy** [comment]
Yeah, it's been paused for a bit, again

**Comment by imomaliev** [comment]
Had the same issue fixed it using these steps https://github.com/zen-browser/desktop/issues/9270#issuecomment-3062750214
