### ISSUE TITLE
Container tabs label not being shown on tab bar

### ISSUE THREAD

**Issue by PostboxRetinal** [zen-browser/desktop#9007]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

Just updated to latest 1.13b via tarball as usual. Trying to create a new tab and assign it a container (as I'm used to) just shows the icon, no label at all

### Expected behavior

Click the 'plus' icon and select a container for a new tab and start browsing

### Actual behavior

Clicked plus icon just showed a center aligned icon of the container, not the container label

### Steps to reproduce

I'm currently using vertical tabs

1. Click '+' icon (labeled 'Select container to open new tab')
2. Try to select a new container
3. A centered column with just container icon will show (no label at all)
4. A new tab will be created

### Screenshots and videos

![Image](https://github.com/user-attachments/assets/95db784f-f86b-4aa5-9eb8-4be95ae02059)

### Version

1.13b

### What platform are you seeing the problem on?

Linux (Tarball)

### What component is this issue related to?

Tabs

### Relevant log output if applicable

```shell

```

**Comment by Propheticus** [comment]
There appears to be a difference between using the long click (affected) and right-clicking (not affected)

Long press:

![Image](https://github.com/user-attachments/assets/d642f375-8f88-4ca9-a7c2-1e4649f65a9b) 

Right-click: 

![Image](https://github.com/user-attachments/assets/7618ef6e-2da3-4132-a920-0fcdf49643af)

**Comment by PostboxRetinal** [comment]
Same over here, didn't noticed before. Shouldn't it be the same? Thanks for the clarification, will right click it on the meantime

**Comment by nasserd** [comment]
Furthermore, the context menu in the long-click action has variable design (width, line breaks, overall sizing... and disappearing text based on the expanded/collapsed condition of the sidebar)... but the right-click action is unaffected by this bug and has the expected design in both expanded and collapsed sidebar conditions.

**Comment by PostboxRetinal** [comment]
Seems it keeps failing even after 1.13.1b update. Just doesn't work while collapsed toolbar is still active

**Comment by PostboxRetinal** [comment]
Fixed on latest update (v1.14b). Working as expected
Left click does open as before but now is larger, right click is way more compact

**Comment by vDAKK** [comment]
> There appears to be a difference between using the long click (affected) and right-clicking (not affected)
> 
> Long press:
> 
> ![Image](https://github.com/user-attachments/assets/d642f375-8f88-4ca9-a7c2-1e4649f65a9b)
> 
> Right-click:
> 
> ![Image](https://github.com/user-attachments/assets/7618ef6e-2da3-4132-a920-0fcdf49643af)

Hi,

The issue is still there exactly like the quoted reply.
My version is 1.14.5b

**Comment by rsenna** [comment]
Leaving this here because _I keep forgetting it after reinstalling Zen_, and it's **surprisingly** hard to find again:

> ⚠️ Attention
>
> If you want to show the current "Firefox Multi-Account Containers" name in the URL bar, as Zen originally did by default:
> 1. Go to `about:config`
> 2. Set `zen.urlbar.show-contextual-id` to **`true`**
