### ISSUE TITLE
Zen browser no loger has dark mode after update

### ISSUE THREAD

**Issue by historyb1** [zen-browser/desktop#9229]
### Preliminary Checks

- [x] I have read and understood the important section above.
- [x] I have searched existing issues and avoided creating duplicates.
- [x] I am not filing an enhancement request.
- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.
- [x] I have checked that this issue can be reproduced once I removed all my Mods and Custom CSS.

### What happened?

I was notified of an update and when I updated and restarted the browser Zen no longer has dark mode even when I enable it.

### Expected behavior

Same as before I closed the browser

### Actual behavior

No dark mode

### Steps to reproduce

I do not know, it just happened when I updated the browser

### Screenshots and videos

![Image](https://github.com/user-attachments/assets/7c646401-7d8b-4a38-bb81-4c9d7b604c9f)

### Version

1.14b

### What platform are you seeing the problem on?

Linux (Flatpak)

### What component is this issue related to?

Mods / Themes

### Relevant log output if applicable

```shell

```

**Comment by daika7ana** [comment]
Same issue under Windows 11.

I did change the theme under the new menu (Edit theme), but not everything is being themed properly (eg. Status bar, Find bar).

**Comment by PushaG** [comment]
It's not a bug, it works. Make sure to right click on tab bar, select edit theme and in new window that opens click on arrow to the right of little colored dots to reveal more colors, just choose some darker shade.

![Image](https://github.com/user-attachments/assets/5d8fc0aa-0f7e-4083-812d-24b2f63adf3d)

**Comment by Propheticus** [comment]
and/or if you don't want Zen to follow your system theme for light/dark website look: change the star to either sun(light) or moon(dark)

**Comment by ItsPasi** [comment]
I use light theme and since the new update I can't get it to light mode anymore, the sidebar only shows the dark color options now.


![Image](https://github.com/user-attachments/assets/f05682bf-8e00-45e7-bd24-13dcfb4e0aa9)

**Comment by 413x1nkp** [comment]
> It's not a bug, it works. Make sure to right click on tab bar, select edit theme and in new window that opens click on arrow to the right of little colored dots to reveal more colors, just choose some darker shade.
> 
> ![Image](https://github.com/user-attachments/assets/5d8fc0aa-0f7e-4083-812d-24b2f63adf3d)

That worked! Although i must say, this is a bit confusing..
There's some weirdness going on, where Zen's icons (like the cog wheel for the settings or the downloads button) are relying on the COLOR SCHEME to choose whether or not they're dark mode or not, instead of relying on the actual selected theme.

![Image](https://github.com/user-attachments/assets/11b6412a-b26e-422b-9186-dd3559b2172c)

But websites like github have their icon correspond to selected theme correctly:

![Image](https://github.com/user-attachments/assets/fb59a887-258a-4220-bc5e-5ae0bebe3eec)

So it would appear that there are two ways to switch theme. One is by changing color scheme and the other is by manually setting it, and both do something unique and are independent from each other. Can't say i like that too much, but it's probably a bug.

**Comment by daika7ana** [comment]
For me it's just partially working.

As I have stated in the previous post. 
The Finder bar (CTRL/CMD + F) and the Status bar (hovering over a link, visible in bottom of the screen) are always stuck in Light mode, even if dark mode is selected in the new Edit Theme menu. Also using the Customize Toolbar displays the same symptom, the element picker is stuck in light mode.

![Image](https://github.com/user-attachments/assets/c8e4ae2d-fa6b-49c6-87c1-01f80a7e622f)

**Comment by 413x1nkp** [comment]
> For me it's just partially working.
> 
> As I have stated in the previous post. The Finder bar (CTRL/CMD + F) and the Status bar (hovering over a link, visible in bottom of the screen) are always stuck in Light mode, even if dark mode is selected in the new Edit Theme menu. Also using the Customize Toolbar displays the same symptom, the element picker is stuck in light mode.
> 
> ![Image](https://github.com/user-attachments/assets/c8e4ae2d-fa6b-49c6-87c1-01f80a7e622f)

That's odd. Have you tried selecting the right-most colors in the picker AND selecting a dark theme by clicking on the moon?

**Comment by daika7ana** [comment]
> That's odd. Have you tried selecting the right-most colors in the picker AND selecting a dark theme by clicking on the moon?

Yes. No change. Neither the colors nor the swapping between Light/Dark (Sun/Moon) toggles affect them. They're stuck in Light mode.

**Comment by 413x1nkp** [comment]
> > That's odd. Have you tried selecting the right-most colors in the picker AND selecting a dark theme by clicking on the moon?
> 
> Yes. No change. Neither the colors nor the swapping between Light/Dark (Sun/Moon) toggles affect them. They're stuck in Light mode.

Alright now THAT'S strange.
Try going to `about:addons` and enabling the dark theme manually, or see if you have any other theme already enabled

**Comment by daika7ana** [comment]
Dark theme is already enabled in `about:addons#themes` but changing between Dark, Light and System themes does nothing.
PS. Issue is present in Safe-mode as well, with all Add-ons and Zen Mods disabled.

**Comment by 413x1nkp** [comment]
> Dark theme is already enabled in `about:addons#themes` but changing between Dark, Light and System themes does nothing. PS. Issue is present in Safe-mode as well, with all Add-ons and Zen Mods disabled.

I think i was wrong. It looks like alongside the general weirdness of the new theme selection with the color schemes there's also an actual problem, at least on Windows 11 (maybe also on the flatpak version, but OP never responded on if changing color scheme helped).

I'm using `zen-browser` off AUR and performing steps i outlined above did it for me..

**Comment by historyb1** [comment]
I am so sorry to not have responded in a timely manner. I ended up reinstalling the flatpak on my Laptop, and it still has the finder bar stuck in light mode. It still is not the same theme as it was before, but I did select dark off of the Color Scheme. I haven't updated the flatpak on my Desktop yet, though, so it still has the old theme that came with Zen.

**Comment by Beeditor04** [comment]
same issue with window 11 on newst update, In my case it's only work in partial way, ONLY A FEW COLOR work properly (look like there are colors for dark mode and light mode, but this kind of UI is very confusing):

![Image](https://github.com/user-attachments/assets/ae541d67-646d-4007-b8f1-a84c722cc44f)

![Image](https://github.com/user-attachments/assets/55d7ec98-83b0-4063-aef4-44afd6fcad7d)

![Image](https://github.com/user-attachments/assets/bc8b1276-6933-441c-8277-ae19c3843f31)

**Comment by ItsPasi** [comment]
Also like I mentioned above but with a bad example, this is the lightest I can get it in light mode and this is just way too dark.


![Image](https://github.com/user-attachments/assets/a3eb436c-3b5f-497e-b8ca-5f0c790cd010)

**Comment by yutsuku** [comment]
> It's not a bug, it works. Make sure to right click on tab bar, select edit theme and in new window that opens click on arrow to the right of little colored dots to reveal more colors, just choose some darker shade.
> 
> ![Image](https://github.com/user-attachments/assets/5d8fc0aa-0f7e-4083-812d-24b2f63adf3d)

Windows build doesn't seems to follow system theme either. Previous builds were having dark theme by default here, now it's all white until I switch to the moon icon in the `Edit theme` picker. Available themes makes this use case even more confusing as seen below:

![Image](https://github.com/user-attachments/assets/6f3c6ef2-4cff-4825-96cd-9a2282374a5c)


Following note from the changelog also isn't clear enough in my opinion. What IS the browser background (I always have at least one tab open and use floating new tab menu)?

> v1.14b • Firefox 140.0.2 June 29, 2025
> Added Added automatic dark/light mode detection based on the browser's background.

**Comment by historyb1** [comment]
Yutsuku explained the problem better than I did. Thank you

**Comment by historyb1** [comment]
Updated to the newest update, and it turned my browser white again. 

<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/6e28d4e8-045e-4daa-8d07-d0d92413a8a4" />

When I installed Zen for the first time it was a nice dark, now this. The updated changed the browser to a different color, and this is not zen. The edition of Zen is 1.14.4b and no theme will work

**Comment by ItsPasi** [comment]
> Updated to the newest update, and it turned my browser white again.

You can click one of the darker preset colors to get a darker color wheel. For me at least the browser now works as expected again.

**Comment by historyb1** [comment]
Thank you. Though it should have never changed. I installed the browser originally because it came dark out of the box

**Comment by ItsPasi** [comment]
> Thank you. Though it should have never changed. I installed the browser originally because it came dark out of the box

I used the lighter colors all the time since I am in light mode so I think it should offer both light and dark colors, but it is a bit unintuitive to get the correct option, they should add a brightness slider.

**Comment by AnAnonymousAuditor** [comment]
I'm also experiencing the same issues mentioned here (I'm on Windows 10):
- Same as Yutsuku and others, Zen uses the light theme even while having the theme in `about:addons` set to dark; it only gets "fixed" after selecting the dark theme in "Edit theme" from the tab bar context menu (moon icon instead of sparkle icon).
- Even with that "fix", at least the status bar, find bar and customize toolbar widget are still stuck in light mode.

Another thing that gets stuck in "light mode" are the toast notifications (just white text in this case, which makes it a bit harder to read; it used to be black text).
It happens with "New background tab opened":

<img width="229" height="61" alt="Image" src="https://github.com/user-attachments/assets/063f280a-33f2-49b6-bbf5-a03df57fd76a" />

And it also happens with "Successfully saved the gradient" after "closing" the Edit theme selector:

<img width="236" height="57" alt="Image" src="https://github.com/user-attachments/assets/255af74d-0210-45c5-94bd-283bfa47f72f" />

On a slightly unrelated note, I also use Zen on my Arch Linux laptop (AUR package: [`zen-browser-bin`](https://aur.archlinux.org/packages/zen-browser-bin)) and can confirm these same issues don't show up, except for the toast notification white text which does still show up on Linux.

**Comment by mr-cheffy** [comment]
>  Try going to about:addons and enabling the dark theme manually, or see if you have any other theme already enabled

Firefox themes don't work anymore. Changing these virtually does nothing

**Comment by historyb1** [comment]
> > Try going to about:addons and enabling the dark theme manually, or see if you have any other theme already enabled
> 
> Firefox themes don't work anymore. Changing these virtually does nothing

I saw the same thing

**Comment by SimoneFelici** [comment]
I have the same problem using the aur package `zen-browser-bin`
But it's not just the finder bar, it's a lot of components, like when zooming in a site:

<img width="218" height="50" alt="Image" src="https://github.com/user-attachments/assets/3cb0548a-a85c-4537-8ba1-9f1b12dbbeb0" />

The workspace icons:

<img width="222" height="53" alt="Image" src="https://github.com/user-attachments/assets/84bbd7dd-1545-4ec0-a234-343e8b37c9a2" />

The links color:

<img width="472" height="44" alt="Image" src="https://github.com/user-attachments/assets/27c6784c-0411-411f-95be-964efac15a41" />

**Comment by devz3r0** [comment]
I have the same issue that some segments are not readable on xubuntu/xfce and using the flatpak like the searchbar:

<img width="958" height="118" alt="Image" src="https://github.com/user-attachments/assets/46be054e-03cd-41d4-ad86-881df4107a0b" />

it is broken in autofillforms too like passwords.

**Comment by 0xferrous** [comment]
is there any workaround for the find bar color?

**Comment by Propheticus** [comment]
> is there any workaround for the find bar color?

The only 2 I can think of:
- Turn on dark mode in your OS's theme settings
- Switch to Zen Twilight (1.15t) where the search bar theming has been fixed. 

My current list of items ignoring the Zen theme settings and following the OS setting instead:

- ~~Search bar (ctrl + f)~~ fixed in 1.15t (and 1.14.9b)
- Library  (manage bookmarks / history / show all downloads, that stuff)
- ~~Customise toolbar (lower 1/2 of screen widget thing)~~ fixed in 1.15t (and 1.14.9b)
- Some extension (url bar) icons that switch between white/black depending on dark/light theme.
- (new) profile switcher
- web developer tools
- bottom left status bar (URL preview on hovering a link)
- page info (ctrl + i)
- ~~space emoji icon picker search text is white on white~~ looks fixed
- (delete cookie/data) confirmation dialogue/popup
- ~~custom colour transparency value in theme editor has white one white text~~ looks fixed

**Comment by 0xferrous** [comment]
I am already on 1.15t (Firefox 141.0) (2025-07-17) (64-bit) but still have that search/find bar theming issue

**Comment by emilime93** [comment]
I'm using https://septatrix.github.io/prefers-color-scheme-test/ to test this, and so far I cannot make this site report dark. On other browsers, for example Safari I get "dark", but not on Zen.

I'm on 1.14.9b and all sites are presented in light mode. I have tried to set `Language and Appearance > Website appearance` to Dark along with using the dark workspace theme. For me this only changes the browsers UI and not the websites UIs.

EDIT: I'm on macOS and have tried this with and without the OS dark mode

**Comment by 0xferrous** [comment]
i think its also worth removing the `about:addons#themes` page altogether, i tried really hard to find it and i now understand its hidden from the sidebar in `about:addons` because the configuring that is now a noop in zen.

**Comment by daika7ana** [comment]
By trial and error I have managed to find why my Zen is acting this way.

I am using the following settings in Windows 11:
<img width="1032" height="557" alt="Image" src="https://github.com/user-attachments/assets/6d074ba2-3efa-44a2-9ebc-263a2fe7e9ba" />

This way, my Windows is in dark mode, but my apps stay in light mode unless I explicitly tell them to be in dark mode.
For some reason setting the theme to a "dark mode" theme in Zen, still doesn't change all the elements into dark mode because they're linked to the OS app color mode and not Zen color mode.

I've managed to find a fix/workaround for the above explained issue. 
This way all the missing elements are now in dark mode to match with the rest of the theme.

Go into `about:config` and look for `ui.systemUsesDarkTheme`.  If it's not there, add it as a `Number` with the value of `1`.

@mr-cheffy can you please take a look into the behaviour I've described above?

**Comment by SimoneFelici** [comment]
> Go into `about:config` and look for `ui.systemUsesDarkTheme`.  If it's not there, add it as a `Number` with the value of `1`.

Thank you, this works for me too, on Linux.

**Comment by mr-cheffy** [comment]
Just right click the sidebar > edit sun > select the moon

**Comment by daika7ana** [comment]
> Just right click the sidebar > edit sun > select the moon

<img width="1161" height="646" alt="Image" src="https://github.com/user-attachments/assets/743b8c46-6017-464b-951a-05178fedccae" />

Sadly, it doesn't work. Moon is selected and elements are still in light mode.

**Comment by Propheticus** [comment]
@0xferrous 
> about:addons#themes

This should be gone in v1.14.9b, Previous versions still had some links to it from other settings pages that have been removed as well.


@mr-cheffy 
> Just right click the sidebar > edit sun > select the moon

As mentioned before, there's several areas that still follow the OS mode. https://github.com/zen-browser/desktop/issues/9229#issuecomment-3107843151

**Comment by mr-cheffy** [comment]
I see, thanks. Could this issue be renamed then?

**Comment by daika7ana** [comment]
> As mentioned before, there's several areas that still follow the OS mode. [#9229 (comment)](https://github.com/zen-browser/desktop/issues/9229#issuecomment-3107843151)
>
> For Windows users the workaround is setting dark mode in settings > personalisation > colours

(2nd quote is from the linked issues)

@Propheticus The workaround I've posted above in https://github.com/zen-browser/desktop/issues/9229#issuecomment-3126353298 forces Zen to think the OS is in dark mode, so you don't have to tinker with the OS Settings and affect all other apps. Also, somebody confirmed it to be working for Linux as well, so it's not limited to just Windows.

**Comment by devz3r0** [comment]
the workaround did not work, the search bar is still broken. Additionally  I set the variable GTK_THEME=Vivid-Dark-GTK:dark in flatseal for zen, as other flatpak apps are following it and are working, zen doesn't care.

**Comment by TNTftw21** [comment]
I just (finally) updated Zen again, and am now having a similar issue. Zen starts in light mode despite Cinnamon being set to dark mode. Forcing Zen to dark mode changes how the pages themselves are rendered but the GTK elements (such as the title bar) remain in light mode. Going into Cinnamon's settings and setting the theme to light and then back to dark causes the app to update everything, after which it works correctly. Best guess is that it's ignoring the system theme at startup and just setting itself to light mode, and changing the system theme triggers an event that causes it to switch.
Running Zen 1.14.9b via flatpak on Linux Mint 21.3, using Cinnamon 6.0.4 on X11 1.21.1.4. No other apps (including those installed through flatpak) are having this issue.

Edit: Wanted to add that `ui.systemUsesDarkTheme` does work for me, but also want to note that this seems like a workaround rather than an actual fix. It looks like that value should be set automatically based on the system theme, which isn't happening for some reason. If I ever want to switch back to light theme (God forbid) I'll have to change it in both, which defeats the point of the "auto" setting.

**Comment by Propheticus** [comment]
> Forcing Zen to dark mode changes how the pages themselves are rendered

That sounds like you're changing the general setting > website appearance. The UI dark/light mode is in the theme editor (right click sidebar > edit theme > pick the icon on top you want; auto/light/dark)

<sub>p.s. trying to help, not endorsing the situation. I think a browser-wide setting like UI dark/light mode should be in the settings and not in the workspace-specific theme editor that's hidden behind a context menu.</sub>

**Comment by Propheticus** [comment]
@historyb1 could you update the issue title to something along the lines of
_"Zen inconsistently follows system light/dark mode, ignoring the mode set in theme editor"_
(I don't have rights to do so)

**Comment by FulgerePulse** [comment]
> ~Customise toolbar (lower 1/2 of screen widget thing)~ fixed in 1.15t (and 1.14.9b)

1.14.11b is installed and the same problem persists.

**Comment by locrianz** [comment]
> It's not a bug, it works. Make sure to right click on tab bar, select edit theme and in new window that opens click on arrow to the right of little colored dots to reveal more colors, just choose some darker shade.
> 
> ![Image](https://github.com/user-attachments/assets/5d8fc0aa-0f7e-4083-812d-24b2f63adf3d)

This is a ridiculous alternative to simply being able to click "light mode" or "dark mode" in the settings. This fancy theme editor is fine for people who want it, but I can't find a way to just tell Zen "I want a plain dark-grey background, no gradients or anything".

**Comment by mr-cheffy** [comment]
If you want just a grey background, just click the `-`. @locrianz

**Comment by 0xferrous** [comment]
find bar is still unreadable for me in latest twilight: 1.15t (Firefox 142.0) (2025-08-17) (64-bit)
<img width="1521" height="61" alt="Image" src="https://github.com/user-attachments/assets/5124cc2c-6bad-4e03-ba4a-cb1b07642071" />

**Comment by Aaxper** [comment]
> Zen starts in light mode despite Cinnamon being set to dark mode. Forcing Zen to dark mode changes how the pages themselves are rendered but the GTK elements (such as the title bar) remain in light mode. Going into Cinnamon's settings and setting the theme to light and then back to dark causes the app to update everything, after which it works correctly. 

I'm also experiencing this exact issue

**Comment by MichaelGloessl04** [comment]
> find bar is still unreadable for me in latest twilight: 1.15t (Firefox 142.0) (2025-08-17) (64-bit) <img alt="Image" width="1521" height="61" src="https://private-user-images.githubusercontent.com/213212767/478818083-5124cc2c-6bad-4e03-ba4a-cb1b07642071.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU3OTgyMjUsIm5iZiI6MTc1NTc5NzkyNSwicGF0aCI6Ii8yMTMyMTI3NjcvNDc4ODE4MDgzLTUxMjRjYzJjLTZiYWQtNGUwMy1iYTRhLWNiMWIwNzY0MjA3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyMVQxNzM4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDAxMDZmNTQ5NzYzNTE1Y2M4MDEwNWVmYTMzMmIxYzEwMjA5NjViYTk3ODZjYTI2NGUyNDE1MmJkNzYzZDcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-_zO4ODen3LfaTA9cPQoXNU5O9SOhMxisdQnw6ihQbk">

Im experiencing the same issue on arch hyprland

**Comment by VoiceShifter** [comment]
Why issue closed, if its still persist on latest stable zen?

**Comment by Propheticus** [comment]
Currently, in the latest build (Twilight 1.15t), I found these items do _not_ follow the theme editor's selected mode but the OS-level mode instead:

-   Library (manage bookmarks / history / show all downloads, that stuff)
-   Some extension (url bar) icons that switch between white/black depending on dark/light theme.
-   (new) profile switcher
-   web developer tools
-   bottom left status bar (URL preview on hovering a link)
-   page info (ctrl + i)
-   delete cookie/data) confirmation dialogue/popup

Does not look fixed.

Step to reproduce:
- In the OS pick light mode
- In the Zen theme editor pick dark mode (moon)
- Spot several items are light.

**Comment by Ev357** [comment]
Just a question, this also broke my catppuccin css theme, i managed to fix it with `ui.systemUsesDarkTheme` but thats not really a solution. Will there be another way to use themes? It would be really nice if there was a way to decleratively set the color scheme. The color picker is kinda nice but i cannot set the theme trough hex codes or anything like that and i don't really want to eyeball everything. Will there be some other way to do this stuff?

**Comment by lishaduck** [comment]
I'm running latest twilight (macOS), and this seems completely broken. Internal pages and dialogs respect my system color scheme, but actual webpages, extensions, and their icons remain in light mode (even when explicitly forcing dark mode in the "edit theme" pane, appearance set to automatic in settings). In the inspector, it looks like media queries match light mode 100% of the time and never dark mode.

I do have dark reader, but it's turned off (and that should make it dark, not light).

**Comment by daika7ana** [comment]
Updated to `1.15.4b` which included commit 213151e but the issue is still present.
All the items in the list provided by @Propheticus above are still in light mode.

**Comment by VoiceShifter** [comment]
Downloaded appimage of 1.15.4b - problem still persist, bookmarks are not present.

**Comment by mhkarimi1383** [comment]
I also have the same problem with dev tools. it is light when I have selected dark theme

**Comment by mr-cheffy** [comment]
Note that these elements *are* supposed to be dark / light depending on the workspace color.

**Comment by mhkarimi1383** [comment]
> Note that these elements _are_ supposed to be dark / light depending on the workspace color.

@mr-cheffy My workspace is dark but devtools is not dark

**Comment by mr-cheffy** [comment]
Devtools are part of the web content, meaning they are part of the system theme or global dark mode

**Comment by mhkarimi1383** [comment]
@mr-cheffy 

My global theme is also dark but devtools is light

**Comment by mr-cheffy** [comment]
Right, devtools do indeed have their own sort of theming system. I'd open a new issue about this specifically as we are starting to deviate from the original issue

**Comment by mhkarimi1383** [comment]
> Right, devtools do indeed have their own sort of theming system. I'd open a new issue about this specifically as we are starting to deviate from the original issue


Ok, thanks

**Comment by mhkarimi1383** [comment]
@mr-cheffy 

Hello again Some problems are fixed by changing my GTK Theme, This option should be present is settings too, So I can make my Browser UI to be dark independent from my OS configuration

**Comment by 0xferrous** [comment]
<img width="852" height="292" alt="Image" src="https://github.com/user-attachments/assets/441dbd26-b87e-41f0-8f3d-3c5599cb282f" />

<img width="989" height="42" alt="Image" src="https://github.com/user-attachments/assets/abb03bbb-23f0-47b1-be45-89ef6ffb21c0" />

issue is back after my latest nightly update

**Comment by Propheticus** [comment]
@0xferrous Which OS? Tarball install of 1.18t on CachyOS looks ok

<img width="921" height="474" alt="Image" src="https://github.com/user-attachments/assets/2b4ef94f-b53f-42e2-9bce-d1f45bf604af" />

**Comment by 0xferrous** [comment]
nixos
